Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-02, with the labels that each got.

#99 Reworked badge topic
  en/components/badge.md
Labels: Topic

#90 Create igx-carousel user story and update current topic based on the article guidance
  en/components/carousel.md
  jp/components/carousel.md
Labels: Topic

#106 Reworking Button samples.
  en/components/button.md
Labels: Topic, localization-pending

#91 Demos refactoring
  en/components/checkbox.md
  en/components/radio_button.md
  en/components/switch.md
Labels: Topic, localization-pending

#96 add topic for toggle
  en/components/toc.yml
  en/components/toggle.md
  jp/components/toc.yml
  jp/components/toggle.md
Labels: Topic

#87 Create Label and Input Demo.
  en/components/input.md
  en/components/label.md
  en/components/label_input.md
  en/components/toc.yml
  jp/components/input.md
  jp/components/label.md
  jp/components/label_input.md
  jp/components/toc.yml
Labels: Topic, localization-pending

#111 Updated badge topic with latest control changes
  en/components/badge.md
Labels: Topic

#116 Add stackblitz button to label-input demo
  en/components/label_input.md
  jp/components/label_input.md
Labels: Topic

#112 igxAvatar demo refactoring
  en/components/avatar.md
  package-lock.json
Labels: Topic, localization-pending

#115 Add igxForOf topic
  en/components/for_of.md
  en/components/toc.yml
  jp/components/for_of.md
  jp/components/toc.yml
Labels: Topic

#123 Ripple Samples Rework
  en/components/button.md
  en/components/icon.md
  en/components/ripple.md
Labels: Topic

#130 Updating API and adding empty list template sample for igx-list.
  en/components/list.md
  jp/components/list.md
Labels: localization-pending

#138 Reworked snackbar topic
  en/components/badge.md
  en/components/slider.md
  en/components/snackbar.md
Labels: Topic

#142 Updated linear and circular progressbar topics
  en/components/circular_progress.md
  en/components/linear_progress.md
  jp/components/circular_progress.md
  jp/components/linear_progress.md
Labels: Topic, localization-pending

#149 Subitems in TOC Navigation styled
  en/components/themes.md
  en/components/toc.yml
  templates/ignite-ui-template/styles/css/main.css
  templates/ignite-ui-template/styles/docfx.js
  templates/ignite-ui-template/styles/sass/partials/_button-link.scss
  templates/ignite-ui-template/styles/sass/partials/_toc.scss
Labels: enhancement, styling

#147 Nav drawer topic feedback fixes
  en/components/navdrawer.md
Labels: Topic, localization-pending

#140 Refactor dialog topic and add api summary
  en/components/dialog.md
  en/components/toc.yml
  jp/components/dialog.md
Labels: Topic, enhancement, localization-pending

#141 Toast topic reworked
  en/components/snackbar.md
  en/components/toast.md
Labels: Topic

#148 Create igx-calendar user story and update current topic
  en/components/calendar.md
  jp/components/calendar.md
Labels: Topic, localization-pending

#150 Updating the TabBar demo page
  en/components/tabbar.md
  jp/components/tabbar.md
Labels: Topic, localization-pending

#145 Improve the section with binding igxForOf to remote service
  en/components/for_of.md
  jp/components/for_of.md
Labels: Topic

#153 Date picker topics
  en/components/date_picker.md
  jp/components/date_picker.md
Labels: localization-pending, status: awaiting-test

#154 remove igxscroll
  en/components/scrollbar.md
  en/components/toc.yml
  jp/components/scrollbar.md
  jp/components/toc.yml
Labels: status: verified

#157 Fixing lexicographical errors.
  en/components/buttonGroup.md
Labels: bug, status: verified

#155 Add information regarding local variables.
  en/components/for_of.md
  jp/components/for_of.md
Labels: status: verified

#158 Remove unnecessary stackblitz buttons.
  en/components/avatar.md
Labels: Topic

#159 `formatOptions`, `formatViews` methods from 5.2 version highlighted in the topic
  en/components/calendar.md
  en/components/carousel.md
Labels: status: verified

#160 Add description for state properties and some more small touches.
  en/components/for_of.md
  jp/components/for_of.md
Labels: status: verified

#161 Adding border to the sample containers.
  en/components/tabbar.md
  jp/components/tabbar.md
Labels: status: in-test

#162 highlight api methods
  jp/components/calendar.md
Labels: status: verified

#163 Themes documentation
  en/components/themes.md
Labels: Topic, localization-pending, status: verified

#164 #121 Fixed a few typos in Tab bar article.
  en/components/tabbar.md
Labels: status: verified

#166 Made changes that did not involve translation
  jp/components/avatar.md
  jp/components/carousel.md
Labels: status: verified

#167 Fix broken links and typos in calendar topic
  en/components/calendar.md
  jp/components/calendar.md
Labels: status: verified

#169 Added assets demo url based on environment
  templates/ignite-ui-template/styles/stackblitz-handler.js
Labels: status: awaiting-test

#171 Fixing typos for list and tabbar.
  en/components/list.md
  en/components/tabbar.md
Labels: bug, status: verified

#165 Grid documentation update
  en/components/grid.md
Labels: localization-pending

#172 Added Japanese header & footer
  jp/components/circular_progress.md
  jp/components/dialog.md
  jp/components/label_input.md
  jp/components/linear_progress.md
  jp/components/toggle.md
  templates/ignite-ui-template/conceptual.html.primary.js
  templates/ignite-ui-template/partials/footer.tmpl.partial
  templates/ignite-ui-template/partials/infrafoot.ja.tmpl.partial
  templates/ignite-ui-template/partials/infrafoot.tmpl.partial
  templates/ignite-ui-template/partials/infranav.ja.tmpl.partial
  templates/ignite-ui-template/partials/infranav.tmpl.partial
  templates/ignite-ui-template/partials/navbar.tmpl.partial
Labels: status: in-test

#174 Fixed an issue with Card article where the bottom part was cut off.
  en/components/card.md
Labels: status: verified

#175 Fix calendar samples height
  en/components/calendar.md
  jp/components/calendar.md
Labels: status: verified

#178 Fixed typos in toast topic
  en/components/toast.md
Labels: bug, status: verified

#177 Added translations for rewritten topics
  jp/components/badge.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/card.md
  jp/components/circular_progress.md
  jp/components/date_picker.md
  jp/components/dialog.md
  jp/components/for_of.md
  jp/components/linear_progress.md
  jp/components/list.md
  jp/components/navdrawer.md
  jp/components/slider.md
  jp/components/snackbar.md
  jp/components/tabbar.md
  jp/components/themes.md
  jp/components/toc.yml
Labels: status: verified

#182 Fixed StackBlitz buttons pop-up warning
  en/components/grid.md
  jp/components/grid.md
  templates/ignite-ui-template/styles/css/main.css
  templates/ignite-ui-template/styles/stackblitz-handler.js
Labels: status: verified
