Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-06, with the labels that each got.

#402 feat: Add topic for igx-drop-down component.
  en/components/drop_down.md
  en/components/toc.yml
  en/components/toggle.md
  jp/components/drop_down.md
  jp/components/toc.yml
  jp/components/toggle.md
Labels: status: localized, status: verified

#425 Update card sample iframe height
  jp/components/card.md
Labels: status: verified

#423 Updated Ignite UI DocFX template version to 1.0.4
  en/docfx.json
  en/global.json
  jp/docfx.json
  jp/global.json
  package-lock.json
  package.json
Labels: status: verified

#431 Updating names in card doc
  en/components/card.md
  jp/components/card.md
Labels: status: verified

#432 Update drop_down.md
  jp/components/drop_down.md
Labels: status: verified

#433 chore(packages.json): Update gulp
  package.json
Labels: status: verified

#434 Adding description for content projection
  en/components/icon.md
  jp/components/icon.md
Labels: status: pending-localization, status: verified

#436 fix(exporters): adding a note regarding JSZip
  en/components/exporter_csv.md
  en/components/exporter_excel.md
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
Labels: status: localized, status: verified

#435 Updated JP for "Adding description for content projection #434".
  jp/components/icon.md
Labels: status: localized, status: verified

#446 Translated peer dependency.
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
Labels: enhancement, status: in-review, status: localized

#438 GroupBy topic
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: status: verified

#451 docs(*): Fixing GroupBy syntax errors and sample Url.
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: status: verified

#449 chore(igxDatePicker): document new inputs
  en/components/date_picker.md
  jp/components/date_picker.md
Labels: status: localized, status: verified

#447 Added Grids and Lists overview; updated index.md default page; and ad…
  en/components/grids_and_lists.md
  en/components/toc.yml
  en/index.md
  jp/components/grids_and_lists.md
  jp/components/toc.yml
  jp/index.md
  package.json
Labels: status: pending-localization, status: verified

#442 chore(igxGrid): add known grid limitations section
  en/components/grid.md
  jp/components/grid.md
Labels: status: localized, status: verified

#456 Know issues limitations
  en/components/grid.md
  jp/components/grid.md
Labels: status: verified

#459 Ys 0621
  jp/components/grids_and_lists.md
Labels: status: localized

#461 chore(igxGrid): create multi column headers topic #460
  en/components/grid_multi_column_headers.md
  en/components/toc.yml
  jp/components/grid_multi_column_headers.md
  jp/components/toc.yml
Labels: status: verified

#463 Ys 0622
  jp/components/grids_and_lists.md
  jp/components/toc.yml
Labels: status: localized

#465 Corrected ARIA tooltip.
  jp/components/grids_and_lists.md
Labels: enhancement

#448 docs(grid): Added docs for column moving #935
  en/components/grid.md
  en/components/grid_column_moving.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_groupby.md
  en/components/grid_paging.md
  en/components/grid_search.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  en/components/tabs.md
  en/components/toc.yml
  jp/components/grid.md
  jp/components/grid_column_moving.md
  jp/components/grid_column_pinning.md
  jp/components/grid_column_resizing.md
  jp/components/grid_filtering.md
  jp/components/grid_groupby.md
  jp/components/grid_paging.md
  jp/components/grid_search.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
  jp/components/tabs.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#464 Grid cell editing topic
  en/components/grid.md
  en/components/grid_editing.md
  en/components/toc.yml
  jp/components/grid.md
  jp/components/grid_editing.md
  jp/components/toc.yml
Labels: status: in-test, status: pending-localization, status: verified

#471 Adding new known issue related to min allowed col widths.
  en/components/grid.md
  jp/components/grid.md
Labels: grid, status: localized

#472 chore(*): Adding new limitation related to max amount of grouped colu…
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: grid, status: localized

#469 fix(groupby): adding groupby topic to toc #468
  en/components/toc.yml
  jp/components/toc.yml
Labels: grid, status: localized, status: verified

#455 Translation update.
  jp/components/grid_groupby.md
Labels: enhancement

#413 docs(grid): Updated remote virtualization topic - added sorting and filtering
  en/components/grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: status: localized, status: verified

#445 docs(toolbar): adding page for the igxGrid toolbar
  en/components/grid_toolbar.md
  en/components/toc.yml
  jp/components/grid_toolbar.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#467 docs(grid): Updated docs for filtering with latest changes #1355
  en/components/grid.md
  en/components/grid_filtering.md
  jp/components/grid.md
  jp/components/grid_filtering.md
Labels: grid, status: localized, status: verified

#482 chore: Uncomment dropdown samples from TOC.
  en/components/toc.yml
  jp/components/toc.yml
Labels: enhancement

#458 Combo
  en/components/combo.md
  en/components/toc.yml
  jp/components/combo.md
  jp/components/toc.yml
Labels: Topic, combo, status: localized

#486 fix: Update docs to match updated samples.
  en/components/drop_down.md
  jp/components/drop_down.md
Labels: status: pending-localization, status: verified

#480 Column group topic
  en/components/grid_multi_column_headers.md
  jp/components/grid_multi_column_headers.md
Labels: status: pending-localization, status: verified

#478 docs(radio-group): Added info about new radio-group
  en/components/grid_virtualization.md
  en/components/radio_button.md
  en/components/toc.yml
  jp/components/grid_virtualization.md
  jp/components/radio_button.md
  jp/components/toc.yml
Labels: radio, status: localized, status: verified

#479 chore(*): Improving issue description.
  en/components/grid.md
  jp/components/grid.md
Labels: status: localized, status: verified

#481 IgxOverlay Topic
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  en/components/toc.yml
  jp/components/overlay_main.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
  jp/components/toc.yml
Labels: Topic, overlay, status: localized, status: verified

#489 chore(grid): remove new from old topics
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified

#487 Updated description and keyword for Toolbar.
  jp/components/grid_toolbar.md
Labels: enhancement

#450 docs(columnHiding): adding page for the igxGrid columnHiding
  en/components/grid_column_hiding.md
  en/components/toc.yml
  jp/components/grid_column_hiding.md
  jp/components/toc.yml
Labels: enhancement, status: pending-localization, status: verified

#488 Localized for #486, #480,#464.
  jp/components/drop_down.md
  jp/components/grid_editing.md
  jp/components/grid_multi_column_headers.md
  jp/components/toc.yml
Labels: status: localized

#502 docs(radio-group): Added tag 'new' to the radio-group demo.
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified

#505 fix: Remove excess IgxToggleModule as not used in the sample.
  en/components/drop_down.md
  jp/components/drop_down.md
Labels: status: verified

#503 docs(grid): Removed tag 'new' from resizing sample
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified

#513 Add forms samples to combo topics
  en/components/combo.md
  jp/components/combo.md
Labels: combo, status: pending-localization, status: verified

#506 docs(grid): Fix in column moving demo - added comments for pinning
  en/components/grid_column_moving.md
Labels: grid, status: verified

#452 docs(igxChip): Adding Chip topic
  en/components/chip.md
  en/components/toc.yml
  en/images/dragging.gif
  jp/components/chip.md
  jp/components/toc.yml
  jp/images/dragging.gif
Labels: Topic, chip, status: localized

#501 Ys 0628 2
  jp/components/grid_column_hiding.md
  jp/components/toc.yml
Labels: status: localized

#512 Updated igniteui-docfx-template
  en/docfx.json
  en/resources-en.json
  jp/docfx.json
  jp/resources-ja.json
  package-lock.json
  package.json
Labels: status: verified

#515 docs(groupby): Fixing GroupBy Stackblitz sample.
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: status: verified

#520 Update iframe id
  en/components/grid_editing.md
  jp/components/grid_editing.md
Labels: grid, status: verified

#504 docs(toolbar): adding information regarding column hiding and pinning
  en/components/grid_toolbar.md
  jp/components/grid_toolbar.md
Labels: enhancement, grid, status: verified

#526 fix: update igxToggle docfx pages
  en/components/toggle.md
  jp/components/toggle.md
Labels: status: pending-localization, status: verified, toggle
