Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-03, with the labels that each got.

#186 Removed warning for peerDependency on hammerjs
  en/components/calendar.md
  en/components/carousel.md
  en/components/list.md
  en/components/tabbar.md
  en/components/toggle.md
  jp/components/calendar.md
  jp/components/carousel.md
  jp/components/list.md
  jp/components/tabbar.md
  jp/components/toggle.md
Labels: status: verified

#187 Translated subheader
  jp/toc.yml
Labels: status: verified

#193 fix typos in calendar topic
  en/components/calendar.md
Labels: status: verified

#204 Update tabbar.md
  jp/components/tabbar.md
Labels: status: verified

#201 Update navdrawer.md
  jp/components/navdrawer.md
Labels: status: verified

#206 Update layout.md
  jp/components/layout.md
Labels: enhancement

#207 Update carousel.md
  jp/components/carousel.md
Labels: enhancement

#208 Update card.md
  jp/components/card.md
Labels: enhancement

#209 Update calendar.md
  jp/components/calendar.md
Labels: enhancement

#210 Update date_picker.md
  jp/components/date_picker.md
Labels: enhancement

#211 fix(stackblitz button): added disabled state styles for stackblitz bu…
  en/images/stackblitz-logo-dark.svg
  jp/images/stackblitz-logo-dark.svg
  templates/ignite-ui-template/styles/css/main.css
  templates/ignite-ui-template/styles/sass/partials/_button-link.scss
Labels: status: awaiting-test

#213 refactor(partial templates): remove unused partial templates
  templates/ignite-ui-template/partials/_affix.liquid
  templates/ignite-ui-template/partials/_breadcrumb.liquid
  templates/ignite-ui-template/partials/_footer.liquid
  templates/ignite-ui-template/partials/_head.liquid
  templates/ignite-ui-template/partials/_logo.liquid
  templates/ignite-ui-template/partials/_navbar.liquid
  templates/ignite-ui-template/partials/_scripts.liquid
  templates/ignite-ui-template/partials/_toc.liquid
Labels: status: awaiting-test

#216 Update radio_button.md
  jp/components/radio_button.md
Labels: enhancement

#215 Localize note blocks
  en/resources-en.json
  jp/resources-ja.json
  templates/ignite-ui-template/styles/docfx.js
Labels: status: awaiting-test

#223 Create web.config
  web.config
Labels: enhancement

#224 Update angularSampes.nuspec
  angularSampes.nuspec
Labels: enhancement

#214 Adding Column Pinning to igxGrid doc
  en/components/grid.md
  jp/components/grid.md
Labels: Topic, status: localized

#227 Update grid.md
  jp/components/grid.md
Labels: enhancement

#229 fix dialog snippet with correctly bound property
  en/components/dialog.md
  jp/components/dialog.md
Labels: status: verified

#226 Implementing calendar template parts parsing for IE/Edge
  en/components/calendar.md
  en/components/date_picker.md
  jp/components/calendar.md
  jp/components/date_picker.md
Labels: Topic, status: verified

#232 Update grid.md
  jp/components/grid.md
Labels: enhancement

#225 Added subtopic for igx-grid-summary in Grid topic
  en/components/grid.md
  jp/components/grid.md
Labels: status: verified

#235 Update description of formatViews property
  en/components/calendar.md
  jp/components/calendar.md
Labels: enhancement

#218 Added topic for mask directive
  en/components/mask.md
  en/components/switch.md
  en/components/toc.yml
  jp/components/mask.md
  jp/components/toc.yml
Labels: Topic, status: pending-localization

#220 Add samples for timepicker
  en/components/time_picker.md
  en/components/toc.yml
  jp/components/time_picker.md
  jp/components/toc.yml
Labels: Topic, enhancement, status: pending-localization
