Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-11, with the labels that each got.

#766 updating pie and doughnut
  en/components/doughnutchart.md
  en/components/piechart.md
Labels: status: pending-localization

#774 bug fixing
  en/components/doughnutchart.md
Labels: status: in-progress

#775 Updated with KR translations.
  kr/components/exporter_excel.md
  kr/components/grid_groupby.md
  kr/components/grid_multi_column_headers.md
  kr/components/grid_paste_excel.md
  kr/components/grid_row_editing.md
  kr/components/grid_transactions.md
Labels: status: verified

#783 bug fixing - 259040 259044
  en/components/doughnutchart.md
  en/components/piechart.md
Labels: status: verified

#764 TreeGrid Docs
  en/components/toc.yml
  en/components/treegrid.md
  jp/components/toc.yml
  jp/components/treegrid.md
Labels: status: pending-localization, status: verified

#767 Refactor row editing/transactions topics
  en/components/grid_batch_editing.md
  en/components/grid_editing.md
  en/components/grid_row_editing.md
  en/components/grid_transactions.md
  en/components/toc.yml
  jp/components/grid_batch_editing.md
  jp/components/grid_editing.md
  jp/components/grid_row_editing.md
  kr/components/grid_batch_editing.md
  kr/components/grid_editing.md
  kr/components/toc.yml
Labels: grid, status: pending-localization, status: verified

#792 Change IgxTreeGrid topics to use new filtering property
  en/components/treegrid.md
  jp/components/treegrid.md
Labels: status: verified

#797 mdd-259091
  en/components/piechart.md
Labels: status: pending-localization

#801 Final updates before 18.2.
  kr/components/categorychart_explore_chart_types.md
  kr/components/exporter_excel.md
  kr/components/grid.md
  kr/components/grid_virtualization.md
Labels: status: verified

#802 Update Stackblitz Button Label
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  kr/components/overlay_main.md
  kr/components/overlay_position.md
  kr/components/overlay_scroll.md
Labels: overlay, status: verified

#791 Update latest row editing API
  en/components/grid_batch_editing.md
  en/components/grid_row_editing.md
  jp/components/grid_batch_editing.md
  jp/components/grid_row_editing.md
  kr/components/grid_batch_editing.md
  kr/components/grid_row_editing.md
Labels: grid, status: verified

#806 chore(*): Adding FinJS sample to the grid topic
  en/components/grid.md
Labels: status: in-test

#805 Updated JP.
  jp/components/grid_batch_editing.md
  jp/components/toc.yml
  jp/components/treegrid_batch_editing.md
Labels: status: verified

#803 Enhancement - Add demo at start of expansion panel topic
  en/components/expansion_panel.md
  jp/components/expansion_panel.md
  kr/components/expansion_panel.md
Labels: Topic, enhancement, expansion-panel, status: verified

#807 Move row editing topic to the overview section.
  en/components/toc.yml
  en/components/treegrid.md
  jp/components/toc.yml
  jp/components/treegrid.md
  jp/components/treegrid_row_editing.md
  kr/components/toc.yml
  kr/components/treegrid_row_editing.md
Labels: status: pending-localization, status: verified

#809 add link to the keyboard nav specification in grid topic
  en/components/grid.md
  jp/components/grid.md
Labels: status: verified

#808 docs(grid): Custom filtering operators #770
  en/components/grid_filtering.md
  jp/components/grid_filtering.md
Labels: grid, status: verified

#811 Updated igniteui-docfx-template to 2.0.3
  package-lock.json
  package.json
Labels: status: verified

#814 Fixed issues in JP.
  jp/components/categorychart_high_volume_data.md
  jp/components/chip.md
  jp/components/combo_features.md
  jp/components/drop_down.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_sparklines.md
  jp/components/exporter_excel.md
  jp/components/financialchart_binding_to_multiple_data.md
  jp/components/financialchart_explore_chart_types.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/grid_batch_editing.md
  jp/components/grid_column_hiding.md
  jp/components/grid_conditional_cell_styling.md
  jp/components/grid_displayDensity.md
  jp/components/grid_filtering.md
  jp/components/grid_multi_column_headers.md
  jp/components/grid_toolbar.md
  jp/components/list.md
  jp/components/radio_button.md
  jp/components/shadows.md
  jp/components/texthighlight.md
  jp/components/themes/palette.md
  jp/components/themes/theming-demo.md
  jp/components/toc.yml
  jp/components/treegrid.md
Labels: status: localized, status: verified

#817 Updated for #809.
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_sparklines.md
  jp/components/grid.md
  jp/components/grid_batch_editing.md
Labels: status: localized, status: verified

#824 Fix typo in Grid Display Density topic.
  en/components/grid_displayDensity.md
Labels: bug, status: verified

#825 KB navigation section update in Grid "Group By" topic.
  en/components/grid_groupby.md
Labels: Topic, grid, status: pending-localization, status: verified

#827 Update for Circular and Linear progress bars topics.
  en/components/circular_progress.md
  en/components/linear_progress.md
Labels: Topic, enhancement, status: pending-localization, status: verified

#829 Adjusted height of samples' containers in topics
  en/components/categorychart.md
  en/components/categorychart_annotation_layers.md
  en/components/categorychart_axis_options.md
  en/components/categorychart_configuration_options.md
  en/components/categorychart_high_volume_data.md
  en/components/categorychart_highlighting.md
  en/components/categorychart_real_time_data.md
  en/components/categorychart_tooltip_templates.md
  en/components/categorychart_tooltip_types.md
  en/components/doughnutchart.md
  en/components/excel_library.md
  en/components/excel_library_using_cells.md
  en/components/excel_library_using_tables.md
  en/components/excel_library_using_workbooks.md
  en/components/excel_library_using_worksheets.md
  en/components/excel_library_working_with_charts.md
  en/components/excel_library_working_with_grids.md
  en/components/excel_library_working_with_sparklines.md
  en/components/financialchart.md
  en/components/financialchart_annotation_layers.md
  en/components/financialchart_binding_to_multiple_data.md
  en/components/financialchart_configuration_options.md
  en/components/financialchart_custom_indicators.md
  en/components/financialchart_explore_chart_types.md
  en/components/financialchart_high_volume_data.md
  en/components/financialchart_panes.md
  en/components/financialchart_performance.md
  en/components/financialchart_real_time_data.md
  en/components/financialchart_tooltip_templates.md
  en/components/financialchart_tooltip_types.md
  en/components/piechart.md
  en/components/toc.yml
Labels: status: in-test

#830 Kr 1112
  kr/components/bulletgraph.md
  kr/components/categorychart_annotation_layers.md
  kr/components/categorychart_highlighting.md
  kr/components/categorychart_tooltip_templates.md
  kr/components/circular_progress.md
  kr/components/display_density.md
  kr/components/expansion_panel.md
  kr/components/financialchart_tooltip_templates.md
  kr/components/for_of.md
  kr/components/grid_batch_editing.md
  kr/components/grid_column_hiding.md
  kr/components/grid_paging.md
  kr/components/grid_row_editing.md
  kr/components/grid_toolbar.md
  kr/components/grid_virtualization.md
  kr/components/linear_progress.md
  kr/components/lineargauge.md
  kr/components/navbar.md
  kr/components/ripple.md
  kr/components/snackbar.md
  kr/components/tabbar.md
  kr/components/toc.yml
  kr/components/treegrid.md
Labels: status: verified

#831 Jp 1112
  jp/components/circular_progress.md
  jp/components/grid_groupby.md
  jp/components/linear_progress.md
  jp/components/toc.yml
Labels: status: verified

#833 Fixed #832.
  jp/components/grid_search.md
Labels: status: verified

#826 docs(*): Headers size fixed to be consistent in topics #
  en/components/button.md
  en/components/buttonGroup.md
  en/components/icon.md
  en/components/input_group.md
  en/components/label_input.md
  en/components/radio_button.md
  en/components/tabbar.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/radio_button.md
  jp/components/tabbar.md
  kr/components/button.md
  kr/components/buttonGroup.md
  kr/components/icon.md
  kr/components/input_group.md
  kr/components/label_input.md
  kr/components/radio_button.md
  kr/components/tabbar.md
Labels: status: verified

#842 Fix truncated drop down samples.
  en/components/drop_down.md
  jp/components/drop_down.md
  kr/components/drop_down.md
Labels: bug, severity: low, status: localized, status: verified

#834 Updated images to feature the new Filter UI
  en/components/grids_and_lists.md
  jp/components/grids_and_lists.md
  kr/components/grids_and_lists.md
Labels: status: verified

#845 Kr 1120
  kr/components/avatar.md
  kr/components/badge.md
  kr/components/button.md
  kr/components/buttonGroup.md
  kr/components/calendar.md
  kr/components/card.md
  kr/components/carousel.md
  kr/components/categorychart_highlighting.md
  kr/components/checkbox.md
  kr/components/chip.md
  kr/components/combo.md
  kr/components/combo_cascading.md
  kr/components/combo_features.md
  kr/components/combo_remote.md
  kr/components/combo_templates.md
  kr/components/date_picker.md
  kr/components/dialog.md
  kr/components/doughnutchart.md
  kr/components/drag_drop.md
  kr/components/drop_down.md
  kr/components/exporter_csv.md
  kr/components/financialchart_annotation_layers.md
  kr/components/icon.md
  kr/components/input_group.md
  kr/components/input_group_reactive_forms.md
  kr/components/label_input.md
  kr/components/layout.md
  kr/components/list.md
  kr/components/mask.md
  kr/components/navdrawer.md
  kr/components/overlay_main.md
  kr/components/overlay_position.md
  kr/components/overlay_scroll.md
  kr/components/piechart.md
  kr/components/radialgauge.md
  kr/components/radio_button.md
  kr/components/slider.md
  kr/components/switch.md
  kr/components/tabs.md
  kr/components/texthighlight.md
  kr/components/themes/theming-demo.md
  kr/components/time_picker.md
  kr/components/toast.md
  kr/components/toc.yml
  kr/components/toggle.md
  kr/components/tooltip.md
  kr/components/treegrid.md
  kr/components/treegrid_batch_editing.md
Labels: status: verified

#846 Fixing and adding links for Display Density/Toggle/Theming Demo topics.
  en/components/grid_displayDensity.md
  en/components/themes/theming-demo.md
  en/components/toggle.md
  jp/components/grid_displayDensity.md
  jp/components/themes/theming-demo.md
  jp/components/toggle.md
  kr/components/grid_displayDensity.md
  kr/components/themes/theming-demo.md
  kr/components/toggle.md
Labels: status: verified, typedoc

#854 Fixed #850.
  kr/components/categorychart_tooltip_types.md
  kr/components/financialchart_tooltip_types.md
  kr/components/toc.yml
Labels: status: verified

#857 Updating template with bundling and minification functionality
  en/docfx.json
  gulpfile.js
  jp/docfx.json
  kr/docfx.json
  package-lock.json
  package.json
Labels: status: verified
