Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-09, with the labels that each got.

#674 docs(tabs): Updated code snippet in en and jp topic #628
  en/components/tabs.md
  jp/components/tabs.md
Labels: status: verified

#663 Rename selector to 'igx-date-picker',
  en/components/date_picker.md
  en/components/grid_editing.md
  jp/components/date_picker.md
  jp/components/grid_editing.md
Labels: Topic, status: verified

#673 docs(grid): Code snippets updated #627
  en/components/grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: status: verified

#675 Ys 0903
  jp/components/calendar.md
  jp/components/date_picker.md
  jp/components/themes/palette.md
  jp/components/themes/theming-demo.md
  jp/components/toc.yml
Labels: status: localized

#677 Add time-picker and date-picker input group template sample.
  en/components/date_picker.md
  en/components/time_picker.md
  jp/components/date_picker.md
  jp/components/time_picker.md
Labels: status: pending-localization, status: verified

#682 Fixed #681.
  jp/components/calendar.md
  jp/components/date_picker.md
  jp/components/time_picker.md
Labels: status: localized, status: resolved

#680 Add link to Remote Filtering/Sorting sample.
  en/components/grid_filtering.md
  en/components/grid_sorting.md
  jp/components/grid_filtering.md
  jp/components/grid_sorting.md
Labels: grid, status: localized, status: verified

#686 Fixed import statement as per #679
  jp/components/categorychart.md
Labels: status: verified

#687 Update grid paging topic for remote paging
  en/components/grid_paging.md
  jp/components/grid_paging.md
Labels: enhancement, grid, status: pending-localization, status: verified

#689 Fix id inconsistency
  en/components/grid_paging.md
  jp/components/grid_paging.md
Labels: status: verified

#685 onAnimation event added in igxOverlay
  en/components/overlay_main.md
Labels: overlay, status: verified

#690 docs(grid): Conditional cell styling topic #1079
  en/components/grid_conditional_cell_styling.md
  en/components/toc.yml
  jp/components/grid_conditional_cell_styling.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#692 Add limitations table to the docs
  en/components/grid_search.md
  jp/components/grid_search.md
Labels: grid, search, status: localized, status: verified

#705 update igniteui-docx-template
  package-lock.json
  package.json
Labels: status: verified

#693 Downgrading browser-sync npm package because of infinite reloading
  package-lock.json
  package.json
Labels: status: verified

#701 DropDown, Combo - update api tables to links.
  en/components/combo.md
  en/components/combo_cascading.md
  en/components/combo_features.md
  en/components/combo_remote.md
  en/components/combo_templates.md
  en/components/drop_down.md
  jp/components/combo.md
  jp/components/combo_cascading.md
  jp/components/combo_features.md
  jp/components/combo_remote.md
  jp/components/combo_templates.md
  jp/components/drop_down.md
Labels: Topic, combo, dropdown, status: verified

#716 Main grid changes
  en/components/grid.md
  en/components/grid_editing.md
  jp/components/grid.md
  jp/components/grid_editing.md
Labels: Topic, grid, status: verified, typedoc

#720 update paging and sorting topics
  en/components/grid_paging.md
  en/components/grid_sorting.md
  jp/components/grid_paging.md
  jp/components/grid_sorting.md
Labels: status: verified

#710 Removed API tables and added links to documentation
  en/components/navdrawer.md
  jp/components/navdrawer.md
Labels: Topic, status: verified

#711 Update overlay topic API links
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  jp/components/overlay_main.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
Labels: Topic, overlay, status: verified
