Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-10, with the labels that each got.

#678 Topic IgxList panning templates
  en/components/list.md
  jp/components/list.md
Labels: list, status: localized, status: verified

#671 Topic - IgxExpansionPanel - Add Topic and demos for control
  en/components/expansion_panel.md
  en/components/toc.yml
  jp/components/expansion_panel.md
  jp/components/toc.yml
Labels: Topic, expansion-panel, status: pending-localization, status: verified

#706 Providing Typedoc and Sassdoc references for EN and JP topics.
  en/components/calendar.md
  en/components/carousel.md
  en/components/circular_progress.md
  en/components/date_picker.md
  en/components/dialog.md
  en/components/grid_displayDensity.md
  en/components/grid_multi_column_headers.md
  en/components/layout.md
  en/components/linear_progress.md
  en/components/slider.md
  en/components/toggle.md
  jp/components/calendar.md
  jp/components/carousel.md
  jp/components/circular_progress.md
  jp/components/date_picker.md
  jp/components/dialog.md
  jp/components/grid_displayDensity.md
  jp/components/grid_multi_column_headers.md
  jp/components/layout.md
  jp/components/linear_progress.md
  jp/components/slider.md
  jp/components/toggle.md
Labels: Topic, calendar, grid, multi-column headers, status: in-test, typedoc

#721 Grid summaries changes
  en/components/grid_summaries.md
  jp/components/grid_summaries.md
Labels: grid, status: verified, typedoc

#696 Updated for #685.
  jp/components/overlay_main.md
Labels: status: localized, status: verified

#695 docs(list): Added chat sample to the list topic #2513
  en/components/list.md
  jp/components/list.md
Labels: status: localized, status: verified

#726 Updated for #701 (#699 and #700).
  jp/components/combo.md
  jp/components/combo_features.md
  jp/components/drop_down.md
Labels: status: localized, status: verified

#725 Providing Typedoc references for the for Grid Column Pinning topic.
  en/components/grid_column_pinning.md
  jp/components/grid_column_pinning.md
Labels: grid, status: pending-localization, typedoc

#697 Add tooltip doc page
  en/components/toc.yml
  en/components/tooltip.md
  jp/components/toc.yml
  jp/components/tooltip.md
Labels: status: localized, status: verified

#724 Providing Typedoc references for the for Grid Virtualiztion topic.
  en/components/grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: grid, typedoc

#723 Providing Typedoc references for the for Grid Paste Excel topic.
  en/components/grid_paste_excel.md
  jp/components/grid_paste_excel.md
Labels: grid, typedoc

#714 Providing Typedoc references for the Grid GroupBy topic.
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: grid, status: in-test, typedoc

#715 Providing Typedoc references for the Chip topic.
  en/components/chip.md
  jp/components/chip.md
Labels: chip, status: verified, typedoc

#718 Providing Typedoc references for the For Of topic.
  en/components/for_of.md
  jp/components/for_of.md
Labels: typedoc

#717 docs(*): Added api links in topics
  en/components/avatar.md
  en/components/badge.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/checkbox.md
  en/components/grid_column_moving.md
  en/components/grid_column_resizing.md
  en/components/grid_conditional_cell_styling.md
  en/components/grid_filtering.md
  en/components/icon.md
  en/components/input_group.md
  en/components/input_group_reactive_forms.md
  en/components/label_input.md
  en/components/mask.md
  en/components/radio_button.md
  en/components/ripple.md
  en/components/switch.md
  en/components/tabbar.md
  en/components/tabs.md
  en/components/time_picker.md
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/checkbox.md
  jp/components/grid_column_moving.md
  jp/components/grid_column_resizing.md
  jp/components/grid_conditional_cell_styling.md
  jp/components/grid_filtering.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/input_group_reactive_forms.md
  jp/components/label_input.md
  jp/components/mask.md
  jp/components/radio_button.md
  jp/components/ripple.md
  jp/components/switch.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/time_picker.md
Labels: status: localized, status: verified, typedoc

#694 Mharrington/annotation layers
  en/components/categorychart_annotation_layers.md
  en/components/financialchart_annotation_layers.md
  en/components/toc.yml
  jp/components/categorychart_annotation_layers.md
  jp/components/financialchart_annotation_layers.md
  jp/components/toc.yml
Labels: status: localized

#733 Removing Icons' Name Property
  en/components/button.md
  en/components/card.md
  en/components/chip.md
  en/components/circular_progress.md
  en/components/combo_cascading.md
  en/components/expansion_panel.md
  en/components/grid_paging.md
  en/components/grid_search.md
  en/components/input_group.md
  en/components/input_group_reactive_forms.md
  en/components/linear_progress.md
  en/components/list.md
  en/components/navbar.md
  en/components/navdrawer.md
  en/components/tabbar.md
  en/components/tabs.md
  en/components/texthighlight.md
  en/components/tooltip.md
  jp/components/button.md
  jp/components/card.md
  jp/components/chip.md
  jp/components/circular_progress.md
  jp/components/combo_cascading.md
  jp/components/expansion_panel.md
  jp/components/grid_paging.md
  jp/components/grid_search.md
  jp/components/input_group.md
  jp/components/input_group_reactive_forms.md
  jp/components/linear_progress.md
  jp/components/list.md
  jp/components/navbar.md
  jp/components/navdrawer.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/texthighlight.md
  jp/components/tooltip.md
Labels: status: verified

#734 Configuring Typedoc and Sassdoc references in topics.
  en/components/grid_editing.md
  en/components/grid_multi_column_headers.md
  en/components/grid_paging.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  jp/components/grid_editing.md
  jp/components/grid_multi_column_headers.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
Labels: enhancement, status: verified, typedoc

#732 docs(icon): Added SVG icons info #2661
  en/components/icon.md
  jp/components/icon.md
Labels: status: localized, status: verified

#728 Added topic for drag and drop.
  en/components/drag_drop.md
  en/components/toc.yml
  jp/components/drag_drop.md
  jp/components/toc.yml
Labels: status: pending-localization, typedoc

#738 feat: adding weather sample to docs.
  en/components/expansion_panel.md
  jp/components/expansion_panel.md
Labels: enhancement, status: localized

#748 Updated IGroupByRecord interface in GroupBy topic.
  en/components/grid_groupby.md
Labels: grid, status: verified

#747 Changed getGroupRow method in group_by topic.
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: grid, status: verified

#750 chore(groupby): Copy editing plus updating with the new keyboard navigation
  en/components/grid_groupby.md
  jp/components/grid_groupby.md
Labels: grid, status: localized

#751 Update chip topic in relation to the chip refactoring. Add more screenshots and gifs.
  en/components/chip.md
  en/images/chip/advanced_customizing.jpg
  en/images/chip/arrow_left_key.gif
  en/images/chip/arrow_right_key.gif
  en/images/chip/default_chip.jpg
  en/images/chip/delete_key.gif
  en/images/chip/density.jpg
  en/images/chip/dragging.gif
  en/images/chip/focused_chip.jpg
  en/images/chip/hover_chip.jpg
  en/images/chip/prefix_suffix.jpg
  en/images/chip/remove_icons.jpg
  en/images/chip/removing_default.gif
  en/images/chip/selecting_custom.gif
  en/images/chip/selecting_default.gif
  en/images/chip/shift_left_key.gif
  en/images/chip/shift_right_key.gif
  en/images/chip/space_key.gif
  en/images/dragging.gif
  jp/components/chip.md
  jp/images/chip/advanced_customizing.jpg
  jp/images/chip/arrow_left_key.gif
  jp/images/chip/arrow_right_key.gif
  jp/images/chip/default_chip.jpg
  jp/images/chip/delete_key.gif
  jp/images/chip/density.jpg
  jp/images/chip/dragging.gif
  jp/images/chip/focused_chip.jpg
  jp/images/chip/hover_chip.jpg
  jp/images/chip/prefix_suffix.jpg
  jp/images/chip/remove_icons.jpg
  jp/images/chip/removing_default.gif
  jp/images/chip/selecting_custom.gif
  jp/images/chip/selecting_default.gif
  jp/images/chip/shift_left_key.gif
  jp/images/chip/shift_right_key.gif
  jp/images/chip/space_key.gif
  jp/images/dragging.gif
Labels: chip, status: pending-localization, status: verified

#756 docs(drop-down): Added notes for onSelection event args. #2031
  en/components/drop_down.md
  jp/components/drop_down.md
Labels: status: pending-localization, status: verified

#757 Adding demo on how to customize the shadowing in the Shadow topic.
  en/components/shadows.md
  jp/components/shadows.md
Labels: status: pending-localization, status: verified, styling

#753 Fixing build warnings in EN and JP versions.
  en/components/grid_filtering.md
  en/components/list.md
  en/components/themes/theming-demo.md
  en/docfx.json
  jp/components/combo.md
  jp/components/grid_filtering.md
  jp/components/grids_and_lists.md
  jp/components/list.md
  jp/components/themes/theming-demo.md
  jp/docfx.json
Labels: status: verified

#761 docs(*): Added topic for display density #2692
  en/components/display_density.md
  en/components/input_group.md
  en/components/toc.yml
  jp/components/display_density.md
  jp/components/input_group.md
  jp/components/toc.yml
  kr/components/display_density.md
  kr/components/toc.yml
Labels: status: pending-localization, status: verified

#763 topics for excel, pie and doughnut charts
  en/components/doughnutchart.md
  en/components/excel_library.md
  en/components/excel_library_using_cells.md
  en/components/excel_library_using_tables.md
  en/components/excel_library_using_workbooks.md
  en/components/excel_library_using_worksheets.md
  en/components/excel_library_working_with_charts.md
  en/components/excel_library_working_with_grids.md
  en/components/excel_library_working_with_sparklines.md
  en/components/piechart.md
  en/components/toc.yml
Labels: status: in-test

#737 Add row editing and transaction topics
  en/components/grid_editing.md
  en/components/grid_row_editing.md
  en/components/grid_transactions.md
  en/components/toc.yml
  jp/components/grid_editing.md
  jp/components/grid_row_editing.md
  jp/components/grid_transactions.md
  jp/components/toc.yml
  kr/components/grid_row_editing.md
  kr/components/grid_transactions.md
  kr/components/toc.yml
Labels: status: pending-localization, status: verified

#769 Updated igniteui-docfx-template to 2.0.1
  package-lock.json
  package.json
Labels: status: verified
