Repository IgniteUI/igniteui-docfx, pull requests merged in 2018-04, with the labels that each got.

#236 Adding "Grid Virtualization and Performance" subtopic.
  en/components/grid.md
  en/components/grid_virtualization.md
  en/components/toc.yml
  jp/components/grid_virtualization.md
  jp/components/toc.yml
Labels: status: verified

#249 Updated grid subtopics
  jp/components/grid.md
  jp/components/grid_column_pinning.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
  jp/components/toc.yml
Labels: status: verified

#253 Missed translating one link
  jp/components/grid_filtering.md
Labels: status: verified

#252 Bug fix from John
  jp/components/icon.md
Labels: status: verified

#250 Input group new topic
  en/components/dialog.md
  en/components/input_group.md
  en/components/label_input.md
  en/components/toc.yml
  jp/components/dialog.md
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/toc.yml
Labels: Topic

#255 update topics for grid with new onCellClick evt
  en/components/grid.md
  jp/components/grid.md
Labels: status: verified

#248 igxFor docs changes for smooth scrolling improvement
  en/components/for_of.md
  jp/components/for_of.md
Labels: enhancement, status: localized

#265 Extracted label and input into separate topic
  en/components/input_group.md
  en/components/label_input.md
  en/components/toc.yml
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/toc.yml
Labels: Topic

#263 Add description for igxGrid's onContextMenu output
  en/components/grid.md
  jp/components/grid.md
Labels: Topic, status: localized

#262 Grid: add subtopic for deferred column resizing.
  en/components/grid.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  en/components/toc.yml
Labels: Topic, status: pending-localization

#267 Updated docs for multiple components related to changes in 5.3.x
  en/components/checkbox.md
  en/components/dialog.md
  en/components/for_of.md
  en/components/list.md
  en/components/mask.md
  en/components/radio_button.md
  en/components/snackbar.md
  en/components/switch.md
Labels: Topic, status: pending-localization

#269 Added new DV topics and category chart images
  jp/components/categorychart.md
  jp/components/categorychart_axis.md
  jp/components/categorychart_configuring.md
  jp/components/financialchart.md
  jp/components/financialchart_axis.md
  jp/components/financialchart_panes.md
  jp/images/category_chart_area.png
  jp/images/category_chart_column.png
  jp/images/category_chart_line.png
  jp/images/category_chart_point.png
  jp/images/category_chart_spline.png
  jp/images/category_chart_splinearea.png
  jp/images/category_chart_steparea.png
  jp/images/category_chart_stepline.png
  jp/images/category_chart_waterfall.png
Labels: Topic, status: localized

#272 Added summary sample to grid-summary topic
  en/components/grid_summaries.md
  jp/components/grid_summaries.md
Labels: status: pending-localization

#264 Deprecate tabbar's selector `igx-tab-bar`
  en/components/tabbar.md
  en/components/toc.yml
Labels: enhancement, status: pending-localization, status: verified

#242 Adding pages for the exporters.
  en/components/exporter_csv.md
  en/components/exporter_excel.md
  en/components/toc.yml
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
  jp/components/toc.yml
Labels: Topic, status: pending-localization, status: verified

#276 Fixes broken build because of a bad toc.yml file formatting.
  en/components/toc.yml
Labels: status: verified

#279 Add samples to the grid giltering/paging topics
  en/components/grid_filtering.md
  en/components/grid_paging.md
Labels: status: verified

#283 fix(docs): Changing demos position and updating Summary description
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_summaries.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_summaries.md
Labels: enhancement, status: pending-localization, status: verified

#284 docs(tabs): Added documentation for tabs #274
  en/components/tabs.md
  en/components/toc.yml
  jp/components/tabs.md
  jp/components/toc.yml
Labels: Topic, status: pending-localization

#288 fix(build): Fixing failing docfx build
  en/components/grid.md
  en/components/grid_selection.md
  en/components/toc.yml
  jp/components/grid_selection.md
  jp/components/toc.yml
Labels: bug, status: verified

#280 Updated sample names and added new content
  en/components/categorychart.md
  en/components/categorychart_axis.md
  en/components/categorychart_configuring.md
  en/components/categorychart_custom_tooltips.md
  en/components/categorychart_performance.md
  en/components/categorychart_performance_high_frequency.md
  en/components/categorychart_performance_high_volume.md
  en/components/financialchart.md
  en/components/financialchart_axis.md
  en/components/financialchart_binding_data.md
  en/components/financialchart_configuring.md
  en/components/financialchart_custom_indicators.md
  en/components/financialchart_custom_tooltips.md
  en/components/financialchart_panes.md
  en/components/financialchart_performance.md
  en/components/toc.yml
Labels: status: pending-localization

#286 New content from 2018/04/17
  jp/components/categorychart.md
  jp/components/categorychart_axis.md
  jp/components/categorychart_configuring.md
  jp/components/categorychart_custom_tooltips.md
  jp/components/categorychart_performance.md
  jp/components/financialchart.md
  jp/components/financialchart_axis.md
  jp/components/financialchart_binding_data.md
  jp/components/financialchart_custom_indicators.md
  jp/components/financialchart_custom_tooltips.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_summaries.md
  jp/components/tabbar.md
  jp/components/toc.yml
Labels: status: verified

#287 tabs doc minor fixes
  en/components/tabs.md
Labels: bug, severity: low, status: verified

#295 fix(SB samples): Assets URL broken after clicking more than once on the SB buttons
  templates/ignite-ui-template/styles/stackblitz-handler.js
Labels: status: verified

#285 Add sample for column resizing
  en/components/grid_column_resizing.md
Labels: Topic, enhancement, status: verified

#297 Add sample for sorting
  en/components/grid_sorting.md
  jp/components/grid_sorting.md
Labels: Topic, status: pending-localization, status: verified

#299 Updates from 2018/04/18
  jp/components/categorychart_performance.md
  jp/components/categorychart_performance_high_frequency.md
  jp/components/categorychart_performance_high_volume.md
  jp/components/financialchart.md
  jp/components/financialchart_axis.md
  jp/components/financialchart_binding_data.md
  jp/components/financialchart_configuring.md
  jp/components/financialchart_custom_tooltips.md
  jp/components/financialchart_panes.md
  jp/components/grid.md
  jp/components/grid_selection.md
  jp/components/grid_summaries.md
  jp/components/radio_button.md
  jp/components/tabs.md
  jp/components/toc.yml
Labels: status: verified

#303 Documented chocolaye's elevated permissions security requirment.
  README.md
Labels: status: verified

#307 improvement(contributing.md): Updating contribution file
  .github/CONTRIBUTING.md
Labels: enhancement, status: verified

#305 Fix selection sample SB button
  en/components/grid_selection.md
Labels: status: verified

#309 fix(doc): Removing onCellSelection event
  en/components/grid.md
Labels: status: verified

#298 IE 11 left menu missing and SB samples not opening
  templates/ignite-ui-template/styles/docfx.js
  web.config
Labels: status: verified

#306 docs(grid): Adding Remote Virtualization sample
  en/components/grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: status: verified

#313 Column resizing demo refactoring
  en/components/grid.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
Labels: Topic, enhancement, status: verified

#311 fix(docs): Change notes position
  en/components/grid_filtering.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
Labels: status: verified

#322 docs(layout manager): Fix sample height
  en/components/layout.md
  jp/components/layout.md
Labels: status: verified

#312 Add browser height limitation description inside Grid Virtualization topic and ForOf topic.
  en/components/for_of.md
  en/components/grid_virtualization.md
  jp/components/for_of.md
  jp/components/grid_virtualization.md
Labels: Topic, enhancement, status: pending-localization

#316 Update tags and descriptions
  en/components/button.md
  en/components/buttonGroup.md
  en/components/exporter_csv.md
  en/components/exporter_excel.md
  en/components/for_of.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  en/components/input_group.md
  en/components/mask.md
  en/components/shadows.md
  en/components/tabs.md
  en/components/themes.md
  en/components/time_picker.md
  en/components/toggle.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
  jp/components/for_of.md
  jp/components/grid_column_pinning.md
  jp/components/grid_column_resizing.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
  jp/components/input_group.md
  jp/components/mask.md
  jp/components/shadows.md
  jp/components/tabs.md
  jp/components/themes.md
  jp/components/time_picker.md
  jp/components/toggle.md
Labels: Topic, enhancement

#324 Remove whitespaces in grid selection sample
  en/components/grid_selection.md
Labels: status: awaiting-test, status: verified

#326 feat(sidenav): add ability to specify a TOC item as "new"
  en/components/toc.yml
  templates/ignite-ui-template/partials/li.tmpl.partial
  templates/ignite-ui-template/styles/css/main.css
  templates/ignite-ui-template/styles/sass/partials/_toc.scss
Labels: status: verified

#325 Fixed grid demos
  en/components/grid.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  en/components/toc.yml
  jp/components/grid.md
  jp/components/grid_column_pinning.md
  jp/components/grid_column_resizing.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
Labels: status: pending-localization, status: verified

#329 Update JP toc.yml
  jp/components/toc.yml
Labels: status: verified

#328 Update toc.yml
  en/components/toc.yml
Labels: status: verified

#315 Virtualization topic width/height info clean-up, remote implementation docs
  en/components/grid_virtualization.md
Labels: Topic, enhancement, status: pending-localization

#345 remove blank space under grid demos
  en/components/grid_selection.md
  en/components/grid_summaries.md
  jp/components/grid_selection.md
  jp/components/grid_summaries.md
Labels: status: verified

#346 Fixed menu to render children when we have a parent with tag new
  en/components/toc.yml
  jp/components/toc.yml
  templates/ignite-ui-template/partials/li.tmpl.partial
Labels: status: verified

#350 Add datepicker `onClose` API description
  en/components/date_picker.md
  jp/components/date_picker.md
Labels: status: verified

#354 docs(igxGrid): adding limitations #347 #348
  en/components/grid_column_pinning.md
  en/components/grid_virtualization.md
Labels: status: pending-localization

#352 Enhance some of the grid samples
  en/components/grid_column_pinning.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  jp/components/grid_column_pinning.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
Labels: Topic, enhancement, status: pending-localization

#327 Fix column resizing demo
  en/components/grid_column_resizing.md
Labels: enhancement, status: pending-localization, status: verified

#361 fix(demos): mobile nav items not displayed correctly
  templates/ignite-ui-template/styles/css/main.css
  templates/ignite-ui-template/styles/docfx.css
  templates/ignite-ui-template/styles/sass/partials/_toc.scss
Labels: enhancement, status: verified

#363 Update mask directive topic
  en/components/mask.md
Labels: Topic, enhancement, status: pending-localization

#364 Fixed console warnings
  en/components/financialchart.md
  en/components/financialchart_binding_to_multiple_data.md
  en/components/financialchart_high_volume_data.md
  en/components/financialchart_panes.md
  en/components/financialchart_performance.md
  en/components/financialchart_real_time_data.md
  en/components/grid.md
  en/components/grid_column_pinning.md
  en/components/grid_column_resizing.md
  en/components/grid_filtering.md
  en/components/grid_paging.md
  en/components/grid_selection.md
  en/components/grid_sorting.md
  en/components/grid_summaries.md
  en/components/grid_virtualization.md
  en/components/navdrawer.md
  jp/components/badge.md
  jp/components/card.md
  jp/components/financialchart.md
  jp/components/financialchart_binding_to_multiple_data.md
  jp/components/financialchart_high_volume_data.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/financialchart_real_time_data.md
  jp/components/grid.md
  jp/components/grid_column_pinning.md
  jp/components/grid_column_resizing.md
  jp/components/grid_filtering.md
  jp/components/grid_paging.md
  jp/components/grid_selection.md
  jp/components/grid_sorting.md
  jp/components/grid_summaries.md
  jp/components/grid_virtualization.md
  jp/components/list.md
  jp/components/navbar.md
  jp/components/navdrawer.md
Labels: status: verified

#365 Add row selection and remote virtualization limitation.
  en/components/grid_selection.md
Labels: status: pending-localization

#367 docs(grid): Adding Known Issue about Mac OS
  en/components/grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: status: pending-localization

#366 Pushing some last minute description enhancements
  en/components/exporter_excel.md
  en/components/grid_column_pinning.md
  en/components/grid_selection.md
  en/components/tabs.md
  en/components/time_picker.md
  en/components/toggle.md
Labels: status: pending-localization

#376 Update grid.md
  jp/components/grid.md
Labels: enhancement

#378 Update grid_virtualization.md
  jp/components/grid_virtualization.md
Labels: enhancement

#382 Update grid_paging.md
  jp/components/grid_paging.md
Labels: enhancement

#383 Update grid_filtering.md
  jp/components/grid_filtering.md
Labels: enhancement

#384 Update grid_sorting.md
  jp/components/grid_sorting.md
Labels: enhancement

#385 Update grid_summaries.md
  jp/components/grid_summaries.md
Labels: enhancement

#387 Update grid_column_resizing.md
  jp/components/grid_column_resizing.md
Labels: enhancement

#388 Update grid_selection.md
  jp/components/grid_selection.md
Labels: enhancement

#389 Update exporter_excel.md
  jp/components/exporter_excel.md
Labels: enhancement

#390 Update list.md
  jp/components/list.md
Labels: enhancement

#391 Translation improvement based on the UI review in context.
  jp/components/categorychart.md
  jp/components/categorychart_configuration_options.md
  jp/components/categorychart_explore_chart_types.md
  jp/components/categorychart_high_volume_data.md
  jp/components/categorychart_real_time_data.md
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
  jp/components/financialchart.md
  jp/components/financialchart_binding_to_multiple_data.md
  jp/components/financialchart_configuration_options.md
  jp/components/financialchart_high_volume_data.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/financialchart_real_time_data.md
  jp/components/input_group.md
  jp/components/mask.md
  jp/components/tabs.md
  jp/components/time_picker.md
Labels: enhancement
