Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-04, with the labels that each got.

#1147 Update datachart_series_types_category.md
  en/components/datachart_series_types_category.md
Labels: bug

#1157 Updating docfx version to 2.0.15
  package-lock.json
  package.json
Labels: status: verified

#1160 Mcs topic update
  en/components/grids_templates/selection.md
  jp/components/grids_templates/selection.md
  kr/components/grids_templates/selection.md
Labels: grid, hierarchical-grid, status: verified, tree grid

#1169 Updated for #1160 and #1162.
  jp/components/grids_templates/selection.md
Labels: status: localized, status: verified

#1167 Adding new label to Selection topic
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: verified

#1171 Ysugiura/0411
  jp/components/buttonGroup.md
  jp/components/datachart_series_types_category.md
  jp/components/grids_templates/filtering.md
Labels: status: localized, status: verified

#1172 Updating to 2.0.16 version of docfx-template
  package-lock.json
  package.json
Labels: status: resolved

#1161 fix(*): Fixed minor issues #
  en/components/date_picker.md
  en/components/toc.yml
  jp/components/date_picker.md
  jp/components/toc.yml
  kr/components/date_picker.md
  kr/components/toc.yml
Labels: status: verified

#1164 docs(date-picker): Added info for drop-down mode re-templating
  en/components/date_picker.md
  jp/components/date_picker.md
  kr/components/date_picker.md
Labels: date picker, status: pending-localization, status: verified

#1173 Remove igxGridModule references
  en/components/grid/grid.md
  jp/components/grid/grid.md
  kr/components/grid/grid.md
Labels: status: resolved

#1175 Fixing wrong formatting
  jp/components/buttonGroup.md
Labels: status: verified

#1183 Update version to 2.0.17
  package-lock.json
  package.json
Labels: build, status: verified

#1193 Updating readme
  .github/CONTRIBUTING.md
Labels: status: verified

#1174 Adding doc for divider component
  en/components/divider.md
  en/components/toc.yml
Labels: status: pending-localization, status: verified

#1195 Add a not related to fixing pinning in grid column moving
  en/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_moving.md
  kr/components/grids_templates/column_moving.md
Labels: grid, hierarchical-grid, status: pending-localization, status: verified, tree grid

#1188 Fixing JP specific broken links reported by Daizen.
  jp/components/date_picker.md
  jp/components/expansion_panel.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/icon.md
  jp/components/mask.md
  jp/components/tabbar.md
  jp/components/toggle.md
Labels: status: localized, status: verified

#1197 refactor(card): update docs after refactoring
  en/components/card.md
Labels: card, status: pending-localization, status: verified

#1200 Update version
  package-lock.json
  package.json
Labels: status: verified

#1170 docs(drop-down): add virtual drop-down topic
  en/components/drop_down_virtual.md
  en/components/toc.yml
  jp/components/drop_down_virtual.md
  jp/components/toc.yml
  kr/components/drop_down_virtual.md
  kr/components/toc.yml
  package-lock.json
Labels: Topic, dropdown, status: pending-localization, status: verified

#1198 Update AutoPositioningStartegy
  kr/components/overlay_position.md
Labels: enhancement, overlay, status: pending-localization, status: verified

#1194 Making the image responsive in the igxHierarchicalGrid Overview topic
  en/components/hierarchicalgrid/hierarchical_grid.md
Labels: hierarchical-grid, status: verified

#1213 Changes from AngularDocFX_JP
  jp/components/bulletgraph.md
  jp/components/categorychart.md
  jp/components/datachart.md
  jp/components/datachart_chart_titles.md
  jp/components/datachart_series_types_scatter_bubble.md
  jp/components/doughnutchart.md
  jp/components/excel_library.md
  jp/components/excel_library_using_cells.md
  jp/components/excel_library_using_tables.md
  jp/components/excel_library_using_workbooks.md
  jp/components/excel_library_using_worksheets.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_grids.md
  jp/components/excel_library_working_with_sparklines.md
  jp/components/financialchart.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/general-getting-started.md
  jp/components/lineargauge.md
  jp/components/map_binding_data_overview.md
  jp/components/map_binding_geographic_csv_files.md
  jp/components/map_binding_geographic_data_models.md
  jp/components/map_binding_geographic_json_files.md
  jp/components/map_binding_geographic_shape_files.md
  jp/components/map_binding_multiple_data_sources.md
  jp/components/map_binding_multiple_shapes_files.md
  jp/components/map_geographic_scatter_area_series.md
  jp/components/map_geographic_scatter_contour_series.md
  jp/components/map_geographic_scatter_density_series.md
  jp/components/map_geographic_scatter_proportional_series.md
  jp/components/map_geographic_scatter_symbol_series.md
  jp/components/map_geographic_series_overview.md
  jp/components/map_geographic_shape_polygon_series.md
  jp/components/map_imagery_from_bing_maps.md
  jp/components/map_imagery_from_open_street_maps.md
  jp/components/map_imagery_overview.md
  jp/components/map_overview.md
  jp/components/map_resources_world_connections.md
  jp/components/map_resources_world_locations.md
  jp/components/map_resources_world_util.md
  jp/components/piechart.md
  jp/components/radialgauge.md
  jp/components/spreadsheet_activation.md
  jp/components/spreadsheet_clipboard.md
  jp/components/spreadsheet_commands.md
  jp/components/spreadsheet_conditonal_formatting.md
  jp/components/spreadsheet_configuring.md
  jp/components/spreadsheet_data_validation.md
  jp/components/spreadsheet_overview.md
  jp/images/general/geo-map.png
Labels: status: localized, status: verified
