Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-01, with the labels that each got.

#919 Updated for #911.
  jp/components/financialchart_performance.md
Labels: status: localized, status: verified

#917 Fixing Grid Editing topic minor section and moving IgxRipple polyfill explanation on higher level in topic
  en/components/grid_editing.md
  en/components/ripple.md
  jp/components/grid_editing.md
  jp/components/ripple.md
Labels: status: localized, status: verified

#922 Updated notifications samples with the new URLs
  en/components/banner.md
  en/components/snackbar.md
  en/components/toast.md
  jp/components/banner.md
  jp/components/snackbar.md
  jp/components/toast.md
  kr/components/banner.md
  kr/components/snackbar.md
  kr/components/toast.md
  package-lock.json
  package.json
Labels: status: verified

#931 correct the url to scheduling samples due to the new scheduling bundle
  en/components/calendar.md
  en/components/date_picker.md
  en/components/time_picker.md
  jp/components/calendar.md
  jp/components/date_picker.md
  jp/components/time_picker.md
  kr/components/calendar.md
  kr/components/date_picker.md
  kr/components/time_picker.md
Labels: status: verified

#927 Interactions bundle
  en/components/dialog.md
  en/components/drag_drop.md
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  en/components/ripple.md
  en/components/slider.md
  en/components/toggle.md
  en/components/tooltip.md
  jp/components/dialog.md
  jp/components/drag_drop.md
  jp/components/overlay_main.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
  jp/components/ripple.md
  jp/components/slider.md
  jp/components/toggle.md
  jp/components/tooltip.md
  kr/components/dialog.md
  kr/components/drag_drop.md
  kr/components/overlay_main.md
  kr/components/overlay_position.md
  kr/components/overlay_scroll.md
  kr/components/ripple.md
  kr/components/slider.md
  kr/components/toggle.md
  kr/components/tooltip.md
Labels: status: verified

#930 Update docfx-template version
  package-lock.json
  package.json
Labels: status: verified

#928 Gauges bundle
  en/components/bulletgraph.md
  en/components/lineargauge.md
  en/components/radialgauge.md
  jp/components/bulletgraph.md
  jp/components/lineargauge.md
  jp/components/radialgauge.md
  kr/components/bulletgraph.md
  kr/components/lineargauge.md
  kr/components/radialgauge.md
Labels: status: verified

#935 correct the url to menus samples due to the new lists bundle
  en/components/combo.md
  en/components/combo_cascading.md
  en/components/combo_features.md
  en/components/combo_remote.md
  en/components/combo_templates.md
  en/components/list.md
  jp/components/combo.md
  jp/components/combo_cascading.md
  jp/components/combo_features.md
  jp/components/combo_remote.md
  jp/components/combo_templates.md
  jp/components/list.md
  kr/components/combo.md
  kr/components/combo_cascading.md
  kr/components/combo_features.md
  kr/components/combo_remote.md
  kr/components/combo_templates.md
  kr/components/list.md
Labels: status: verified

#937 Excel samples URLs update
  en/components/excel_library.md
  en/components/excel_library_using_cells.md
  en/components/excel_library_using_workbooks.md
  en/components/excel_library_using_worksheets.md
  en/components/excel_library_working_with_charts.md
  en/components/excel_library_working_with_grids.md
  en/components/excel_library_working_with_sparklines.md
  jp/components/excel_library.md
  jp/components/excel_library_using_cells.md
  jp/components/excel_library_using_workbooks.md
  jp/components/excel_library_using_worksheets.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_sparklines.md
  kr/components/excel_library.md
  kr/components/excel_library_using_cells.md
  kr/components/excel_library_using_workbooks.md
  kr/components/excel_library_using_worksheets.md
  kr/components/excel_library_working_with_charts.md
  kr/components/excel_library_working_with_grids.md
  kr/components/excel_library_working_with_sparklines.md
Labels: status: verified

#933 correct the url to menus samples due to the new menus bundle
  en/components/navbar.md
  en/components/navdrawer.md
  jp/components/navbar.md
  jp/components/navdrawer.md
  kr/components/navbar.md
  kr/components/navdrawer.md
Labels: status: verified

#934 Themes bundling
  en/components/display_density.md
  en/components/shadows.md
  en/components/themes/examples.md
  jp/components/display_density.md
  jp/components/shadows.md
  jp/components/themes/examples.md
  kr/components/display_density.md
  kr/components/shadows.md
  kr/components/themes/examples.md
Labels: status: verified

#942 correcting layouts samples urls
  en/components/avatar.md
  en/components/card.md
  en/components/carousel.md
  en/components/expansion_panel.md
  en/components/layout.md
  en/components/tabbar.md
  en/components/tabs.md
  jp/components/avatar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/expansion_panel.md
  jp/components/layout.md
  jp/components/tabbar.md
  jp/components/tabs.md
  kr/components/avatar.md
  kr/components/card.md
  kr/components/carousel.md
  kr/components/expansion_panel.md
  kr/components/layout.md
  kr/components/tabbar.md
  kr/components/tabs.md
Labels: status: verified

#945 add ursl for services bundle
  en/components/exporter_csv.md
  en/components/exporter_excel.md
  en/components/localization.md
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
  jp/components/localization.md
  kr/components/exporter_csv.md
  kr/components/exporter_excel.md
  kr/components/localization.md
Labels: status: verified

#926 Add "Getting started with Ignite UI for Angular" topic
  en/components/general/getting_started.md
  en/components/toc.yml
  en/docfx.json
  en/images/general/buildCLIapp.gif
  en/images/general/igniteui-project.PNG
  en/images/general/nodejs.svg
  en/images/general/play.svg
  en/images/general/vs-code.svg
  en/toc.yml
  jp/components/general/getting_started.md
  jp/components/toc.yml
  jp/docfx.json
  jp/images/general/buildCLIapp.gif
  jp/images/general/igniteui-project.PNG
  jp/images/general/nodejs.svg
  jp/images/general/play.svg
  jp/images/general/vs-code.svg
  jp/toc.yml
  kr/components/general/getting_started.md
  kr/components/toc.yml
  kr/docfx.json
  kr/images/general/buildCLIapp.gif
  kr/images/general/igniteui-project.PNG
  kr/images/general/nodejs.svg
  kr/images/general/play.svg
  kr/images/general/vs-code.svg
  kr/toc.yml
Labels: Topic, status: verified

#947 Data entries and display samples URL update
  en/components/badge.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/checkbox.md
  en/components/chip.md
  en/components/circular_progress.md
  en/components/drop_down.md
  en/components/for_of.md
  en/components/icon.md
  en/components/input_group.md
  en/components/input_group_reactive_forms.md
  en/components/label_input.md
  en/components/linear_progress.md
  en/components/mask.md
  en/components/radio_button.md
  en/components/switch.md
  en/components/texthighlight.md
  jp/components/badge.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/checkbox.md
  jp/components/chip.md
  jp/components/circular_progress.md
  jp/components/drop_down.md
  jp/components/for_of.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/input_group_reactive_forms.md
  jp/components/label_input.md
  jp/components/linear_progress.md
  jp/components/mask.md
  jp/components/radio_button.md
  jp/components/switch.md
  jp/components/texthighlight.md
  kr/components/badge.md
  kr/components/button.md
  kr/components/buttonGroup.md
  kr/components/checkbox.md
  kr/components/chip.md
  kr/components/circular_progress.md
  kr/components/drop_down.md
  kr/components/for_of.md
  kr/components/icon.md
  kr/components/input_group.md
  kr/components/input_group_reactive_forms.md
  kr/components/label_input.md
  kr/components/linear_progress.md
  kr/components/mask.md
  kr/components/radio_button.md
  kr/components/switch.md
  kr/components/texthighlight.md
Labels: status: verified

#951 Tpaskalev/cli overview
  en/components/general/cli-overview.md
  en/components/toc.yml
  jp/components/general/cli-overview.md
  jp/components/toc.yml
  kr/components/general/cli-overview.md
  kr/components/toc.yml
Labels: status: pending-localization, status: verified

#918 Documenting the igx-grid data structure availability.
  en/components/grid.md
  jp/components/grid.md
  kr/components/grid.md
Labels: grid, status: pending-localization

#955 localization for JP
  jp/components/general/cli-overview.md
  jp/components/general/getting_started.md
  jp/components/grid.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#940 Creating the "Ignite UI for Angular update guide" topic
  en/components/general/update_guide.md
  en/components/toc.yml
  jp/components/general/update_guide.md
  jp/components/toc.yml
  kr/components/general/update_guide.md
  kr/components/toc.yml
Labels: status: verified

#895 Docs - Overlay - Add ElasticStrategy to Position topic
  en/components/overlay_position.md
  jp/components/overlay_position.md
  kr/components/overlay_position.md
Labels: Topic, overlay, status: in-test, status: localized

#954 Update "New" flags on items
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: verified

#932 Add new section to IgxSnackbar topic
  en/components/snackbar.md
  jp/components/snackbar.md
  kr/components/snackbar.md
Labels: status: pending-localization, status: verified

#957 Fix typo in the update guide
  en/components/general/update_guide.md
  jp/components/general/update_guide.md
  kr/components/general/update_guide.md
Labels: status: verified

#950 Documenting styles configuration for IE11 and autoprefixer need
  en/components/grid.md
Labels: enhancement, status: verified

#959 Fix defaults for elastic positioning strategy
  en/components/overlay_position.md
Labels: overlay, severity: medium, status: verified

#941 Adding link to the repos of all the versions in global json file
  en/global.json
  jp/global.json
  kr/global.json
  package-lock.json
  package.json
Labels: enhancement, status: pending-localization, status: verified

#962 Updated for #941.
  jp/global.json
Labels: status: localized, status: verified

#968 #966 Fixed broken links to typedocs.
  en/components/calendar.md
  en/components/expansion_panel.md
  jp/components/calendar.md
  jp/components/expansion_panel.md
  kr/components/calendar.md
  kr/components/expansion_panel.md
Labels: calendar, expansion-panel, status: verified

#969 JP+KR updates
  jp/components/general/cli-overview.md
  jp/components/general/getting_started.md
  jp/components/general/update_guide.md
  jp/components/grid.md
  jp/components/overlay_position.md
  jp/components/toc.yml
  kr/components/overlay_position.md
Labels: status: localized, status: verified

#971 Adding a space in order to try to fix the table.
  jp/components/overlay_position.md
Labels: status: verified

#978 Updated for JP and KR.
  jp/components/financialchart_tooltip_templates.md
  jp/components/general/cli-overview.md
  jp/components/general/getting_started.md
  jp/components/general/update_guide.md
  kr/components/categorychart_axis_options.md
Labels: enhancement, status: verified

#979 Updated KR toc.
  kr/components/toc.yml
Labels: status: verified

#981 docs(theming): Fixing import paths for styles
  en/components/themes/examples.md
  jp/components/themes/examples.md
  kr/components/themes/examples.md
  kr/components/themes/theming-demo.md
Labels: theming

#977 Provide documentation for indeterminate circular progress
  en/components/circular_progress.md
Labels: Topic, status: verified

#984 docs(avatar): Fixing avatar theme path
  en/components/themes/component-themes.md
  jp/components/themes/component-themes.md
  kr/components/themes/component-themes.md
Labels: avatar, theming

#985 fix(*): Adding overlay themes to some components' API reference.
  en/components/banner.md
  en/components/combo.md
  en/components/date_picker.md
  en/components/dialog.md
  en/components/drop_down.md
  en/components/grid_editing.md
  en/components/overlay_main.md
  en/components/themes/examples.md
  en/components/time_picker.md
  jp/components/banner.md
  jp/components/combo.md
  jp/components/date_picker.md
  jp/components/dialog.md
  jp/components/drop_down.md
  jp/components/grid_editing.md
  jp/components/overlay_main.md
  jp/components/themes/examples.md
  jp/components/time_picker.md
  kr/components/banner.md
  kr/components/combo.md
  kr/components/date_picker.md
  kr/components/dialog.md
  kr/components/drop_down.md
  kr/components/grid_editing.md
  kr/components/overlay_main.md
  kr/components/themes/examples.md
  kr/components/themes/theming-demo.md
  kr/components/time_picker.md
Labels: overlay, theming

#988 restore the initial finjs demo url
  en/components/grid.md
  jp/components/grid.md
  kr/components/grid.md
Labels: status: verified
