Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-07, with the labels that each got.

#1324 Updated for #1307.
  jp/components/grids_templates/column_moving.md
Labels: status: verified

#1323 Adding iframe for grid paging styling section
  en/components/grids_templates/paging.md
  jp/components/grids_templates/paging.md
Labels: status: verified

#1328 SEO improvements
  .github/CONTRIBUTING.md
  en/components/grid/groupby.md
  en/components/grids_templates/column_moving.md
  en/components/grids_templates/column_pinning.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/selection.md
  en/components/grids_templates/summaries.md
  en/components/grids_templates/toolbar.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/treegrid/tree_grid.md
  jp/components/display_density.md
  jp/components/grid/groupby.md
  jp/components/grid/paste_excel.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/lineargauge.md
  jp/components/treegrid/tree_grid.md
  kr/components/grids_templates/batch_editing.md
  kr/components/grids_templates/column_pinning.md
  kr/components/grids_templates/editing.md
  kr/components/grids_templates/filtering.md
  kr/components/grids_templates/summaries.md
  kr/components/lineargauge.md
Labels: status: verified

#1327 Updated for #1315.
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/live_data.md
  jp/components/icon.md
Labels: status: verified

#1333 ported GeoMap changes from xplatform TOC
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: in-progress

#1336 Updated for #1328.
  jp/components/grid/groupby.md
  jp/components/grid/paste_excel.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/live_data.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1308 Add multi column header template docs
  en/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/multi_column_headers.md
Labels: ig-grid, ig-multi-column-headers, status: pending-localization, status: verified

#1349 Localized to JP.
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/live_data.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/sorting.md
Labels: status: localized, status: verified

#1344 Updated for the rest of #1328.
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/treegrid/tree_grid.md
Labels: status: localized, status: verified

#1346 Add Multi-Cell Selection Styling sections
  en/components/grids_templates/selection.md
  jp/components/grids_templates/selection.md
Labels: category-topic, ig-grid, ig-hierarchical-grid, ig-tree grid, status: verified

#1357 Updated JP contents.
  jp/components/display_density.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/live_data.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/summaries.md
  jp/components/roundness.md
  jp/components/slider.md
  jp/components/toc.yml
  jp/components/treegrid/load_on_demand.md
Labels: status: localized, status: verified

#1361 Cherry pick 1357
  jp/components/display_density.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/live_data.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/summaries.md
  jp/components/roundness.md
  jp/components/slider.md
  jp/components/toc.yml
  jp/components/treegrid/load_on_demand.md
Labels: status: localized, status: verified

#1360 Changing code snippets based on the new paginator
  en/components/grids_templates/paging.md
  jp/components/grids_templates/paging.md
Labels: status: verified

#1339 Add column group template docs
  en/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/multi_column_headers.md
Labels: ig-grid, ig-multi-column-headers, status: pending-localization, status: verified

#1369 Valadzhov/0715 minor localization fixes
  jp/components/date_picker.md
  jp/components/display_density.md
  jp/components/spreadsheet_hyperlinks.md
  jp/components/themes/global-theme.md
Labels: status: localized, status: verified

#1368 Add styling section to column hiding topic
  en/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_hiding.md
Labels: status: verified

#1367 Add styling sections to toolbar topic
  en/components/grids_templates/toolbar.md
  jp/components/grids_templates/toolbar.md
Labels: category-sassdoc, status: verified

#1365 Add dropdown, select and combo styling topics
  en/components/combo.md
  en/components/drop_down.md
  en/components/select.md
  en/components/themes/component-themes.md
  jp/components/combo.md
  jp/components/drop_down.md
  jp/components/select.md
  jp/components/themes/component-themes.md
  kr/components/themes/component-themes.md
Labels: category-styling, ig-combo, ig-dropdown, ig-select, status: pending-localization, status: verified

#1373 Clipboard operations topic #1372
  en/components/grids_templates/clipboard_interactions.md
  en/components/grids_templates/sorting.md
  en/components/toc.yml
  jp/components/grids_templates/clipboard_interactions.md
  jp/components/grids_templates/sorting.md
  jp/components/toc.yml
  kr/components/grids_templates/sorting.md
Labels: status: pending-localization, status: verified

#1371 Add styling section to tooltip topic
  en/components/tooltip.md
  jp/components/tooltip.md
Labels: status: verified

#1366 Adding Tabs/BottomNav Routing Docs
  en/components/tabbar.md
  en/components/tabs.md
Labels: ig-bottomNav, ig-tabs, status: verified

#1382 Localized a new topic clipboard interactions.
  jp/components/grids_templates/clipboard_interactions.md
  jp/components/grids_templates/filtering.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1380 Update styles sections - palette and colors for igxDropDown based components.
  en/components/combo.md
  en/components/drop_down.md
  en/components/select.md
  jp/components/combo.md
  jp/components/drop_down.md
  jp/components/select.md
Labels: category-styling, ig-combo, ig-dropdown, ig-select, status: pending-localization, status: verified

#1370 docs(grids): add cell edit template topic
  en/components/grids_templates/editing.md
  jp/components/grids_templates/editing.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified

#1348 Adding the Transaction Service topics
  en/components/grids_templates/batch_editing.md
  en/components/toc.yml
  en/components/transaction-example.md
  en/components/transaction-how-to.md
  en/components/transaction.md
  jp/components/grids_templates/batch_editing.md
  jp/components/transaction copy 2.md
  jp/components/transaction copy.md
  jp/components/transaction-example.md
  jp/components/transaction-how-to.md
  jp/components/transaction.md
Labels: category-topic, ig-transaction, status: pending-localization, status: verified

#1358 docs(input-group): add styling section
  en/components/input_group.md
  jp/components/input_group.md
Labels: category-styling, category-topic, status: pending-localization, status: verified

#1347 Add Row Editing Styling section to grid topics
  en/components/grids_templates/row_editing.md
  jp/components/grids_templates/row_editing.md
Labels: category-styling, category-topic, ig-grid, ig-hierarchical-grid, ig-tree grid, status: verified

#1384 Add banner styling topic section
  en/components/banner.md
  jp/components/banner.md
Labels: category-styling, ig-banner, status: pending-localization, status: verified

#1362 docs(overlay): add overlay styling topic
  en/components/overlay_main.md
  en/components/overlay_styling.md
  en/components/toc.yml
  jp/components/overlay_main.md
  jp/components/overlay_styling.md
  jp/components/toc.yml
Labels: category-topic, ig-overlay, status: pending-localization, status: verified

#1330 WPF to Angular Guide
  en/components/general/wpf_to_angular_guide/angular_events.md
  en/components/general/wpf_to_angular_guide/angular_pipes.md
  en/components/general/wpf_to_angular_guide/create_first_angular_app.md
  en/components/general/wpf_to_angular_guide/create_ui_with_components.md
  en/components/general/wpf_to_angular_guide/layout.md
  en/components/general/wpf_to_angular_guide/one_way_binding.md
  en/components/general/wpf_to_angular_guide/structural_directives.md
  en/components/general/wpf_to_angular_guide/two_way_binding.md
  en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  en/components/toc.yml
  en/images/general/Angular_project_structure.png
  en/images/general/First_angular_app.png
  en/images/general/WPF_project_structure.png
  en/images/general/angular_grid.png
  en/images/general/angular_grid_span.png
  en/images/general/angular_stackpanel.png
  en/images/general/angular_wrappanel.png
  en/images/general/component_code_behind.png
  en/images/general/component_structure.png
  en/images/general/sample_component.png
  en/images/general/wpf_grid.png
  en/images/general/wpf_stackpanel.png
  en/images/general/wpf_wrappanel.png
Labels: category-topic, status: verified

#1385 Adding routing for tabs/bottomNav in JP files
  jp/components/tabbar.md
  jp/components/tabs.md
Labels: ig-bottomNav, ig-tabs, status: pending-localization, status: verified

#1388 Fix broken links in docfx documentation
  en/components/carousel.md
  en/components/circular_progress.md
  en/components/display_density.md
  en/components/drag_drop.md
  en/components/grids_templates/virtualization.md
  en/components/linear_progress.md
  en/components/navdrawer.md
  en/components/slider.md
  jp/components/carousel.md
  jp/components/circular_progress.md
  jp/components/display_density.md
  jp/components/drag_drop.md
  jp/components/grids_templates/virtualization.md
  jp/components/linear_progress.md
  jp/components/navdrawer.md
  jp/components/slider.md
  kr/components/carousel.md
  kr/components/circular_progress.md
  kr/components/display_density.md
  kr/components/drag_drop.md
  kr/components/grids_templates/virtualization.md
  kr/components/linear_progress.md
  kr/components/navdrawer.md
  kr/components/slider.md
Labels: status: verified

#1378 Removing "includes" check in index file for IE compatibility
  en/index.md
  jp/index.md
  kr/index.md
Labels: status: verified

#1389 Add checkbox styling section
  en/components/checkbox.md
  jp/components/checkbox.md
Labels: category-styling, ig-checkbox, status: pending-localization, status: verified

#1394 docs(combo): add combo overlay section
  en/components/combo_features.md
  jp/components/combo_features.md
Labels: ig-combo, ig-overlay, status: verified

#1395 fix(combo): fix link
  en/components/combo_features.md
  jp/components/combo_features.md
Labels: status: verified

#1392 Updated new tags for treegrid, hierarchical grid & ESF. #1391
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: verified

#1381 Adds docs for GroupBy w/ Paging
  en/components/grid/groupby.md
  en/components/grids_templates/paging.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/paging.md
  kr/components/grid/groupby.md
  kr/components/grids_templates/paging.md
Labels: status: verified

#1400 Fix button data-iframe-id
  en/components/grids_templates/selection.md
Labels: status: verified

#1396 Adds docs for igxForOf's new local variables
  en/components/for_of.md
  jp/components/for_of.md
  kr/components/for_of.md
Labels: status: pending-localization, status: verified

#1390 Add styling section to button topic
  en/components/button.md
  jp/components/button.md
Labels: status: verified

#1401 fix(combo): add language identifier
  en/components/combo.md
Labels: ig-combo, status: verified

#1403 Rename transactions topics
  en/components/toc.yml
  en/components/transaction-classes.md
  en/components/transaction-how-to-use.md
  jp/components/toc.yml
  jp/components/transaction copy 2.md
  jp/components/transaction copy.md
  jp/components/transaction-classes.md
  jp/components/transaction-how-to-use.md
Labels: ig-transaction, status: pending-localization, status: verified

#1402 docs(grid): change row editing overlay style code snippets
  en/components/grids_templates/row_editing.md
  jp/components/grids_templates/row_editing.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: verified

#1354 Update cli documentation
  en/components/general/cli-overview.md
  en/components/general/cli/auth-template.md
  en/components/general/cli/components-templates.md
  en/components/general/cli/step-by-step-guide.md
  en/components/toc.yml
  en/images/general/cli-igx-side-auth.png
  en/images/general/igx-side-auth-login-bar.png
  en/images/general/igx-side-auth-login-dialogs.png
  en/images/general/igx-side-auth-login-google.png
  en/images/general/igx-side-auth-login-social.png
  jp/components/general/cli/auth-template.md
  jp/components/general/cli/components-templates.md
  jp/components/general/cli/step-by-step-guide.md
  jp/components/toc.yml
  jp/images/general/cli-igx-side-auth.png
  jp/images/general/igx-side-auth-login-bar.png
  jp/images/general/igx-side-auth-login-dialogs.png
  jp/images/general/igx-side-auth-login-google.png
  jp/images/general/igx-side-auth-login-social.png
Labels: category-topic, status: pending-localization, status: verified

#1404 docs(*): copy editing changes for-of & groupby
  en/components/for_of.md
  en/components/grid/groupby.md
  jp/components/for_of.md
  jp/components/grid/groupby.md
  kr/components/for_of.md
  kr/components/grid/groupby.md
Labels: status: pending-localization

#1405 Add lazyload and "no-theming" classes to samples in the styling sections
  en/components/banner.md
  en/components/button.md
  en/components/checkbox.md
  en/components/combo.md
  en/components/drop_down.md
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/column_moving.md
  en/components/grids_templates/column_resizing.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/multi_column_headers.md
  en/components/grids_templates/multi_row_layout.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/row_drag.md
  en/components/grids_templates/row_editing.md
  en/components/grids_templates/selection.md
  en/components/grids_templates/toolbar.md
  en/components/grids_templates/virtualization.md
  en/components/input_group.md
  en/components/select.md
  jp/components/banner.md
  jp/components/button.md
  jp/components/checkbox.md
  jp/components/combo.md
  jp/components/drop_down.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/toolbar.md
  jp/components/grids_templates/virtualization.md
  jp/components/input_group.md
  jp/components/select.md
  package-lock.json
  package.json
Labels: status: verified

#1383 Add grid sorting styling
  en/components/grids_templates/sorting.md
  jp/components/grids_templates/sorting.md
Labels: status: verified

#1407 Fix iframes src values
  en/components/piechart.md
  en/components/zoomslider_overview.md
Labels: status: verified

#1411 fix(transaction,cli,grids): broken links, grid editing typos
  en/components/general/cli-overview.md
  en/components/grids_templates/batch_editing.md
  en/components/grids_templates/editing.md
  en/components/overlay_styling.md
  en/components/transaction-classes.md
  en/components/transaction.md
  jp/components/grids_templates/editing.md
  jp/components/overlay_styling.md
  jp/components/transaction-classes.md
  jp/components/transaction.md
Labels: ig-grid, ig-hierarchical-grid, ig-transaction, ig-tree grid, status: pending-localization, status: verified

#1414 Update topics to reflect latest samples
  en/components/grids_templates/row_editing.md
  jp/components/grids_templates/row_editing.md
Labels: category-styling, ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified

#1415 Minor fixes
  en/components/date_picker.md
  en/components/expansion_panel.md
  jp/components/date_picker.md
  jp/components/expansion_panel.md
  kr/components/date_picker.md
  kr/components/expansion_panel.md
Labels: ig-date picker, ig-expansion-panel, status: verified

#1412 Add button group styling section
  en/components/buttonGroup.md
  jp/components/buttonGroup.md
Labels: status: verified

#1410 Fix stackblitz demo link in Excel Style Filtering topic
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: verified

#1416 Add checkbox link and update sample height
  en/components/combo.md
  en/components/input_group.md
  en/components/select.md
  jp/components/combo.md
  jp/components/input_group.md
  jp/components/select.md
Labels: category-styling, ig-combo, status: verified

#1423 Fix links in tooltip and button topics
  en/components/button.md
  en/components/tooltip.md
  jp/components/button.md
  jp/components/tooltip.md
Labels: status: verified

#1424 Wpf to Angular edits
  en/components/general/wpf_to_angular_guide/angular_events.md
  en/components/general/wpf_to_angular_guide/angular_pipes.md
  en/components/general/wpf_to_angular_guide/create_first_angular_app.md
  en/components/general/wpf_to_angular_guide/create_ui_with_components.md
  en/components/general/wpf_to_angular_guide/one_way_binding.md
  en/components/general/wpf_to_angular_guide/structural_directives.md
  en/components/general/wpf_to_angular_guide/two_way_binding.md
Labels: status: verified

#1425 Adding a note about updating `paginationTemplate`
  en/components/general/update_guide.md
Labels: category-topic, status: verified

#1430 Add dialog styling documentation
  en/components/dialog.md
  jp/components/dialog.md
Labels: category-styling, category-topic, status: verified
