Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-10, with the labels that each got.

#1559 Update select groups section
  en/components/select.md
Labels: ig-select, status: verified

#1566 Add export grouping as limitation - vNext
  en/components/grids_templates/export_excel.md
  jp/components/grids_templates/export_excel.md
Labels: status: verified

#1560 Update persistence sample height - vNext
  en/components/grid/grid.md
  jp/components/grid/grid.md
Labels: status: verified

#1567 Add export grouping as limitation - master
  en/components/grids_templates/export_excel.md
Labels: status: verified

#1575 Add known limitations section
  en/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/conditional_cell_styling.md
Labels: status: pending-localization, status: verified

#1576 Add known limitations section
  en/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/conditional_cell_styling.md
Labels: status: pending-localization, status: verified

#1561 Update persistence sample height - master
  en/components/grid/grid.md
  jp/components/grid/grid.md
Labels: status: verified

#1570 RAndriova/0925
  jp/components/banner.md
  jp/components/checkbox.md
  jp/components/combo.md
  jp/components/combo_features.md
  jp/components/dialog.md
  jp/components/drop_down.md
  jp/components/drop_down_virtual.md
  jp/components/expansion_panel.md
  jp/components/general/cli-overview.md
  jp/components/general/update_guide.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/advanced_filtering.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/input_group.md
  jp/components/overlay_styling.md
  jp/components/select.md
Labels: status: localized, status: verified

#1586 Update docfx template to 2.1.0
  package-lock.json
  package.json
Labels: status: verified

#1579 Translated Styling reported by Rumi.
  jp/components/badge.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/circular_progress.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/icon.md
  jp/components/linear_progress.md
  jp/components/navbar.md
  jp/components/snackbar.md
  jp/components/toast.md
Labels: status: localized, status: verified

#1563 Add bottomNav style docs - vNext
  en/components/tabbar.md
  jp/components/tabbar.md
Labels: ig-bottomNav, status: verified

#1564 Add bottomNav style docs - master
  en/components/tabbar.md
  jp/components/tabbar.md
Labels: ig-bottomNav, status: verified

#1585 docs(themes): add fluent theme section in the global theme doc
  en/components/themes/global-theme.md
  jp/components/themes/global-theme.md
Labels: ig-theming, status: pending-localization, status: verified

#1587 Add tree grid style docs - vNext
  en/components/treegrid/tree_grid.md
  jp/components/treegrid/tree_grid.md
Labels: ig-tree grid, status: verified

#1588 Add tree grid style docs - master
  en/components/treegrid/tree_grid.md
Labels: ig-tree grid, status: verified

#1594 Remove carrets from igniteui-docfx-template
  package-lock.json
  package.json
Labels: status: verified

#1592 RAndriova/0927
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/carousel.md
  jp/components/checkbox.md
  jp/components/chip.md
  jp/components/circular_progress.md
  jp/components/combo_features.md
  jp/components/date_picker.md
  jp/components/dialog.md
  jp/components/expansion_panel.md
  jp/components/exporter_csv.md
  jp/components/exporter_excel.md
  jp/components/general/cli/auth-template.md
  jp/components/general/wpf_to_angular_guide/angular_pipes.md
  jp/components/grids_templates/advanced_filtering.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/live_data.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/linear_progress.md
  jp/components/list.md
  jp/components/month_picker.md
  jp/components/navbar.md
  jp/components/overlay_main.md
  jp/components/overlay_styling.md
  jp/components/ripple.md
  jp/components/slider.md
  jp/components/snackbar.md
  jp/components/switch.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/themes/examples.md
  jp/components/time_picker.md
  jp/components/toast.md
  jp/components/tooltip.md
Labels: status: localized, status: verified

#1598 Update getting started topic - vNext
  en/components/general/cli/step-by-step-guide.md
  en/components/general/getting_started.md
Labels: status: verified

#1602 Update usage section of each component topic - vNext
  en/components/autocomplete.md
  en/components/avatar.md
  en/components/badge.md
  en/components/banner.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/calendar.md
  en/components/card.md
  en/components/carousel.md
  en/components/checkbox.md
  en/components/circular_progress.md
  en/components/combo.md
  en/components/date_picker.md
  en/components/dialog.md
  en/components/drop_down.md
  en/components/expansion_panel.md
  en/components/for_of.md
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/icon.md
  en/components/input_group.md
  en/components/label_input.md
  en/components/linear_progress.md
  en/components/list.md
  en/components/mask.md
  en/components/month_picker.md
  en/components/navbar.md
  en/components/navdrawer.md
  en/components/overlay_main.md
  en/components/radio_button.md
  en/components/ripple.md
  en/components/select.md
  en/components/slider.md
  en/components/snackbar.md
  en/components/switch.md
  en/components/tabbar.md
  en/components/tabs.md
  en/components/texthighlight.md
  en/components/time_picker.md
  en/components/toast.md
  en/components/toggle.md
  en/components/tooltip.md
  en/components/treegrid/tree_grid.md
Labels: status: verified

#1590 docs(Themes): Add a docs section with snippet for switching from Material to Fluent Design theme
  en/components/themes/global-theme.md
  jp/components/themes/global-theme.md
Labels: ig-theming, status: pending-localization, status: verified

#1599 Add text-highlight directive style docs - vNext
  en/components/texthighlight.md
  jp/components/texthighlight.md
Labels: ig-text-highlight, status: verified

#1584 Update usage section of each component topic - master
  en/components/autocomplete.md
  en/components/avatar.md
  en/components/badge.md
  en/components/banner.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/calendar.md
  en/components/card.md
  en/components/carousel.md
  en/components/checkbox.md
  en/components/circular_progress.md
  en/components/combo.md
  en/components/date_picker.md
  en/components/dialog.md
  en/components/drop_down.md
  en/components/expansion_panel.md
  en/components/for_of.md
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/icon.md
  en/components/input_group.md
  en/components/label_input.md
  en/components/linear_progress.md
  en/components/list.md
  en/components/mask.md
  en/components/month_picker.md
  en/components/navbar.md
  en/components/navdrawer.md
  en/components/overlay_main.md
  en/components/radio_button.md
  en/components/ripple.md
  en/components/select.md
  en/components/slider.md
  en/components/snackbar.md
  en/components/switch.md
  en/components/tabbar.md
  en/components/tabs.md
  en/components/texthighlight.md
  en/components/time_picker.md
  en/components/toast.md
  en/components/toggle.md
  en/components/tooltip.md
  en/components/treegrid/tree_grid.md
Labels: status: verified

#1593 Update getting started topic
  en/components/general/cli/step-by-step-guide.md
  en/components/general/getting_started.md
Labels: status: verified

#1608 Adding grid custom summary header (vnext)
  en/components/grids_templates/summaries.md
Labels: status: verified

#1607 Adding custom summaries header (master)
  en/components/grids_templates/summaries.md
Labels: status: verified

#1611 Angular Universal topic
  en/components/general/framework-and-features/ssr-rendering.md
  en/components/toc.yml
Labels: status: verified

#1600 Add text-highlight directive style docs - master
  en/components/texthighlight.md
Labels: ig-text-highlight, status: verified

#1623 Loc/1028
  jp/components/autocomplete.md
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/checkbox.md
  jp/components/circular_progress.md
  jp/components/combo.md
  jp/components/date_picker.md
  jp/components/dialog.md
  jp/components/drop_down.md
  jp/components/expansion_panel.md
  jp/components/for_of.md
  jp/components/general/getting_started.md
  jp/components/general/update_guide.md
  jp/components/grid/grid.md
  jp/components/grids_templates/row_drag.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/linear_progress.md
  jp/components/list.md
  jp/components/mask.md
  jp/components/month_picker.md
  jp/components/navbar.md
  jp/components/navdrawer.md
  jp/components/overlay_main.md
  jp/components/overlay_position.md
  jp/components/radio_button.md
  jp/components/ripple.md
  jp/components/select.md
  jp/components/slider.md
  jp/components/snackbar.md
  jp/components/switch.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/texthighlight.md
  jp/components/time_picker.md
  jp/components/toast.md
  jp/components/toggle.md
  jp/components/tooltip.md
  jp/components/treegrid/tree_grid.md
Labels: status: localized, status: verified

#1622 Randriova/0926 - Minor formatting changes. Fixing broken links.
  jp/components/autocomplete.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/circular_progress.md
  jp/components/combo.md
  jp/components/drop_down_virtual.md
  jp/components/general/cli/auth-template.md
  jp/components/grids_templates/clipboard_interactions.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/summaries.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/texthighlight.md
  jp/components/themes/schemas.md
  jp/components/time_picker.md
  jp/components/tooltip.md
  jp/components/treegrid/tree_grid.md
Labels: status: localized, status: verified

#1615 Add select-item text description under usage section
  en/components/select.md
Labels: ig-select, status: pending-localization, status: verified

#1616 Add select-item text description under usage section
  en/components/select.md
Labels: ig-select, status: pending-localization, status: verified

#1624 Updated JP for #1590. - master
  jp/components/themes/global-theme.md
Labels: status: localized, status: verified

#1629 Update to 2.3.0
  package-lock.json
  package.json
Labels: status: verified
