Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-12, with the labels that each got.

#1693 Additional fixes for JP to match EN. - vNext
  jp/components/avatar.md
  jp/components/banner.md
  jp/components/button.md
  jp/components/calendar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/date_picker.md
  jp/components/for_of.md
  jp/components/general/cli-overview.md
  jp/components/general/cli/auth-template.md
  jp/components/general/cli/component-templates.md
  jp/components/general/cli/step-by-step-guide.md
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/ssr-rendering.md
  jp/components/general/getting_started.md
  jp/components/general/wpf_to_angular_guide/angular_events.md
  jp/components/general/wpf_to_angular_guide/create_ui_with_components.md
  jp/components/general/wpf_to_angular_guide/one_way_binding.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/row_selection.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/sizing.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/grids_templates/virtualization.md
  jp/components/hierarchicalgrid/load_on_demand.md
  jp/components/list.md
  jp/components/month_picker.md
  jp/components/overlay_main.md
  jp/components/overlay_scroll.md
  jp/components/overlay_styling.md
  jp/components/radio_button.md
  jp/components/roundness.md
  jp/components/shadows.md
  jp/components/slider.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/themes/examples.md
  jp/components/themes/index.md
  jp/components/themes/palette.md
  jp/components/time_picker.md
  jp/components/toc.yml
  jp/components/tooltip.md
  jp/components/treegrid/aggregations.md
  jp/components/treegrid/load_on_demand.md
  jp/components/treegrid/tree_grid.md
Labels: status: localized, status: verified

#1690 Remote data and paging topic updates
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote_data_operations.md
Labels: status: in-test

#1682 New State Persistence topic for the IgxGridState directive
  en/components/grid/grid.md
  en/components/grids_templates/state_persistence.md
  en/components/toc.yml
  jp/components/grid/grid.md
  jp/components/grids_templates/state_persistence.md
  jp/components/state_persistence.md
  jp/components/toc.yml
  kr/components/grid/grid.md
  kr/components/grids_templates/state_persistence.md
  kr/components/toc.yml
Labels: status: localized, status: verified

#1691 Collapsible Column Groups Topic
  en/components/grids_templates/collapsible_column_groups.md
  en/components/toc.yml
  en/images/general/collapsed_indicator.png
  en/images/general/expand_indicator.png
  jp/components/grids_templates/collapsible_column_groups.md
  jp/components/toc.yml
  jp/images/general/collapsed_indicator.png
  jp/images/general/expand_indicator.png
  kr/components/grids_templates/collapsible_column_groups.md
  kr/components/toc.yml
  kr/images/general/collapsed_indicator.png
  kr/images/general/expand_indicator.png
Labels: grid, status: localized, status: verified

#1694 All Data summary topic
  en/components/grids_templates/summaries.md
  jp/components/grids_templates/summaries.md
  kr/components/grids_templates/summaries.md
Labels: grid, status: pending-localization, status: verified

#1697 Remote paging topic - vNext
  en/components/grids_templates/remote_data_operations.md
Labels: status: verified

#1695 Remote paging topic master
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/paging.md
Labels: status: verified

#1698 All Data summary topic -- master
  en/components/grids_templates/summaries.md
  jp/components/grids_templates/summaries.md
  kr/components/grids_templates/summaries.md
Labels: grid, status: pending-localization, status: verified

#1649 Adding master-detail topic.
  README.md
  en/.gitignore
  en/components/grid/master_detail.md
  en/components/toc.yml
  gulpfile.js
Labels: status: in-development, status: localized

#1699 Adding missing links and content to JP to match EN.
  jp/components/banner.md
  jp/components/button.md
  jp/components/date_picker.md
  jp/components/for_of.md
  jp/components/general/wpf_to_angular_guide/two_way_binding.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/grids_templates/cell_selection.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/row_selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/month_picker.md
  jp/components/select.md
  jp/components/time_picker.md
  jp/components/toc.yml
  jp/components/tooltip.md
Labels: status: localized, status: verified

#1700 chore(*): Fixing iframe id to enable stackblkitz button on sample load.
  en/components/grid/master_detail.md
Labels: status: verified

#1704 Migrate to gulp 4 (Vnext)
  .travis.yml
  gulpfile.js
  package-lock.json
  package.json
Labels: status: verified

#1684 Migrate to gulp 4
  .travis.yml
  gulpfile.js
  package-lock.json
  package.json
Labels: status: verified

#1702 SSR topic updates
  en/components/general/framework-and-features/ssr-rendering.md
  jp/components/general/framework-and-features/ssr-rendering.md
Labels: status: verified

#1703 SSR topic updates
  en/components/general/framework-and-features/ssr-rendering.md
  jp/components/general/framework-and-features/ssr-rendering.md
Labels: status: verified

#1705 updating template version to include theming widget
  package-lock.json
  package.json
Labels: status: verified

#1692 add new slider ticks topic
  en/components/slider/slider.md
  en/components/slider/slider_ticks.md
  en/components/toc.yml
  jp/components/slider/slider.md
  jp/components/slider/slider_ticks.md
  jp/components/toc.yml
  kr/components/slider/slider.md
  kr/components/slider/slider_ticks.md
  kr/components/toc.yml
Labels: slider, status: localized, status: verified

#1707 Conditional formatting section
  en/components/general/framework-and-features/data-analysis.md
  en/images/general/color-scale-formatting.png
  en/images/general/contains-formatting.png
  en/images/general/data-bars-formatting.png
  en/images/general/top-10-percent.png
  en/images/general/unique-values-formatting.png
Labels: status: verified

#1712 Text formatting master
  en/components/general/framework-and-features/data-analysis.md
  en/images/general/color-scale-formatting.png
  en/images/general/contains-formatting.png
  en/images/general/data-bars-formatting.png
  en/images/general/top-10-percent.png
  en/images/general/unique-values-formatting.png
Labels: status: verified

#1708 Updated JP Summary topic (#1698).
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/ssr-rendering.md
  jp/components/grids_templates/summaries.md
  jp/images/general/color-scale-formatting.png
  jp/images/general/contains-formatting.png
  jp/images/general/data-bars-formatting.png
  jp/images/general/top-10-percent.png
  jp/images/general/unique-values-formatting.png
Labels: status: localized, status: verified

#1716 Additional updates to JP to match latest EN changes - vNext
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/ssr-rendering.md
  jp/images/general/color-scale-formatting.png
  jp/images/general/contains-formatting.png
  jp/images/general/data-bars-formatting.png
  jp/images/general/top-10-percent.png
  jp/images/general/unique-values-formatting.png
Labels: status: localized, status: verified

#1715 chore(*): updating version to include IE11 fallback and localization …
  package-lock.json
  package.json
Labels: status: verified
