Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-02, with the labels that each got.

#983 Fix snippet in combo binding example
  en/components/combo_features.md
  jp/components/combo_features.md
  kr/components/combo_features.md
Labels: combo, status: verified

#998 Updated DocFX template to 2.0.9
  package-lock.json
  package.json
Labels: status: verified

#989 Fix primaryKey note for row editing
  en/components/grid_row_editing.md
  jp/components/grid_row_editing.md
Labels: grid, status: localized, status: verified

#999 Add file-include-plugin to docfx
  en/components/grid/grid.md
  en/components/grids_templates/general_template.md
  en/components/hierarchicalGrid/hierarchical_grid.md
  en/components/treeGrid/tree_grid.md
  gulpfile.js
  jp/components/grid/grid.md
  jp/components/grids_templates/general_template.md
  jp/components/hierarchicalGrid/hierarchical_grid.md
  jp/components/treeGrid/tree_grid.md
  kr/components/grid/grid.md
  kr/components/grids_templates/general_template.md
  kr/components/hierarchicalGrid/hierarchical_grid.md
  kr/components/treeGrid/tree_grid.md
  package.json
Labels: status: verified

#870 Setting bigger height to calendar samples iframe for prevention from cutting.
  en/components/calendar.md
  jp/components/calendar.md
  kr/components/calendar.md
Labels: calendar, status: verified

#1001 Added lazy loading for iframes
  en/components/button.md
  en/components/input_group.md
  en/components/localization.md
  jp/components/localization.md
  kr/components/localization.md
  package-lock.json
  package.json
Labels: status: verified

#1011 Updated igniteui-docfx-template to 2.0.11
  package-lock.json
  package.json
Labels: status: verified

#1009 Exclude auto-generated topics from watch
  gulpfile.js
Labels: status: verified

#1014 fix wrong API links
  en/components/drop_down.md
  jp/components/drop_down.md
  kr/components/drop_down.md
Labels: api docs, dropdown

#1017 updating toc
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: verified

#1019 Remove invalid links to modules
  en/components/banner.md
  en/components/combo.md
  en/components/combo_cascading.md
  en/components/combo_features.md
  en/components/combo_remote.md
  en/components/combo_templates.md
  en/components/drop_down.md
  jp/components/banner.md
  jp/components/combo.md
  jp/components/combo_cascading.md
  jp/components/combo_features.md
  jp/components/combo_remote.md
  jp/components/combo_templates.md
  jp/components/drop_down.md
  kr/components/banner.md
  kr/components/combo.md
  kr/components/combo_cascading.md
  kr/components/combo_features.md
  kr/components/combo_remote.md
  kr/components/combo_templates.md
  kr/components/drop_down.md
Labels: api docs, status: verified, typedoc

#1018 Update redirecting URLs to true source for SEO boost
  en/global.json
  jp/global.json
  kr/global.json
Labels: status: verified

#956 Combo - Update Combo templating section with proper selectors
  en/components/combo_templates.md
  jp/components/combo_templates.md
  kr/components/combo_templates.md
Labels: combo, status: localized, status: verified

#1033 fix(docs): Removing virtualization known issues #1032
  en/components/grids_templates/virtualization.md
  jp/components/grids_templates/virtualization.md
  kr/components/grids_templates/virtualization.md
Labels: status: pending-localization

#1034 fix(docs): Removing virtualization known issues #1032
  en/components/grids_templates/virtualization.md
  jp/components/grids_templates/virtualization.md
  kr/components/grids_templates/virtualization.md
Labels: status: pending-localization

#980 Remove search from TreeGrid limitations
  en/components/treeGrid/tree_grid.md
  jp/components/treeGrid/tree_grid.md
  kr/components/treeGrid/tree_grid.md
Labels: search, status: verified, tree grid

#1028 Add IgxSelect topic
  en/components/select.md
  en/components/toc.yml
  jp/components/select.md
  jp/components/toc.yml
  kr/components/select.md
  kr/components/toc.yml
Labels: select, status: pending-localization, status: verified

#1012 Update Paging topic
  en/components/grids_templates/paging.md
  jp/components/grids_templates/paging.md
  kr/components/grids_templates/paging.md
Labels: grid, status: verified

#973 docs(drop-down): add drop-drop-item-group explanation and code snippets
  en/components/drop_down.md
  jp/components/drop_down.md
  kr/components/drop_down.md
Labels: dropdown, status: localized, status: verified

#1000 Add autocomplete topic
  en/components/autocomplete.md
  en/components/input_group.md
  en/components/input_group_reactive_forms.md
  en/components/toc.yml
  jp/components/autocomplete.md
  jp/components/input_group.md
  jp/components/input_group_reactive_forms.md
  jp/components/toc.yml
  kr/components/autocomplete.md
  kr/components/input_group.md
  kr/components/input_group_reactive_forms.md
  kr/components/toc.yml
  package-lock.json
Labels: autocomplete, status: pending-localization, status: verified

#1040 Adding lazy loading section
  .github/CONTRIBUTING.md
Labels: status: verified

#1042 chore(*): Updating keywords on grid topic templates
  en/components/grids_templates/batch_editing.md
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/column_moving.md
  en/components/grids_templates/column_pinning.md
  en/components/grids_templates/column_resizing.md
  en/components/grids_templates/conditional_cell_styling.md
  en/components/grids_templates/display_density.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/multi_column_headers.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/row_editing.md
  en/components/grids_templates/search.md
  en/components/grids_templates/selection.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/summaries.md
  en/components/grids_templates/toolbar.md
  en/components/grids_templates/virtualization.md
Labels: status: pending-localization

#1043 Ysugiura/0225
  jp/components/autocomplete.md
  jp/components/select.md
  kr/components/select.md
Labels: status: localized, status: verified

#1045 Ignore only generated files in .gitignore
  en/.gitignore
  gulpfile.js
  jp/.gitignore
  kr/.gitignore
Labels: status: verified

#1035 Add Hierarchical Grid Load on Demand topic.
  en/components/hierarchicalGrid/load_on_demand.md
  en/components/toc.yml
  en/images/hgrid-database.jpg
  jp/components/hierarchicalGrid/load_on_demand.md
  jp/components/toc.yml
  jp/images/hgrid-database.jpg
  kr/components/hierarchicalGrid/load_on_demand.md
  kr/components/toc.yml
  kr/images/hgrid-database.jpg
Labels: hierarchical-grid, status: verified

#1046 added missing `searchable` keyword
  jp/components/grids_templates/search.md
Labels: status: verified

#900 Add timepicker dropdown sample.
  en/components/time_picker.md
  jp/components/time_picker.md
  kr/components/time_picker.md
Labels: status: pending-localization, status: verified, time picker

#1030 Add TreeGrid aggregations topic
  en/.gitignore
  en/components/toc.yml
  en/components/treeGrid/aggregations.md
  gulpfile.js
  jp/.gitignore
  jp/components/toc.yml
  jp/components/treeGrid/aggregations.md
  kr/.gitignore
  kr/components/toc.yml
  kr/components/treeGrid/aggregations.md
Labels: status: pending-localization, status: verified, tree grid

#1048 Ysugiura/0227
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/display_density.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/grids_templates/virtualization.md
  jp/components/time_picker.md
  jp/components/toc.yml
  jp/components/treeGrid/aggregations.md
  kr/components/treeGrid/aggregations.md
Labels: status: localized, status: verified

#1052 Rename treegrid and hierarchicalgrid folders to lower-case
  en/.gitignore
  en/components/exporter_excel.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/hierarchicalgrid/load_on_demand.md
  en/components/toc.yml
  en/components/treegrid/aggregations.md
  en/components/treegrid/tree_grid.md
  gulpfile.js
  jp/.gitignore
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/hierarchicalgrid/load_on_demand.md
  jp/components/toc.yml
  jp/components/treegrid/aggregations.md
  jp/components/treegrid/tree_grid.md
  jp/components/treegrid/treegrid_batch_editing.md
  jp/components/treegrid/treegrid_row_editing.md
  kr/.gitignore
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/hierarchicalgrid/load_on_demand.md
  kr/components/toc.yml
  kr/components/treegrid/aggregations.md
  kr/components/treegrid/tree_grid.md
  kr/components/treegrid/treegrid_batch_editing.md
  kr/components/treegrid/treegrid_row_editing.md
Labels: status: verified

#990 Change docs for elevations
  en/components/shadows.md
  jp/components/shadows.md
  kr/components/shadows.md
Labels: status: localized, theming

#1051 Updating docs after initial topics review.
  en/components/grids_templates/batch_editing.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/row_editing.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/summaries.md
  en/components/grids_templates/virtualization.md
  en/components/hierarchicalgrid/load_on_demand.md
Labels: hierarchical-grid, status: pending-localization

#1066 Update TextHighlight topic after sample changes
  en/components/texthighlight.md
  en/components/toc.yml
  jp/components/texthighlight.md
  jp/components/toc.yml
  kr/components/texthighlight.md
  kr/components/toc.yml
Labels: search, status: pending-localization, status: verified

#1062 #1060 Removed a common update link.
  en/components/grids_templates/editing.md
Labels: grid, hierarchical-grid, status: verified, tree grid

#1061 #1059 Fixed a parameter in a code snippet.
  en/components/grids_templates/editing.md
Labels: status: verified, tree grid
