Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-08, with the labels that each got.

#1431 Add styling section to grid/treegrid/hierarchicalgrid filtering topic
  en/components/grids_templates/filtering.md
  jp/components/grids_templates/filtering.md
Labels: status: verified

#1426 Update step-by-step-guide
  en/components/general/cli-overview.md
  en/components/general/cli/component-templates.md
  en/components/general/cli/step-by-step-guide.md
  en/components/toc.yml
  en/images/general/ig-step-by-step-component-features.png
  en/images/general/ig-step-by-step-new-project-action.png
  en/images/general/ig-step-by-step-new-project-name.png
  en/images/general/ig-step-by-step-new-project-template.png
  en/images/general/ig-step-by-step-new-project-theme.png
  en/images/general/ig-step-by-step-scenario-templates.png
  en/images/general/ig-step-by-step-template-group.png
  jp/components/general/cli/component-templates.md
  jp/components/general/cli/step-by-step-guide.md
  jp/components/toc.yml
  jp/images/general/ig-step-by-step-component-features.png
  jp/images/general/ig-step-by-step-new-project-action.png
  jp/images/general/ig-step-by-step-new-project-name.png
  jp/images/general/ig-step-by-step-new-project-template.png
  jp/images/general/ig-step-by-step-new-project-theme.png
  jp/images/general/ig-step-by-step-scenario-templates.png
  jp/images/general/ig-step-by-step-template-group.png
Labels: category-topic, status: verified

#1427 Add calendar styling documentation
  en/components/calendar.md
  jp/components/calendar.md
Labels: category-styling, ig-calendar, status: verified

#1440 Removing EN content in the JP files which appers on production.
  jp/components/banner.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/card.md
  jp/components/checkbox.md
  jp/components/combo.md
  jp/components/combo_features.md
  jp/components/drop_down.md
  jp/components/expansion_panel.md
  jp/components/financialchart.md
  jp/components/for_of.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/toolbar.md
  jp/components/input_group.md
  jp/components/map_geographic_scatter_proportional_series.md
  jp/components/select.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/toc.yml
  jp/components/tooltip.md
Labels: status: verified

#1445 docs(cards): Adding styling section to cards topic
  en/components/card.md
  jp/components/card.md
Labels: category-sassdoc, ig-card, status: verified

#1446 Adding styling section to ESF topics for all grids
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/filtering.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified

#1450 Update transaction topic according to the new demo
  en/components/transaction-classes.md
  en/components/transaction-how-to-use.md
  en/components/transaction.md
  jp/components/transaction-classes.md
  jp/components/transaction-how-to-use.md
  jp/components/transaction.md
Labels: ig-transaction, status: verified

#1436 Add expansion panel styling section
  en/components/expansion_panel.md
Labels: category-styling, ig-expansion-panel, status: pending-localization, status: verified

#1449 chore(*): Changing D&D puzzle sample with icons sample
  en/components/drag_drop.md
  jp/components/drag_drop.md
  kr/components/drag_drop.md
Labels: 8.1.x, ig-drag & drop, status: verified

#1437 Adds Sample for Selection-based Summaries
  en/components/grids_templates/selection.md
  jp/components/grids_templates/selection.md
  kr/components/grids_templates/selection.md
Labels: 8.1.x, category-StackBlitz, ig-grid, status: pending-localization

#1455 Revmoing the EN strings by commenting them out.
  jp/components/calendar.md
  jp/components/card.md
  jp/components/grid/grid.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/toc.yml
  jp/components/treegrid/tree_grid.md
Labels: i18n-japanese, status: localized

#1459 Hiding Sizing topics.
  jp/components/grid/grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/treegrid/tree_grid.md
Labels: i18n-japanese, status: verified

#1460 Document igxForOf/igxGrid etc. known issue when working with hidden containers like igxTabs
  en/components/combo.md
  en/components/for_of.md
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/treegrid/tree_grid.md
  jp/components/combo.md
  jp/components/for_of.md
  jp/components/grid/grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/treegrid/tree_grid.md
  kr/components/combo.md
  kr/components/for_of.md
  kr/components/grid/grid.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/treegrid/tree_grid.md
Labels: 8.1.x, status: pending-localization, status: verified

#1393 [JP] WPF to Angular Guide
  jp/components/general/wpf_to_angular_guide/angular_events.md
  jp/components/general/wpf_to_angular_guide/angular_pipes.md
  jp/components/general/wpf_to_angular_guide/create_first_angular_app.md
  jp/components/general/wpf_to_angular_guide/create_ui_with_components.md
  jp/components/general/wpf_to_angular_guide/layout.md
  jp/components/general/wpf_to_angular_guide/one_way_binding.md
  jp/components/general/wpf_to_angular_guide/structural_directives.md
  jp/components/general/wpf_to_angular_guide/two_way_binding.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/toc.yml
  jp/images/general/Angular_project_structure.png
  jp/images/general/First_angular_app.png
  jp/images/general/WPF_project_structure.png
  jp/images/general/angular_grid.png
  jp/images/general/angular_grid_span.png
  jp/images/general/angular_stackpanel.png
  jp/images/general/angular_wrappanel.png
  jp/images/general/component_code_behind.png
  jp/images/general/component_structure.png
  jp/images/general/sample_component.png
  jp/images/general/wpf_grid.png
  jp/images/general/wpf_stackpanel.png
  jp/images/general/wpf_wrappanel.png
Labels: status: pending-localization, status: verified

#1454 Fix missing refs
  en/components/dialog.md
  en/components/grids_templates/editing.md
  jp/components/button.md
  jp/components/dialog.md
  jp/components/grids_templates/editing.md
  jp/components/tooltip.md
Labels: status: verified

#1418 docs(paging): Update of the paging topics
  en/components/grids_templates/paging.md
  jp/components/grids_templates/paging.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization

#1464 Updating grid, tree and hgrid descriptions
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/treegrid/tree_grid.md
  jp/components/grid/grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/treegrid/tree_grid.md
Labels: status: verified

#1421 Add How to use required section
  en/components/select.md
Labels: ig-select, status: verified

#1462 fix(docs): Adding default Column Pinning UI via toolbar as main topic…
  en/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_pinning.md
  kr/components/grids_templates/column_pinning.md
Labels: status: verified

#1475 Add declarative item and label.
  en/components/select.md
  jp/components/select.md
Labels: ig-select, status: pending-localization, status: verified

#1474 Add new Fintech Templates
  en/components/general/cli/component-templates.md
  jp/components/general/cli/component-templates.md
Labels: category-cli, ig-grid, ig-tree grid, status: verified

#1441 docs(grid): Update cell templating, add CRUD events
  en/components/grid/grid.md
  en/components/grids_templates/editing.md
  jp/components/grid/grid.md
  jp/components/grids_templates/editing.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified

#1457 Add navbar style docs
  en/components/navbar.md
  jp/components/navbar.md
Labels: ig-navbar, status: verified

#1461 Add snackbar style docs
  en/components/snackbar.md
  jp/components/snackbar.md
Labels: ig-snackbar, status: verified

#1463 Add toast style docs
  en/components/toast.md
  jp/components/toast.md
Labels: ig-toast, status: verified

#1490 Ysugiura/0827
  jp/components/banner.md
  jp/components/grids_templates/editing.md
Labels: status: localized, status: verified

#1469 Adds Column Pinning Styling Topic
  en/components/grids_templates/column_pinning.md
  jp/components/grids_templates/column_pinning.md
  kr/components/grids_templates/column_pinning.md
Labels: category-enhancement, category-styling, status: pending-localization, status: verified

#1467 Adds Group By Styling Topic
  en/components/grid/groupby.md
  jp/components/grid/groupby.md
  kr/components/grid/groupby.md
Labels: category-enhancement, category-styling, status: pending-localization, status: verified

#1476 Ysugiura/0821
  jp/components/for_of.md
  jp/components/grid/grid.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/images/financial_chart_bar.png
  jp/images/financial_chart_candle.png
  jp/images/financial_chart_column.png
  jp/images/financial_chart_line.png
Labels: status: localized, status: verified

#1492 Adding Demos base url variable in global.json
  en/global.json
  jp/global.json
  kr/global.json
Labels: status: verified

#1496 Update docfx-temlate to 2.0.24
  package-lock.json
  package.json
Labels: status: verified

#1456 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
Labels: category-enhancement, status: verified

#1468 Adding new topics.
  jp/components/grids_templates/sizing.md
  jp/components/toc.yml
  jp/components/transaction-classes.md
  jp/components/transaction-how-to-use.md
  jp/components/transaction.md
Labels: status: localized, status: verified

#1486 Ysugiura/0826
  jp/components/combo.md
  jp/components/drop_down.md
  jp/components/input_group.md
  jp/components/overlay_styling.md
  jp/components/select.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1473 Adds MRL Styling Topic
  en/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/multi_row_layout.md
  kr/components/grids_templates/multi_row_layout.md
Labels: category-enhancement, category-styling, status: pending-localization, status: verified

#1477 Adds Hierarchical Grid Styling Topic
  en/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
Labels: category-enhancement, category-styling, status: pending-localization, status: verified

#1482 Updated for #1354.
  jp/components/combo.md
  jp/components/drop_down.md
  jp/components/general/cli-overview.md
  jp/components/general/cli/auth-template.md
  jp/components/general/cli/component-templates.md
  jp/components/general/cli/step-by-step-guide.md
  jp/components/select.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1498 Ysugiura/0829
  jp/components/banner.md
  jp/components/checkbox.md
  jp/components/grids_templates/editing.md
  jp/components/tabbar.md
Labels: status: localized, status: verified

#1502 Adds Topic for Chip Styling
  en/components/chip.md
  en/components/grid/groupby.md
  en/components/grids_templates/column_pinning.md
  en/components/grids_templates/editing.md
  jp/components/chip.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/column_pinning.md
  kr/components/chip.md
  kr/components/grid/groupby.md
  kr/components/grids_templates/column_pinning.md
Labels: category-enhancement, category-styling, status: verified, version: 8.2.x

#1488 Adds Topic for Ripple Styling
  en/components/ripple.md
  jp/components/ripple.md
  kr/components/ripple.md
Labels: category-enhancement, category-styling, status: verified, version: 8.2.x

#1503 Update summaries
  en/components/grids_templates/summaries.md
  jp/components/grids_templates/summaries.md
Labels: status: verified, version: 8.2.x
