Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-09, with the labels that each got.

#1499 Adds Topic for Icon Styling
  en/components/icon.md
  jp/components/icon.md
  kr/components/icon.md
Labels: category-enhancement, category-styling, status: verified, version: 8.2.x

#1504 Updated for #1393.
  jp/components/general/wpf_to_angular_guide/angular_events.md
  jp/components/general/wpf_to_angular_guide/angular_pipes.md
  jp/components/general/wpf_to_angular_guide/create_first_angular_app.md
  jp/components/general/wpf_to_angular_guide/create_ui_with_components.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
Labels: status: localized, status: verified

#1451 Add ESF Load On Demand docs
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified, version: 8.2.x

#1505 Update summary colors - master
  en/components/grids_templates/summaries.md
  jp/components/grids_templates/summaries.md
Labels: status: verified, version: 8.1.x

#1507 Updated for #1393 - 2.
  jp/components/general/wpf_to_angular_guide/layout.md
  jp/components/general/wpf_to_angular_guide/one_way_binding.md
  jp/components/general/wpf_to_angular_guide/structural_directives.md
  jp/components/general/wpf_to_angular_guide/two_way_binding.md
Labels: status: localized, status: verified

#1470 Add update guide related to changes in the IgxDrag/IgxDrop directive in 8.2.x.
  en/components/general/update_guide.md
  jp/components/general/update_guide.md
  kr/components/general/update_guide.md
Labels: ig-drag & drop, status: verified, version: 8.2.x

#1472 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/layout.md
Labels: category-enhancement, status: verified, version: 8.2.x

#1465 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/structural_directives.md
Labels: category-enhancement, status: verified, version: 8.2.x

#1484 Split selection topics
  en/components/grids_templates/cell_selection.md
  en/components/grids_templates/row_selection.md
  en/components/grids_templates/selection.md
  en/components/toc.yml
  jp/components/grids_templates/cell_selection.md
  jp/components/grids_templates/row_selection.md
  jp/components/grids_templates/selection.md
  jp/components/toc.yml
Labels: grid-row-selection, grid-selection, ig-multi-cell-selection, status: verified, version: 8.2.x

#1513 Ysugiura/0903
  jp/components/for_of.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/row_editing.md
Labels: status: localized, status: verified

#1516 Copy edit the new changes regarding the Drag/Drop main topic.
  en/components/drag_drop.md
Labels: category-enhancement, ig-drag & drop

#1510 Adding new functionalities to the Drag and Drop topic
  en/components/drag_drop.md
Labels: category-enhancement, status: verified, version: 8.2.x

#1520 Adding position and animation settings
  en/components/dialog.md
  jp/components/dialog.md
Labels: status: pending-localization, status: verified

#1522 Updating template to 2.0.25 (vnext)
  package-lock.json
  package.json
Labels: status: verified

#1523 Update template to 2.0.25 (master)
  package-lock.json
  package.json
Labels: status: verified

#1528 Fixes styling topics theme switch behavior
  en/components/chip.md
  en/components/grid/groupby.md
  en/components/grids_templates/column_pinning.md
  en/components/grids_templates/multi_row_layout.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/icon.md
  en/components/ripple.md
  jp/components/chip.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/icon.md
  jp/components/ripple.md
  kr/components/chip.md
  kr/components/grid/groupby.md
  kr/components/grids_templates/column_pinning.md
  kr/components/grids_templates/multi_row_layout.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/icon.md
  kr/components/ripple.md
Labels: category-bug, category-styling, status: verified

#1458 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/angular_events.md
  en/components/general/wpf_to_angular_guide/angular_pipes.md
  en/components/general/wpf_to_angular_guide/create_first_angular_app.md
  en/components/general/wpf_to_angular_guide/create_ui_with_components.md
  en/components/general/wpf_to_angular_guide/one_way_binding.md
  en/components/general/wpf_to_angular_guide/two_way_binding.md
  jp/components/general/wpf_to_angular_guide/angular_events.md
  jp/components/general/wpf_to_angular_guide/angular_pipes.md
  jp/components/general/wpf_to_angular_guide/create_first_angular_app.md
  jp/components/general/wpf_to_angular_guide/create_ui_with_components.md
  jp/components/general/wpf_to_angular_guide/one_way_binding.md
  jp/components/general/wpf_to_angular_guide/two_way_binding.md
Labels: category-enhancement, status: in-test, status: pending-localization, version: 8.2.x

#1527 Ysugiura/0909
  jp/components/grid/grid.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/excel_style_filtering.md
Labels: status: localized, status: verified

#1518 Ysugiura/0904
  jp/components/expansion_panel.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/selection.md
  jp/components/select.md
Labels: status: localized, status: verified

#1533 Mark Drag and Drop topic as new
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: ig-drag & drop, status: verified

#1512 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/structural_directives.md
Labels: category-enhancement, status: verified, version: 8.2.x

#1511 docs(general): SEO optimizations for WPFtoAngular #1447
  en/components/general/wpf_to_angular_guide/layout.md
Labels: category-enhancement, status: verified, version: 8.2.x

#1519 feat(grid): add row selector templating section
  en/components/grids_templates/row_selection.md
Labels: grid-row-selection, status: verified, version: 8.2.x

#1546 Update text based on new Chart representation
  en/components/grids_templates/live_data.md
  jp/components/grids_templates/live_data.md
Labels: status: pending-localization, status: verified

#1545 Update text based on new Chart representation
  en/components/grids_templates/live_data.md
  jp/components/grids_templates/live_data.md
Labels: status: pending-localization, status: verified

#1542 docs(horizontal card sample): Update the sample doc to correspond the new styling of the sample
  en/components/card.md
  jp/components/card.md
Labels: ig-card, status: pending-localization, status: verified, version: 8.1.x

#1509 docs(combo): add combo valueKey binding documentation
  en/components/combo.md
  en/components/combo_features.md
  en/components/combo_remote.md
  en/components/general/update_guide.md
Labels: ig-combo, status: pending-localization, status: verified

#1532 Ysugiura/0911
  jp/components/grids_templates/multi_row_layout.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
Labels: status: localized, status: verified

#1547 Ysugiura/0917
  jp/components/general/wpf_to_angular_guide/layout.md
  jp/components/general/wpf_to_angular_guide/structural_directives.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/grids_templates/live_data.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1549 Add Advanced Filtering topic
  en/components/grids_templates/advanced_filtering.md
  en/components/toc.yml
  jp/components/grids_templates/advanced_filtering.md
  jp/components/toc.yml
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: pending-localization, status: verified, version: 8.2.x

#1550 Updated for #1509.
  jp/components/combo.md
  jp/components/combo_features.md
  jp/components/combo_remote.md
  jp/components/general/update_guide.md
Labels: status: localized, status: verified

#1515 Updating Grid Row Drag topics + Update guide
  en/components/general/update_guide.md
  en/components/grids_templates/row_drag.md
Labels: ig-row-drag

#1538 Refactor position strategies section
  en/components/overlay_position.md
Labels: category-enhancement, ig-overlay, status: pending-localization, status: verified, version: 8.2.x

#1525 add calendar and datepicker multiview sections
  en/components/calendar.md
  en/components/date_picker.md
  jp/components/calendar.md
  jp/components/date_picker.md
  kr/components/calendar.md
  kr/components/date_picker.md
Labels: status: verified, version: 8.2.x

#1552 Add tabs style docs
  en/components/tabs.md
  jp/components/tabs.md
Labels: ig-tabs, status: pending-localization, status: verified

#1554 Fix minor issues in the new overlay position docs
  en/components/overlay_position.md
Labels: category-topic, ig-overlay, severity: medium, status: awaiting-test, version: 8.2.x

#1553 Ysugiura/0924
  jp/components/overlay_position.md
Labels: status: localized, status: verified

#1551 Ysugiura/0919
  jp/components/card.md
  jp/components/grids_templates/advanced_filtering.md
  jp/components/grids_templates/live_data.md
  jp/components/grids_templates/row_selection.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1506 Added badge styling topic
  en/components/badge.md
  jp/components/badge.md
Labels: category-styling, category-topic, status: verified

#1534 Ysugiura/0912
  jp/components/chip.md
  jp/components/dialog.md
  jp/components/general/wpf_to_angular_guide/angular_events.md
  jp/components/general/wpf_to_angular_guide/angular_pipes.md
  jp/components/general/wpf_to_angular_guide/create_first_angular_app.md
  jp/components/general/wpf_to_angular_guide/create_ui_with_components.md
  jp/components/general/wpf_to_angular_guide/one_way_binding.md
  jp/components/general/wpf_to_angular_guide/two_way_binding.md
  jp/components/ripple.md
Labels: status: localized, status: verified

#1539 Add circular progress bar styling section
  en/components/circular_progress.md
  jp/components/circular_progress.md
Labels: category-styling, status: verified

#1540 Add linear progress bar styling section
  en/components/linear_progress.md
  jp/components/linear_progress.md
Labels: category-styling, status: verified

#1555 Fix Excel Style filtering template directive names
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/excel_style_filtering.md
Labels: ig-grid, ig-hierarchical-grid, ig-tree grid, status: verified, version: 8.2.x
