Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-03, with the labels that each got.

#1071 Address igxNavDrawer typos
  en/components/navdrawer.md
  jp/components/navdrawer.md
  kr/components/navdrawer.md
Labels: api docs, severity: low, status: verified

#1069 Fixes on autocomplete topic
  en/components/autocomplete.md
  en/components/toc.yml
  jp/components/autocomplete.md
  jp/components/toc.yml
  kr/components/autocomplete.md
  kr/components/toc.yml
Labels: autocomplete, status: pending-localization, status: verified

#1077 Fixing wrong links to the API for the Autocomplete topic
  en/components/autocomplete.md
  jp/components/autocomplete.md
  kr/components/autocomplete.md
Labels: Topic, autocomplete, status: verified

#1047 Add attach method to overlay docs
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  jp/components/overlay_main.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
Labels: overlay, status: localized, status: verified

#1054 Adding Ignite UI for React to the explanation of the ig new command
  en/components/general/cli-overview.md
  en/components/general/update_guide.md
Labels: status: pending-localization

#1072 Remove closeOnOutsideClick from samples
  en/components/navdrawer.md
  en/components/toggle.md
Labels: status: pending-localization, status: verified, toggle

#1065 docs(*): remove broken links from banner and expansion_panel
  en/components/banner.md
  en/components/expansion_panel.md
  jp/components/banner.md
  jp/components/expansion_panel.md
  kr/components/banner.md
  kr/components/expansion_panel.md
Labels: Topic, banner, expansion-panel, status: verified

#986 Adding roundness documentation
  en/components/roundness.md
  en/components/toc.yml
  jp/components/roundness.md
  jp/components/toc.yml
  kr/components/roundness.md
  kr/components/toc.yml
Labels: status: awaiting-test, status: localized

#1068 Add topic for excel style filtering
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/filtering.md
  en/components/toc.yml
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/toc.yml
  kr/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/filtering.md
  kr/components/toc.yml
Labels: status: pending-localization, status: verified

#1081 Removing the link to selectionAPI in "Grid Row Selection" topic
  en/components/grids_templates/selection.md
  jp/components/grids_templates/selection.md
  kr/components/grids_templates/selection.md
Labels: Topic, grid, status: verified

#1088 chore(*): Fixing incorrect merge
  jp/components/toc.yml
Labels: status: pending-localization, status: verified

#1073 docs(month-picker): Topic for month picker #3947
  en/components/date_picker.md
  en/components/month_picker.md
  en/components/toc.yml
  jp/components/month_picker.md
  jp/components/toc.yml
  kr/components/month_picker.md
  kr/components/toc.yml
Labels: Topic, status: pending-localization, status: verified

#1084 Fixing code snippet indentations
  en/components/grids_templates/paging.md
Labels: hierarchical-grid, status: verified

#1085 docs(dropdown): update code snippets to match updated samples
  en/components/drop_down.md
  jp/components/drop_down.md
  kr/components/drop_down.md
Labels: Topic, dropdown, status: verified

#1087 Fix overlay topics issues
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
  kr/components/overlay_position.md
  kr/components/overlay_scroll.md
Labels: overlay, status: pending-localization, status: verified

#1013 refactor(button): add documentation for the outlined button style
  en/components/button.md
  jp/components/button.md
  kr/components/button.md
  package-lock.json
Labels: button, status: localized

#1078 fix(pickers): Fixed mode references #4143
  en/components/date_picker.md
  en/components/time_picker.md
  jp/components/time_picker.md
  kr/components/time_picker.md
Labels: status: verified, time picker

#1091 Increase ESF sample height
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/excel_style_filtering.md
Labels: Topic, status: verified

#1058 docs(): Removed missing links in API #1016
  en/components/input_group.md
  en/components/label_input.md
  en/components/mask.md
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/mask.md
  kr/components/input_group.md
  kr/components/label_input.md
  kr/components/mask.md
Labels: status: verified

#1057 Localized for #1049.
  jp/components/date_picker.md
Labels: status: localized, status: verified

#1090 Localized for #1021 - 5, #1054, #1068
  jp/components/general/cli-overview.md
  jp/components/general/update_guide.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/toc.yml
  jp/components/treegrid/aggregations.md
Labels: status: localized, status: verified

#1095 Removing the link to `IgxHierarchicalTransactionServiceFactory`
  en/components/grids_templates/batch_editing.md
Labels: status: pending-localization, status: verified

#1093 Vkacheshmarova/fixing issue 1092
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/column_moving.md
  en/components/grids_templates/display_density.md
  en/components/grids_templates/editing.md
Labels: status: verified

#1075 Updated for PR#1021-3
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/virtualization.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/themes/examples.md
  jp/components/treegrid/tree_grid.md
Labels: status: completed

#1070 Ysugiura/0301
  jp/components/exporter_excel.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grid/paste_excel.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/texthighlight.md
Labels: status: completed, status: localized

#1101 Styling changes to the Autocomplete and Select topics
  en/components/autocomplete.md
  en/components/select.md
  jp/components/autocomplete.md
  jp/components/select.md
  kr/components/autocomplete.md
  kr/components/select.md
Labels: status: pending-localization, status: verified

#1104 Add igxLabel directive to snippets.
  en/components/select.md
  jp/components/select.md
  kr/components/select.md
Labels: select, status: verified

#960 Adding schemas documentation and example
  en/components/themes/examples.md
Labels: grid, status: verified, styling, theming

#1106 Small changes to the API References section
  en/components/overlay_position.md
  en/components/overlay_scroll.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
  kr/components/overlay_position.md
  kr/components/overlay_scroll.md
Labels: status: pending-localization, status: verified

#1107 Update code snippets according to the sample
  en/components/input_group.md
  en/components/input_group_reactive_forms.md
  jp/components/input_group.md
  jp/components/input_group_reactive_forms.md
  kr/components/input_group.md
  kr/components/input_group_reactive_forms.md
Labels: select, status: verified

#1096 Move ESF list item to be sibling of filtering item
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: Topic, status: pending-localization, status: verified

#1099 Ysugiura/0308
  jp/components/autocomplete.md
  jp/components/date_picker.md
  jp/components/month_picker.md
  jp/components/navdrawer.md
  jp/components/overlay_position.md
  jp/components/toggle.md
Labels: status: localized, status: verified

#1083 localized for #1021 - 4.
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/display_density.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/toolbar.md
Labels: status: localized, status: verified

#1074 Localized for #1021-2
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/search.md
  jp/components/hierarchicalgrid/load_on_demand.md
Labels: status: localized, status: verified

#1111 Button samples loading fix
  en/components/button.md
  jp/components/button.md
  kr/components/button.md
Labels: button, status: verified

#1112 Remove controls module links
  en/components/card.md
  en/components/grids_templates/column_hiding.md
  en/components/list.md
  en/components/navbar.md
  en/components/snackbar.md
  en/components/texthighlight.md
  en/components/toast.md
  en/components/tooltip.md
  jp/components/card.md
  jp/components/grids_templates/column_hiding.md
  jp/components/list.md
  jp/components/navbar.md
  jp/components/snackbar.md
  jp/components/texthighlight.md
  jp/components/toast.md
  jp/components/tooltip.md
  kr/components/card.md
  kr/components/grids_templates/column_hiding.md
  kr/components/list.md
  kr/components/navbar.md
  kr/components/snackbar.md
  kr/components/toast.md
  kr/components/tooltip.md
  kr/components/treegrid/tree_grid.md
Labels: status: verified

#1117 fix(*): Fixed invalid api links to modules #1115
  en/components/avatar.md
  en/components/badge.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/calendar.md
  en/components/checkbox.md
  en/components/date_picker.md
  en/components/icon.md
  en/components/label_input.md
  en/components/mask.md
  en/components/month_picker.md
  en/components/radio_button.md
  en/components/ripple.md
  en/components/switch.md
  en/components/tabbar.md
  en/components/tabs.md
  en/components/time_picker.md
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/calendar.md
  jp/components/checkbox.md
  jp/components/date_picker.md
  jp/components/icon.md
  jp/components/label_input.md
  jp/components/mask.md
  jp/components/month_picker.md
  jp/components/radio_button.md
  jp/components/ripple.md
  jp/components/switch.md
  jp/components/tabbar.md
  jp/components/tabs.md
  jp/components/time_picker.md
  kr/components/avatar.md
  kr/components/badge.md
  kr/components/button.md
  kr/components/buttonGroup.md
  kr/components/calendar.md
  kr/components/checkbox.md
  kr/components/date_picker.md
  kr/components/icon.md
  kr/components/label_input.md
  kr/components/mask.md
  kr/components/month_picker.md
  kr/components/radio_button.md
  kr/components/ripple.md
  kr/components/switch.md
  kr/components/tabbar.md
  kr/components/tabs.md
  kr/components/time_picker.md
Labels: status: verified

#1124 docs(*): update mention of other components in combo and expansion panel
  en/components/combo_features.md
  en/components/expansion_panel.md
  jp/components/combo_features.md
  jp/components/expansion_panel.md
  kr/components/combo_features.md
  kr/components/expansion_panel.md
Labels: api docs, combo, expansion-panel, status: pending-localization, status: verified

#1118 Clean up IgxSelect topic
  en/components/select.md
  jp/components/select.md
  kr/components/select.md
Labels: select, status: pending-localization, status: verified

#1098 docs(calendar): Added sample for calendar views #3855
  en/components/calendar.md
  jp/components/calendar.md
  kr/components/calendar.md
Labels: calendar, status: verified

#1108 Ysugiura/0311
  jp/components/autocomplete.md
  jp/components/grids_templates/batch_editing.md
  jp/components/overlay_position.md
  jp/components/overlay_scroll.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1114 Overlay and Toggle docs fixes
  en/components/overlay_main.md
  en/components/toggle.md
  jp/components/overlay_main.md
  jp/components/toggle.md
  kr/components/overlay_main.md
  kr/components/toggle.md
Labels: overlay, severity: medium, status: pending-localization, status: verified, toggle

#1038 Add notes about close on outside click + toggle
  en/components/toggle.md
Labels: status: verified, toggle

#1100 Changing the styling of links in the API links section
  en/components/general/getting_started.md
  en/components/grids_templates/batch_editing.md
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/export_excel.md
  en/components/grids_templates/search.md
  en/components/treegrid/tree_grid.md
  jp/components/general/getting_started.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/search.md
  jp/components/treegrid/tree_grid.md
  kr/components/general/getting_started.md
  kr/components/grids_templates/batch_editing.md
  kr/components/grids_templates/column_hiding.md
  kr/components/grids_templates/export_excel.md
  kr/components/grids_templates/search.md
  kr/components/treegrid/tree_grid.md
Labels: status: verified

#1102 Styling changes for the Tooltip topic
  en/components/tooltip.md
  jp/components/tooltip.md
  kr/components/tooltip.md
Labels: status: verified

#1103 refactor(palette): add info about surface color
  en/components/themes/palette.md
Labels: status: pending-localization, status: verified, theming

#1127 Replace drop down with select in cascading scenario topic
  en/components/combo_cascading.md
  jp/components/combo_cascading.md
  kr/components/combo_cascading.md
Labels: combo, select, status: pending-localization, status: verified

#1133 Fix links for stackblitz, shadow and roundness samples
  en/components/roundness.md
  en/components/shadows.md
Labels: StackBlitz, status: verified

#1125 Add lazyload in Pie chart Doughnut chart and List topics for all versions
  en/components/doughnutchart.md
  en/components/list.md
  en/components/piechart.md
  jp/components/doughnutchart.md
  jp/components/list.md
  jp/components/piechart.md
  kr/components/doughnutchart.md
  kr/components/list.md
  kr/components/piechart.md
Labels: status: verified

#1123 Add lazyload excel_library topics for all versions
  en/components/excel_library.md
  en/components/excel_library_using_cells.md
  en/components/excel_library_using_tables.md
  en/components/excel_library_using_workbooks.md
  en/components/excel_library_using_worksheets.md
  en/components/excel_library_working_with_charts.md
  en/components/excel_library_working_with_grids.md
  en/components/excel_library_working_with_sparklines.md
  jp/components/excel_library.md
  jp/components/excel_library_using_cells.md
  jp/components/excel_library_using_tables.md
  jp/components/excel_library_using_workbooks.md
  jp/components/excel_library_using_worksheets.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_grids.md
  jp/components/excel_library_working_with_sparklines.md
  kr/components/excel_library.md
  kr/components/excel_library_using_cells.md
  kr/components/excel_library_using_tables.md
  kr/components/excel_library_using_workbooks.md
  kr/components/excel_library_using_worksheets.md
  kr/components/excel_library_working_with_charts.md
  kr/components/excel_library_working_with_grids.md
  kr/components/excel_library_working_with_sparklines.md
Labels: status: verified

#1122 Add lazyload for financialchart samples in all versions
  en/components/financialchart.md
  en/components/financialchart_annotation_layers.md
  en/components/financialchart_binding_to_multiple_data.md
  en/components/financialchart_configuration_options.md
  en/components/financialchart_custom_indicators.md
  en/components/financialchart_explore_chart_types.md
  en/components/financialchart_high_volume_data.md
  en/components/financialchart_panes.md
  en/components/financialchart_performance.md
  en/components/financialchart_real_time_data.md
  en/components/financialchart_tooltip_templates.md
  en/components/financialchart_tooltip_types.md
  jp/components/financialchart.md
  jp/components/financialchart_annotation_layers.md
  jp/components/financialchart_binding_to_multiple_data.md
  jp/components/financialchart_configuration_options.md
  jp/components/financialchart_custom_indicators.md
  jp/components/financialchart_custom_tooltips.md
  jp/components/financialchart_explore_chart_types.md
  jp/components/financialchart_high_volume_data.md
  jp/components/financialchart_panes.md
  jp/components/financialchart_performance.md
  jp/components/financialchart_real_time_data.md
  jp/components/financialchart_tooltip_templates.md
  jp/components/financialchart_tooltip_types.md
  kr/components/financialchart.md
  kr/components/financialchart_annotation_layers.md
  kr/components/financialchart_binding_to_multiple_data.md
  kr/components/financialchart_configuration_options.md
  kr/components/financialchart_custom_indicators.md
  kr/components/financialchart_explore_chart_types.md
  kr/components/financialchart_high_volume_data.md
  kr/components/financialchart_panes.md
  kr/components/financialchart_performance.md
  kr/components/financialchart_real_time_data.md
  kr/components/financialchart_tooltip_templates.md
  kr/components/financialchart_tooltip_types.md
Labels: status: verified

#1120 Add lazyload for Datachart samples En version
  en/components/datachart.md
  en/components/datachart_axis.md
  en/components/datachart_axis_locations.md
  en/components/datachart_axis_scales.md
  en/components/datachart_axis_settings.md
  en/components/datachart_axis_sharing.md
  en/components/datachart_axis_types.md
  en/components/datachart_chart_legends.md
  en/components/datachart_chart_navigation.md
  en/components/datachart_chart_performance.md
  en/components/datachart_chart_synchronization.md
  en/components/datachart_chart_titles.md
  en/components/datachart_data_triangulation.md
  en/components/datachart_series_animations.md
  en/components/datachart_series_annotations.md
  en/components/datachart_series_errorbars.md
  en/components/datachart_series_highlighting.md
  en/components/datachart_series_markers.md
  en/components/datachart_series_requirements.md
  en/components/datachart_series_tooltips.md
  en/components/datachart_series_trendlines.md
  en/components/datachart_series_types_category.md
  en/components/datachart_series_types_financial.md
  en/components/datachart_series_types_polar.md
  en/components/datachart_series_types_radial.md
  en/components/datachart_series_types_range.md
  en/components/datachart_series_types_scatter_area.md
  en/components/datachart_series_types_scatter_bubble.md
  en/components/datachart_series_types_scatter_contour.md
  en/components/datachart_series_types_scatter_hd.md
  en/components/datachart_series_types_scatter_marker.md
  en/components/datachart_series_types_shape.md
  en/components/datachart_series_types_stacked.md
  en/components/datachart_series_value_overlay.md
Labels: status: verified

#1131 Add lazyload in Layouts topics for all versions
  en/components/avatar.md
  en/components/card.md
  en/components/carousel.md
  en/components/expansion_panel.md
  en/components/tabbar.md
  en/components/tabs.md
  jp/components/avatar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/expansion_panel.md
  jp/components/tabbar.md
  jp/components/tabs.md
  kr/components/avatar.md
  kr/components/card.md
  kr/components/carousel.md
  kr/components/expansion_panel.md
  kr/components/tabbar.md
  kr/components/tabs.md
Labels: status: verified

#1132 Add lazyload in Scheduling and Services topics for all versions
  en/components/calendar.md
  en/components/date_picker.md
  en/components/exporter_csv.md
  en/components/month_picker.md
  en/components/time_picker.md
  jp/components/calendar.md
  jp/components/date_picker.md
  jp/components/exporter_csv.md
  jp/components/month_picker.md
  jp/components/time_picker.md
  kr/components/calendar.md
  kr/components/date_picker.md
  kr/components/exporter_csv.md
  kr/components/month_picker.md
  kr/components/time_picker.md
Labels: status: verified

#1126 Add lazyload in Gauges topics for all versions
  en/components/bulletgraph.md
  en/components/lineargauge.md
  en/components/radialgauge.md
  jp/components/bulletgraph.md
  jp/components/lineargauge.md
  jp/components/radialgauge.md
  kr/components/bulletgraph.md
  kr/components/lineargauge.md
  kr/components/radialgauge.md
Labels: status: verified

#1129 Add lazyload in Interaction topics for all versions
  en/components/dialog.md
  en/components/overlay_main.md
  en/components/ripple.md
  en/components/slider.md
  en/components/toggle.md
  en/components/tooltip.md
  jp/components/dialog.md
  jp/components/overlay_main.md
  jp/components/ripple.md
  jp/components/slider.md
  jp/components/toggle.md
  jp/components/tooltip.md
  kr/components/dialog.md
  kr/components/overlay_main.md
  kr/components/ripple.md
  kr/components/slider.md
  kr/components/toggle.md
  kr/components/tooltip.md
Labels: status: verified

#1130 Add lazyload in Menus and Notification topics for all versions
  en/components/banner.md
  en/components/navbar.md
  en/components/navdrawer.md
  en/components/snackbar.md
  en/components/toast.md
  jp/components/banner.md
  jp/components/navbar.md
  jp/components/navdrawer.md
  jp/components/snackbar.md
  jp/components/toast.md
  kr/components/banner.md
  kr/components/navbar.md
  kr/components/navdrawer.md
  kr/components/snackbar.md
  kr/components/toast.md
Labels: status: verified

#1134 Add keyboard navigation to Tree Grid overview topic
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/treegrid/tree_grid.md
  jp/components/grid/grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/treegrid/tree_grid.md
  kr/components/grid/grid.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/treegrid/tree_grid.md
Labels: status: pending-localization, status: verified, tree grid

#1113 Adding lazyloading for Grid Templates
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/summaries.md
  en/components/grids_templates/toolbar.md
  en/components/grids_templates/virtualization.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/grids_templates/virtualization.md
  kr/components/grids_templates/column_hiding.md
  kr/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/filtering.md
  kr/components/grids_templates/paging.md
  kr/components/grids_templates/summaries.md
  kr/components/grids_templates/toolbar.md
  kr/components/grids_templates/virtualization.md
Labels: status: verified

#1116 Adding lazyload for IgxGrid and TreeGrid topics all versions
  en/components/grid/grid.md
  en/components/themes/examples.md
  en/components/treegrid/tree_grid.md
  jp/components/grid/grid.md
  jp/components/themes/examples.md
  jp/components/treegrid/tree_grid.md
  kr/components/grid/grid.md
  kr/components/themes/examples.md
  kr/components/treegrid/tree_grid.md
Labels: status: verified

#1119 Add loading classes for category chart topics all versions
  en/components/categorychart.md
  en/components/categorychart_annotation_layers.md
  en/components/categorychart_axis_options.md
  en/components/categorychart_configuration_options.md
  en/components/categorychart_high_volume_data.md
  en/components/categorychart_highlighting.md
  en/components/categorychart_real_time_data.md
  en/components/categorychart_tooltip_templates.md
  en/components/categorychart_tooltip_types.md
  jp/components/categorychart.md
  jp/components/categorychart_annotation_layers.md
  jp/components/categorychart_axis_options.md
  jp/components/categorychart_configuration_options.md
  jp/components/categorychart_custom_tooltips.md
  jp/components/categorychart_explore_chart_types.md
  jp/components/categorychart_high_volume_data.md
  jp/components/categorychart_highlighting.md
  jp/components/categorychart_real_time_data.md
  jp/components/categorychart_tooltip_templates.md
  jp/components/categorychart_tooltip_types.md
  kr/components/categorychart.md
  kr/components/categorychart_annotation_layers.md
  kr/components/categorychart_axis_options.md
  kr/components/categorychart_configuration_options.md
  kr/components/categorychart_explore_chart_types.md
  kr/components/categorychart_high_volume_data.md
  kr/components/categorychart_highlighting.md
  kr/components/categorychart_real_time_data.md
  kr/components/categorychart_tooltip_templates.md
  kr/components/categorychart_tooltip_types.md
Labels: status: verified

#1137 Comment out data chart topics and fixed missed translation.
  jp/components/grids_templates/multi_column_headers.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1142 Remove closeOnOutsideClick and modal overlay properties
  en/components/select.md
  jp/components/select.md
  kr/components/select.md
Labels: select, status: pending-localization

#1036 Changes from AngularDocFX_EN
  en/components/datachart.md
  en/components/datachart_axis_locations.md
  en/components/datachart_axis_scales.md
  en/components/datachart_axis_settings.md
  en/components/datachart_axis_sharing.md
  en/components/datachart_axis_types.md
  en/components/datachart_chart_legends.md
  en/components/datachart_chart_navigation.md
  en/components/datachart_chart_performance.md
  en/components/datachart_chart_synchronization.md
  en/components/datachart_chart_titles.md
  en/components/datachart_data_triangulation.md
  en/components/datachart_series_animations.md
  en/components/datachart_series_annotations.md
  en/components/datachart_series_errorbars.md
  en/components/datachart_series_highlighting.md
  en/components/datachart_series_markers.md
  en/components/datachart_series_requirements.md
  en/components/datachart_series_tooltips.md
  en/components/datachart_series_trendlines.md
  en/components/datachart_series_types.md
  en/components/datachart_series_types_category.md
  en/components/datachart_series_types_financial.md
  en/components/datachart_series_types_polar.md
  en/components/datachart_series_types_radial.md
  en/components/datachart_series_types_range.md
  en/components/datachart_series_types_scatter_area.md
  en/components/datachart_series_types_scatter_bubble.md
  en/components/datachart_series_types_scatter_contour.md
  en/components/datachart_series_types_scatter_hd.md
  en/components/datachart_series_types_scatter_marker.md
  en/components/datachart_series_types_shape.md
  en/components/datachart_series_types_stacked.md
  en/components/datachart_series_value_overlay.md
  en/components/doughnutchart.md
  en/components/excel_library.md
  en/components/excel_library_using_cells.md
  en/components/excel_library_using_tables.md
  en/components/excel_library_using_workbooks.md
  en/components/excel_library_using_worksheets.md
  en/components/excel_library_working_with_charts.md
  en/components/excel_library_working_with_grids.md
  en/components/excel_library_working_with_sparklines.md
  en/components/financialchart.md
  en/components/financialchart_annotation_layers.md
  en/components/financialchart_binding_to_multiple_data.md
  en/components/financialchart_configuration_options.md
  en/components/financialchart_custom_indicators.md
  en/components/financialchart_explore_chart_types.md
  en/components/financialchart_high_volume_data.md
  en/components/financialchart_panes.md
  en/components/financialchart_performance.md
  en/components/financialchart_real_time_data.md
  en/components/financialchart_tooltip_templates.md
  en/components/financialchart_tooltip_types.md
  en/components/piechart.md
Labels: status: verified

#1128 Add lazyload in Data Entry and Display topics for all versions
  en/components/autocomplete.md
  en/components/badge.md
  en/components/button.md
  en/components/buttonGroup.md
  en/components/checkbox.md
  en/components/circular_progress.md
  en/components/drop_down.md
  en/components/icon.md
  en/components/label_input.md
  en/components/linear_progress.md
  en/components/mask.md
  en/components/radio_button.md
  en/components/select.md
  en/components/switch.md
  en/components/texthighlight.md
  jp/components/autocomplete.md
  jp/components/badge.md
  jp/components/button.md
  jp/components/buttonGroup.md
  jp/components/checkbox.md
  jp/components/circular_progress.md
  jp/components/drop_down.md
  jp/components/icon.md
  jp/components/input_group.md
  jp/components/label_input.md
  jp/components/linear_progress.md
  jp/components/mask.md
  jp/components/radio_button.md
  jp/components/select.md
  jp/components/switch.md
  jp/components/texthighlight.md
  kr/components/autocomplete.md
  kr/components/badge.md
  kr/components/button.md
  kr/components/buttonGroup.md
  kr/components/checkbox.md
  kr/components/circular_progress.md
  kr/components/drop_down.md
  kr/components/icon.md
  kr/components/input_group.md
  kr/components/label_input.md
  kr/components/linear_progress.md
  kr/components/mask.md
  kr/components/radio_button.md
  kr/components/select.md
  kr/components/switch.md
  kr/components/texthighlight.md
Labels: status: verified

#1139 Fixing JP issues.
  jp/components/autocomplete.md
  jp/components/banner.md
  jp/components/calendar.md
  jp/components/categorychart.md
  jp/components/categorychart_high_volume_data.md
  jp/components/categorychart_highlighting.md
  jp/components/categorychart_real_time_data.md
  jp/components/chip.md
  jp/components/date_picker.md
  jp/components/display_density.md
  jp/components/doughnutchart.md
  jp/components/drag_drop.md
  jp/components/excel_library.md
  jp/components/excel_library_using_cells.md
  jp/components/excel_library_using_tables.md
  jp/components/excel_library_using_workbooks.md
  jp/components/excel_library_using_worksheets.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_sparklines.md
  jp/components/expansion_panel.md
  jp/components/financialchart_custom_tooltips.md
  jp/components/financialchart_performance.md
  jp/components/general/getting_started.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/conditional_cell_styling.md
  jp/components/grids_templates/display_density.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/multi_column_headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/virtualization.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/icon.md
  jp/components/linear_progress.md
  jp/components/list.md
  jp/components/localization.md
  jp/components/roundness.md
  jp/components/select.md
  jp/components/snackbar.md
  jp/components/toc.yml
  jp/components/tooltip.md
  jp/components/treegrid/aggregations.md
  jp/components/treegrid/tree_grid.md
  jp/components/treegrid/treegrid_batch_editing.md
  jp/components/treegrid/treegrid_row_editing.md
Labels: status: localized, status: verified

#1140 Add sample for excel style filtering operations templates
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/excel_style_filtering.md
Labels: grid, status: pending-localization, status: verified

#1141 Add Tree Grid Remote Filtering docs
  en/components/grids_templates/virtualization.md
  jp/components/grids_templates/virtualization.md
Labels: status: verified, tree grid

#1143 docs(dialog): Added info about retemplating title/actions
  en/components/dialog.md
  jp/components/dialog.md
  kr/components/dialog.md
Labels: dialog, status: pending-localization, status: verified

#1145 Remove comment-out for data chart topics and some translation updates.
  jp/components/datachart_axis_settings.md
  jp/components/datachart_chart_legends.md
  jp/components/datachart_series_trendlines.md
  jp/components/datachart_series_types_financial.md
  jp/components/datachart_series_types_radial.md
  jp/components/datachart_series_types_scatter_bubble.md
  jp/components/grids_templates/search.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1152 Fixed some data chart topic related issues for JP.
  jp/components/datachart_axis_settings.md
  jp/components/datachart_chart_navigation.md
  jp/components/datachart_chart_titles.md
  jp/components/datachart_data_sources.md
  jp/components/datachart_series_highlighting.md
  jp/components/datachart_series_markers.md
  jp/components/datachart_series_trendlines.md
  jp/components/datachart_series_types.md
  jp/components/datachart_series_types_range.md
  jp/components/financialchart_high_volume_data.md
Labels: status: localized, status: verified

#1150 Add sample for igxFilterCellTemplate
  en/components/grids_templates/filtering.md
  jp/components/grids_templates/filtering.md
  kr/components/grids_templates/filtering.md
Labels: grid, status: pending-localization, status: verified

#1151 docs(button-group): Snippets updated, added more info #1006
  en/components/buttonGroup.md
  jp/components/buttonGroup.md
  kr/components/buttonGroup.md
Labels: status: pending-localization, status: verified
