Repository IgniteUI/igniteui-docfx, pull requests merged in 2019-05, with the labels that each got.

#1210 Update Excel style filtering samples container height
  en/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/excel_style_filtering.md
  kr/components/grids_templates/excel_style_filtering.md
Labels: grid, hierarchical-grid, status: pending-localization, status: verified, tree grid

#1179 [DO NOT MERGE] Update button topic with display density
  en/components/button.md
  jp/components/button.md
  kr/components/button.md
Labels: button, do not merge, status: pending-localization, status: verified

#1166 [DO NOT MERGE] Update list topic with display density
  en/components/list.md
  jp/components/list.md
  kr/components/list.md
Labels: list, status: pending-localization, status: verified

#1208 Adding global varibale for theme enabling/disabling
  en/global.json
  jp/global.json
  kr/global.json
Labels: status: verified

#1209 Update documentation about exiting edit mode
  en/components/grids_templates/editing.md
  en/components/grids_templates/row_editing.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/row_editing.md
  kr/components/grids_templates/editing.md
  kr/components/grids_templates/row_editing.md
Labels: grid, status: verified

#1217 Ysugiura/0507
  jp/components/date_picker.md
  jp/components/drop_down_virtual.md
  jp/components/list.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1218 Add Tree Grid Load on Demand topic
  en/.gitignore
  en/components/toc.yml
  en/components/treegrid/load_on_demand.md
  gulpfile.js
  jp/.gitignore
  jp/components/toc.yml
  jp/components/treegrid/load_on_demand.md
  kr/.gitignore
  kr/components/toc.yml
  kr/components/treegrid/load_on_demand.md
Labels: status: verified, tree grid

#1222 REupdate button topic with display density
  en/components/button.md
  jp/components/button.md
  kr/components/button.md
Labels: button, status: pending-localization, status: verified

#1216 Multi row layout topic
  en/components/grids_templates/multi_row_layout.md
  en/components/toc.yml
  en/images/multi-row-layout-1.png
  jp/components/grids_templates/multi_row_layout.md
  jp/components/toc.yml
  jp/images/multi-row-layout-1.png
  kr/components/grids_templates/multi_row_layout.md
  kr/components/toc.yml
  kr/images/multi-row-layout-1.png
Labels: status: pending-localization

#1227 Add state persistence topic
  en/components/grid/grid.md
  jp/components/grid/grid.md
  kr/components/grid/grid.md
Labels: status: verified

#1230 Ysugiura/0509
  jp/components/button.md
  jp/components/overlay_position.md
  jp/components/row_drag.md
  jp/components/spreadsheet_hyperlinks.md
  jp/components/toc.yml
  jp/components/toggle.md
Labels: status: localized, status: verified

#1231 Changes from AngularDocFX_JP
  jp/components/bulletgraph.md
  jp/components/categorychart.md
  jp/components/categorychart_axis_options.md
  jp/components/datachart.md
  jp/components/datachart_axis_locations.md
  jp/components/datachart_data_sources.md
  jp/components/datachart_data_sources_range.md
  jp/components/datachart_series_annotations.md
  jp/components/datachart_series_highlighting.md
  jp/components/datachart_series_trendlines.md
  jp/components/datachart_series_types.md
  jp/components/datachart_series_types_category.md
  jp/components/datachart_series_types_financial.md
  jp/components/datachart_series_types_polar.md
  jp/components/datachart_series_types_radial.md
  jp/components/datachart_series_types_range.md
  jp/components/datachart_series_types_scatter_area.md
  jp/components/datachart_series_types_scatter_bubble.md
  jp/components/datachart_series_types_scatter_contour.md
  jp/components/datachart_series_types_scatter_marker.md
  jp/components/datachart_series_types_shape.md
  jp/components/datachart_series_types_stacked.md
  jp/components/doughnutchart.md
  jp/components/excel_library.md
  jp/components/excel_library_working_with_charts.md
  jp/components/excel_library_working_with_sparklines.md
  jp/components/financialchart.md
  jp/components/financialchart_explore_chart_types.md
  jp/components/financialchart_tooltip_templates.md
  jp/components/lineargauge.md
  jp/components/map_binding_geographic_csv_files.md
  jp/components/map_binding_geographic_json_files.md
  jp/components/map_geographic_scatter_area_series.md
  jp/components/map_geographic_scatter_density_series.md
  jp/components/map_geographic_shape_polyline_series.md
  jp/components/map_overview.md
  jp/components/piechart.md
  jp/components/radialgauge.md
  jp/components/spreadsheet_conditional_formatting.md
  jp/components/spreadsheet_overview.md
Labels: status: localized, status: verified

#1234 Fixing typo in selection grid template
  en/components/grids_templates/selection.md
  kr/components/grids_templates/selection.md
Labels: Topic, status: verified

#1229 Documentation for IgxGrid complex data binding
  en/components/grid/grid.md
  jp/components/grid/grid.md
  kr/components/grid/grid.md
Labels: Topic, status: verified

#1236 chore(row-drag): change base row drag sample
  en/components/grids_templates/row_drag.md
Labels: row-drag, status: verified

#1238 Row drag updates for JP and KR
  jp/components/grids_templates/row_drag.md
  kr/components/grids_templates/row_drag.md
Labels: grid, row-drag, status: verified

#1237 Moved row_drag to the correct folder and comment out Stacked Series i…
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/row_drag.md
  jp/components/row_drag.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1239 Update Row Drag topic in JP
  jp/components/grids_templates/row_drag.md
Labels: row-drag, status: localized, status: verified

#1241 Localized load_on_demand.md.
  jp/components/overlay_scroll.md
  jp/components/themes/component-themes.md
  jp/components/treegrid/load_on_demand.md
Labels: status: localized, status: verified

#1242 Add note for row drag clone
  en/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_drag.md
  kr/components/grids_templates/row_drag.md
Labels: row-drag, status: pending-localization, status: verified

#1232 time picker: add dropdown retemplate documentation
  en/components/time_picker.md
  jp/components/time_picker.md
  kr/components/time_picker.md
Labels: status: localized, status: verified, time picker

#1247 Revert #1232
  en/components/time_picker.md
  jp/components/time_picker.md
  kr/components/time_picker.md
Labels: status: verified

#1226 Adding of Keyboard navigation topic
  en/components/grid/grid.md
  en/components/grids_templates/keyboard_navigation.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/toc.yml
  en/components/treegrid/tree_grid.md
  jp/components/grid/grid.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/toc.yml
  jp/components/treegrid/tree_grid.md
  kr/components/grid/grid.md
  kr/components/grids_templates/keyboard_navigation.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/toc.yml
  kr/components/treegrid/tree_grid.md
Labels: status: verified

#1244 Add new demo to drag topic
  en/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_drag.md
  kr/components/grids_templates/row_drag.md
Labels: row-drag, status: verified

#1246 Ysugiura/0520
  jp/components/divider.md
  jp/components/grids_templates/row_drag.md
Labels: status: localized

#1249 Updated for PR #1226.
  jp/components/card.md
  jp/components/grid/grid.md
  jp/components/grids_templates/display_density.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row_drag.md
  jp/components/toc.yml
  jp/components/tooltip.md
Labels: status: localized, status: verified

#1251 Fixed broken links
  en/components/chip.md
  jp/components/chip.md
  jp/components/dialog.md
  jp/components/hierarchicalgrid/load_on_demand.md
  jp/components/month_picker.md
  jp/components/themes/examples.md
  jp/components/treegrid/tree_grid.md
  jp/components/treegrid/treegrid_batch_editing.md
  kr/components/banner.md
  kr/components/chip.md
  kr/components/display_density.md
  kr/components/divider.md
  kr/components/drop_down_virtual.md
  kr/components/general/cli-overview.md
  kr/components/general/getting_started.md
  kr/components/general/update_guide.md
  kr/components/grids_templates/excel_style_filtering.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/hierarchicalgrid/load_on_demand.md
  kr/components/localization.md
  kr/components/month_picker.md
  kr/components/select.md
  kr/components/treegrid/load_on_demand.md
  kr/components/treegrid/tree_grid.md
  kr/components/treegrid/treegrid_batch_editing.md
  package-lock.json
  package.json
Labels: status: verified

#1240 Update IgxButtonGroup topic with display density
  en/components/buttonGroup.md
  jp/components/buttonGroup.md
  kr/components/buttonGroup.md
Labels: button, status: pending-localization, status: verified

#1248 time picker: add dropdown retemplate documentation
  en/components/time_picker.md
  jp/components/time_picker.md
  kr/components/time_picker.md
Labels: do not merge, status: verified, time picker

#1257 Fix repo vulnerabilities
  gulpfile.js
  package-lock.json
  package.json
Labels: status: verified
