Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-01, with the labels that each got.

#1719 Updating data analysis topic based on latest changes
  en/components/general/framework-and-features/data-analysis.md
  en/images/general/data-analysis-button.PNG
  en/images/general/data-bars-formatting.png
  en/images/general/unique-values-formatting.png
Labels: status: verified

#1720 Updating data analysis topic based on latest changes (master)
  en/components/general/framework-and-features/data-analysis.md
  en/images/general/data-analysis-button.PNG
  en/images/general/data-bars-formatting.png
  en/images/general/unique-values-formatting.png
Labels: status: pending-localization, status: verified

#1714 Adds newly exposed chip icon styling property - vNext
  en/components/chip.md
  jp/components/chip.md
  kr/components/chip.md
Labels: category-styling, chip, status: awaiting-test

#1713 Separates selection-based summaries into a new topic
  en/.gitignore
  en/components/grid/selection_based_aggregates.md
  en/components/grids_templates/selection.md
  en/components/grids_templates/summaries.md
  en/components/toc.yml
  gulpfile.js
  jp/.gitignore
  jp/components/grid/selection_based_aggregates.md
  kr/.gitignore
  kr/components/grid/selection_based_aggregates.md
Labels: category-topic, grid-selection, status: verified

#1709 Add select header footer topic
  en/components/select.md
Labels: category-enhancement, select, status: verified

#1723 Adding a schematics snippet
  en/components/general/cli/auth-template.md
Labels: category-cli, status: verified, version: 9.0.x

#1724 Adding localized strings for latest EN topic updates.
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/grids_templates/cell_selection.md
  jp/components/grids_templates/state_persistence.md
  jp/components/state_persistence.md
  jp/components/toc.yml
  jp/components/transaction-classes.md
  jp/images/general/data-analysis-button.PNG
  jp/images/general/data-bars-formatting.png
  jp/images/general/unique-values-formatting.png
Labels: status: localized, status: verified

#1739 updating template ver in package.json
  package-lock.json
  package.json
Labels: do not merge

#1748 Adding lobDemosBaseUrl environment variable
  en/components/grid/grid.md
  en/components/grid/master_detail.md
  en/components/grids_templates/column_resizing.md
  en/components/grids_templates/live_data.md
  en/components/treegrid/aggregations.md
  en/components/treegrid/tree_grid.md
  jp/components/grid/grid.md
  jp/components/grid/master_detail.md
  jp/components/grids_templates/column_resizing.md
  jp/components/grids_templates/live_data.md
  jp/components/treegrid/aggregations.md
  jp/components/treegrid/tree_grid.md
  kr/components/grid/grid.md
  kr/components/grids_templates/column_resizing.md
  kr/components/treegrid/aggregations.md
  kr/components/treegrid/tree_grid.md
Labels: status: verified

#1749 Adding _language property in toc files
  jp/components/toc.yml
  jp/toc.yml
  kr/components/toc.yml
  kr/toc.yml
Labels: status: verified

#1757 Changes from AngularDocFX_EN
  en/components/data-chart-axis-types.md
  en/components/data-chart-navigation.md
  en/components/excel_library_using_cells.md
  en/components/financial-chart-panes.md
  en/components/financial-chart-performance.md
  en/components/general-breaking-changes-dv.md
  en/components/general/breaking_changes_dv.md
  en/components/geo-map-display-bing-imagery.md
  en/components/spreadsheet_configuring.md
Labels: dv-charts, status: in-review

#1753 Adding single selection combo sample
  en/components/combo.md
Labels: combo, status: verified, version: 9.0.x

#1756 Adding Combo Single Selection sample and text
  en/components/combo.md
Labels: combo, status: verified, version: 8.2.x
