Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-06, with the labels that each got.

#1974 Enhance the Keyboard Navigation topic
  en/components/grids_templates/keyboard_navigation.md
  en/components/grids_templates/selection.md
  en/components/toc.yml
Labels: category-enhancement, keyboard-navigation, status: pending-localization, status: verified

#1949 Infinite Scroll Topic
  en/components/grids_templates/remote_data_operations.md
Labels: status: pending-localization, status: verified, version: 9.1.x

#1939 Adds igxForOf dynamic height changing known limitation - 9.1
  en/components/for_of.md
  jp/components/for_of.md
Labels: status: pending-localization, status: verified, version: 9.1.x

#1990 docs: upgrade command packages update, yarn note, token setup typo
  en/components/general/ignite-ui-licensing.md
Labels: status: pending-localization

#1988 docs: upgrade command packages update, yarn note, token setup typo
  en/components/general/ignite-ui-licensing.md
Labels: status: pending-localization, version: 9.1.x

#1993 docs(nav): removing tab nav from mrl doc #1935
  en/components/grids_templates/multi_row_layout.md
Labels: status: pending-localization

#1996 chore(*): Address issues 1941, 1908, 1800, 1722
  en/components/exporter_excel.md
  en/components/grid/grid.md
  en/components/grids_templates/collapsible_column_groups.md
  en/components/grids_templates/export_excel.md
  jp/components/grids_templates/collapsible_column_groups.md
Labels: status: verified

#1997 chore(*): Address issues 1941, 1908, 1800, 1722
  en/components/exporter_excel.md
  en/components/grid/grid.md
  en/components/grids_templates/collapsible_column_groups.md
  en/components/grids_templates/export_excel.md
  jp/components/grids_templates/collapsible_column_groups.md
Labels: status: pending-localization

#1998 Updating remaining JP topics - vNext.
  jp/components/chip.md
  jp/components/date_range_picker.md
  jp/components/for_of.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/selection.md
  jp/components/toc.yml
  jp/images/general/azure-ci-add-token-variable-1.JPG
  jp/images/general/azure-ci-new-variable-2.JPG
  jp/images/general/azure-ci-pipelines-ci-yml-3.JPG
  jp/images/general/fullscreen-black-18dp.svg
  jp/images/general/fullscreen-white-18dp.svg
  jp/images/general/generate-token.JPG
Labels: status: localized

#1999 Updating the remaining JP topics - master.
  jp/components/chip.md
  jp/components/date_range_picker.md
  jp/components/for_of.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/remote_data_operations.md
  jp/components/grids_templates/selection.md
  jp/components/toc.yml
  jp/images/general/azure-ci-add-token-variable-1.JPG
  jp/images/general/azure-ci-new-variable-2.JPG
  jp/images/general/azure-ci-pipelines-ci-yml-3.JPG
  jp/images/general/fullscreen-black-18dp.svg
  jp/images/general/fullscreen-white-18dp.svg
  jp/images/general/generate-token.JPG
Labels: status: localized

#2001 Updating data analysis topic package section (vnext)
  en/components/general/framework-and-features/data-analysis.md
Labels: status: verified

#2002 Updating data analysis topic package section (master)
  en/components/general/framework-and-features/data-analysis.md
Labels: status: verified

#1989 fix(drop-down): fix virtual remote dropdown snippet - vNext
  en/components/drop_down_virtual.md
  jp/components/drop_down_virtual.md
  kr/components/drop_down_virtual.md
Labels: dropdown, status: localized, status: verified, version: 9.1.x

#1985 fix(drop-down): fix virtual remote dropdown snippet - master
  en/components/drop_down_virtual.md
  jp/components/drop_down_virtual.md
  kr/components/drop_down_virtual.md
Labels: dropdown, status: localized, status: verified, version: 9.1.x

#2015 Updating localization to match latest EN changes - vNext
  jp/components/dock-manager.md
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/general/ignite-ui-licensing.md
Labels: status: localized, status: verified

#2016 Updating localization to match EN changes - master
  jp/components/dock-manager.md
  jp/components/exporter_excel.md
  jp/components/general/framework-and-features/data-analysis.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grid/grid.md
  jp/components/grids_templates/collapsible_column_groups.md
  jp/components/grids_templates/export_excel.md
Labels: status: localized, status: verified

#2006 Add dock manager to templates list
  en/components/general/cli/component-templates.md
Labels: category-cli, dock-manager, status: pending-localization

#2012 Add dock-manager template
  en/components/general/cli/component-templates.md
Labels: category-cli, dock-manager, status: pending-localization, version: 9.1.x

#2019 Adding API table for igniteui-angular-extras
  en/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/data-analysis.md
Labels: status: verified

#2022 Adding API table for igniteui-angular-extras (master)
  en/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/data-analysis.md
Labels: status: verified

#1995 Add igxHint usage in topic
  en/components/select.md
Labels: select, status: verified, version: 9.2.x

#2013 docs(autocomplete): update autocomplete docs
  en/components/autocomplete.md
Labels: autocomplete, status: pending-localization, status: verified, version: 10.0.x

#2014 docs(drop-down): edit drop-down documentations
  en/components/drop_down.md
  en/components/drop_down_virtual.md
Labels: dropdown, status: pending-localization, status: verified, version: 10.0.x

#2025 Update the topic for text highlight
  en/components/texthighlight.md
Labels: status: pending-localization, status: verified, text-highlight, version: 9.2.x

#2020 Additional localization to match EN - vNext.
  jp/components/exporter_excel.md
  jp/components/general/cli/component-templates.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grid/grid.md
  jp/components/grids_templates/collapsible_column_groups.md
  jp/components/grids_templates/export_excel.md
Labels: status: localized, status: verified

#2004 Rename ESF template labels to more meaningful ones
  en/components/grids_templates/excel_style_filtering.md
Labels: status: verified

#2007 Rename ESF template labels to more meaningful ones
  en/components/grids_templates/excel_style_filtering.md
Labels: status: verified

#2009 Link every article with its tutorial
  en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
Labels: status: verified

#2024 Updating Component Themes topic localization - master.
  jp/components/general/cli/component-templates.md
  jp/components/grids_templates/export_excel.md
Labels: status: localized, status: verified

#2018 Add a note for hierarchy levels #1948
  en/components/treegrid/tree_grid.md
Labels: category-enhancement, status: verified, tree grid

#2008 Link every article with its tutorial
  en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
Labels: status: verified

#2017 docs(tree-grid): Add a note for hierarchy levels #1948
  en/components/treegrid/tree_grid.md
Labels: category-enhancement, status: verified, tree grid

#1975 Remote Paging using default pagination template
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote_data_operations.md
Labels: grid, paging, status: in-test

#2031 docs(select): update select docs
  en/components/select.md
Labels: select, status: pending-localization, version: 10.0.x

#2035 Updating JP localization for latest EN topic changes - Autocomplete, Drop Down, Text Highlight
  jp/components/autocomplete.md
  jp/components/drop_down.md
  jp/components/drop_down_virtual.md
  jp/components/texthighlight.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2046 Promote 10
  en/components/autocomplete.md
  en/components/drag_drop.md
  en/components/drop_down.md
  en/components/drop_down_virtual.md
  en/components/grid/master_detail.md
  en/components/grids_templates/multi_row_layout.md
  en/components/select.md
  en/components/texthighlight.md
  jp/components/autocomplete.md
  jp/components/drop_down.md
  jp/components/drop_down_virtual.md
  jp/components/exporter_excel.md
  jp/components/grid/grid.md
  jp/components/grids_templates/collapsible_column_groups.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/texthighlight.md
Labels: version: 10.0.x

#2041 Mvenkov/update grid edit event vnext
  en/components/grids_templates/editing.md
  jp/components/grids_templates/editing.md
Labels: grid, severity: medium, status: pending-localization, status: verified, version: 9.0.x, version: 9.1.x, version: 9.2.x
