Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-02, with the labels that each got.

#1759 Fixing wrong url for sample with chart.
  en/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  kr/components/hierarchicalgrid/hierarchical_grid.md
Labels: status: verified

#1763 Fix src in iframe
  en/components/general/framework-and-features/data-analysis.md
  jp/components/general/framework-and-features/data-analysis.md
Labels: status: verified

#1764 Update docfx-template to 2.5.2
  package-lock.json
  package.json
Labels: status: resolved

#1740 [DO NOT MERGE]Replaced kr domains to use infragistics.co.kr
  en/global.json
  jp/global.json
  kr/global.json
  kr/toc.yml
  package-lock.json
  package.json
Labels: status: verified

#1768 Updating empty project template id from "empty-project" to "empty"
  en/components/general/cli-overview.md
  jp/components/general/cli-overview.md
Labels: status: verified

#1761 chore(*): Adding warning for components that use hammer module for in…
  en/components/calendar.md
  en/components/carousel.md
  en/components/date_picker.md
  en/components/general/update_guide.md
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical_grid.md
  en/components/list.md
  en/components/month_picker.md
  en/components/navdrawer.md
  en/components/slider/slider.md
  en/components/time_picker.md
  en/components/treegrid/tree_grid.md
  jp/components/calendar.md
  jp/components/carousel.md
  jp/components/date_picker.md
  jp/components/general/update_guide.md
  jp/components/grid/grid.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/list.md
  jp/components/month_picker.md
  jp/components/navdrawer.md
  jp/components/slider/slider.md
  jp/components/time_picker.md
  jp/components/treegrid/tree_grid.md
Labels: status: localized

#1731 Updating JP to match latest EN changes. Exposing Master-Detail topic for JP.
  jp/components/combo.md
  jp/components/grid/selection_based_aggregates.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1737 Updating JP Data Analysis Topic according to latest changes - master
  jp/components/combo.md
  jp/components/general/framework-and-features/data-analysis.md
  jp/images/general/data-analysis-button.PNG
  jp/images/general/data-bars-formatting.png
  jp/images/general/unique-values-formatting.png
Labels: status: localized, status: verified

#1769 fix(badge): fixing the avatar + badge #1721
  en/components/badge.md
  jp/components/badge.md
  kr/components/badge.md
Labels: badge, status: localized, status: verified

#1778 Adding fixes to JP - vNext
  jp/components/date_picker.md
  jp/components/general/cli/auth-template.md
  jp/components/general/update_guide.md
  jp/components/grid/grid.md
  jp/components/grid/master_detail.md
  jp/components/grids_templates/selection.md
  jp/components/month_picker.md
  jp/components/select.md
  jp/components/slider/slider.md
  jp/components/time_picker.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1779 Adding fixes to JP - master.
  jp/components/date_picker.md
  jp/components/general/cli/auth-template.md
  jp/components/general/update_guide.md
  jp/components/grid/grid.md
  jp/components/grid/master_detail.md
  jp/components/grids_templates/selection.md
  jp/components/month_picker.md
  jp/components/select.md
  jp/components/slider/slider.md
  jp/components/time_picker.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#1772 Fixing demos-base-urls attributes (vNext)
  en/components/grids_templates/row_selection.md
  jp/components/grids_templates/row_selection.md
Labels: status: verified

#1773 Fixing data-demos-base-url attributes (master)
  en/components/grids_templates/row_selection.md
  jp/components/grids_templates/row_selection.md
Labels: status: verified

#1784 docs(update-guide): list changes made to the enums and their members
  en/components/general/update_guide.md
  jp/components/general/update_guide.md
Labels: status: localized, version: 9.0.x

#1803 docs(*): update tags - add/remove new #1785
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified, version: 9.1.x

#1804 docs(*): update tags - add/remove new #1785
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified, version: 9.0.x
