Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-09, with the labels that each got.

#2204 docs(mask): update mask docs
  en/components/mask.md
Labels: mask, status: pending-localization, version: 10.2.x

#2195 move filtering topics as children of a main filtering topic #2178
  en/components/grids_templates/filtering-overview.md
  en/components/grids_templates/filtering.md
  en/components/toc.yml
Labels: status: verified

#2206 docs(combo): improve combo component documentation
  en/components/combo.md
  en/components/combo_cascading.md
  en/components/combo_features.md
  en/components/combo_remote.md
  en/components/combo_templates.md
Labels: combo, status: pending-localization, status: verified

#2193 move filtering topics as children of a main filtering topic #2178
  en/components/grids_templates/filtering-overview.md
  en/components/grids_templates/filtering.md
  en/components/toc.yml
Labels: status: pending-localization, status: verified

#2205 docs(grid): Toolbar topic add export visaulization
  en/components/grids_templates/toolbar.md
  en/components/toc.yml
Labels: grid, status: pending-localization, status: verified

#2218 Revert "docs(grid): Toolbar topic add export visaulization"
  en/components/grids_templates/toolbar.md
  en/components/toc.yml
Labels: status: verified

#2201 feat(inputgroup): Add InputGroupToken #2200
  en/components/input_group.md
Labels: input-group, status: verified

#2220 Re-apply "docs(grid): Toolbar topic add export visualization"
  en/components/grids_templates/toolbar.md
  en/components/toc.yml
Labels: status: verified

#2215 Localization dhristova 0909 master
  jp/components/general/update_guide.md
  jp/components/grids_templates/cell_selection.md
  jp/components/grids_templates/filtering-overview.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row_editing.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2214 Adding changes from #2195 and #2204.
  jp/components/combo.md
  jp/components/combo_cascading.md
  jp/components/combo_features.md
  jp/components/combo_remote.md
  jp/components/combo_templates.md
  jp/components/general/update_guide.md
  jp/components/grids_templates/filtering-overview.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/toolbar.md
  jp/components/mask.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2203 Time picker custom label
  en/components/time_picker.md
Labels: status: pending-localization, status: verified, time-picker

#2221 Update column moving topic
  en/components/grids_templates/column_moving.md
  en/components/toc.yml
  jp/components/grids_templates/column_moving.md
  jp/components/toc.yml
  kr/components/grids_templates/column_moving.md
Labels: column-moving, status: pending-localization, status: verified

#2227 Updating JP localization to match the latest EN changes
  jp/components/grids_templates/column_moving.md
  jp/components/input_group.md
  jp/components/time_picker.md
Labels: status: localized, status: verified

#2235 Seo related updates master
  en/components/general/angular-grid-overview-guide.md
  en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  en/components/grid/grid.md
  en/components/list.md
Labels: status: pending-localization

#2231 docs(avatar): correct wrong snippet code
  en/components/avatar.md
  jp/components/avatar.md
Labels: avatar, status: pending-localization, status: verified, version: 10.2.x

#2229 docs(avatar): correct wrong snippet code
  en/components/avatar.md
  jp/components/avatar.md
Labels: avatar, status: pending-localization, status: verified, version: 10.1.x

#2236 [JP] Small changes in Breaking Changes topic.
  jp/components/general-breaking-changes-dv.md
Labels: status: localized

#2238 ShowWeekNumbers - Update calendar and date picker topics
  en/components/calendar.md
  en/components/date_picker.md
Labels: status: verified

#2099 Update the update_guide.md to reflect the dropdown item changes
  en/components/general/update_guide.md
Labels: dropdown, status: localized

#2230 Multi-cell selection topic for Hierarchical Grid --vNext
  en/components/grids_templates/cell_selection.md
  en/components/toc.yml
Labels: hierarchical-grid, multi-cell-selection, status: verified

#2213 Valadzhov/date picker new label 8086
  en/components/date_picker.md
Labels: date-picker, status: pending-localization, status: verified

#2240 Move target from position to overlay settings
  en/components/overlay_main.md
  en/components/overlay_position.md
  en/components/select.md
  en/components/toggle.md
Labels: overlay, status: verified, version: 10.2.x

#2249 Update headers master
  en/components/general/accessibility-compliance.md
  en/components/general/cli-overview.md
  en/components/general/cli/auth-template.md
  en/components/general/cli/component-templates.md
  en/components/general/cli/step-by-step-guide.md
  en/components/general/framework-and-features/data-analysis.md
  en/components/general/framework-and-features/framework-and-features.md
  en/components/general/framework-and-features/ssr-rendering.md
  en/components/general/getting_started.md
  en/components/general/update_guide.md
  en/components/grid/grid.md
  en/components/grid/groupby.md
  en/components/grid/master_detail.md
  en/components/grid/paste_excel.md
  en/components/grid/selection_based_aggregates.md
  en/components/grids_and_lists.md
  en/components/grids_templates/advanced_filtering.md
  en/components/grids_templates/batch_editing.md
  en/components/grids_templates/cell_editing.md
  en/components/grids_templates/cell_selection.md
  en/components/grids_templates/clipboard_interactions.md
  en/components/grids_templates/collapsible_column_groups.md
  en/components/grids_templates/column_hiding.md
  en/components/grids_templates/column_moving.md
  en/components/grids_templates/column_resizing.md
  en/components/grids_templates/column_selection.md
  en/components/grids_templates/conditional_cell_styling.md
  en/components/grids_templates/display_density.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/excel_style_filtering.md
  en/components/grids_templates/export_excel.md
  en/components/grids_templates/filtering-overview.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/keyboard_navigation.md
  en/components/grids_templates/live_data.md
  en/components/grids_templates/multi_column_headers.md
  en/components/grids_templates/multi_row_layout.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote_data_operations.md
  en/components/grids_templates/row_drag.md
  en/components/grids_templates/row_editing.md
  en/components/grids_templates/row_pinning.md
  en/components/grids_templates/row_selection.md
  en/components/grids_templates/search.md
  en/components/grids_templates/selection.md
  en/components/grids_templates/sizing.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/state_persistence.md
  en/components/grids_templates/summaries.md
  en/components/grids_templates/toolbar.md
  en/components/grids_templates/virtualization.md
  en/components/toc.yml
  jp/components/grids_templates/live_data.md
  kr/components/grids_templates/column_moving.md
  kr/components/grids_templates/multi_column_headers.md
  kr/components/grids_templates/multi_row_layout.md
  kr/components/themes/examples.md
  kr/components/themes/theming-demo.md
  package-lock.json
  package.json
Labels: status: verified

#2251 Updating JP for #2238 and #2230.
  jp/components/calendar.md
  jp/components/date_picker.md
  jp/components/grids_templates/cell_selection.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2241 Localization 1709
  jp/components/date_picker.md
  jp/components/general/angular-grid-overview-guide.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/grid/grid.md
  jp/components/list.md
Labels: status: localized, status: verified

#2242 Localization 1709 master
  jp/components/general/angular-grid-overview-guide.md
  jp/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
  jp/components/grid/grid.md
  jp/components/list.md
Labels: status: localized, status: verified
