Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-08, with the labels that each got.

#2116 Add sorting inidicators section in all grid sorting topics
  en/components/grids_templates/sorting.md
  en/components/toc.yml
Labels: status: verified

#2132 update the overlay_styling.md
  en/components/overlay_styling.md
Labels: overlay

#2131 Update the overlay_styling.md
  en/components/overlay_styling.md
Labels: overlay, status: verified

#2097 chore(*): Add section for custom group by.
  en/components/grid/groupby.md
Labels: status: pending-localization, status: verified

#2130 Adding changes from #2119 and #2107
  jp/components/card.md
  jp/components/grids_templates/column_moving.md
  jp/components/grids_templates/paging.md
  jp/components/themes/typography.md
Labels: status: localized, status: verified

#2112 Adding changes from #2102, #2095, #2086, #2085, #2080
  jp/components/calendar.md
  jp/components/combo_features.md
  jp/components/navbar.md
  jp/components/toast.md
  jp/components/toggle.md
  jp/components/transaction-how-to-use.md
Labels: status: localized, status: verified

#2133 Adding changes from #2122, #2120, #2087
  jp/components/calendar.md
  jp/components/exporter_excel.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/paging.md
  jp/components/themes/typography.md
Labels: status: localized, status: verified

#2135 Adding changes from #2116, #2097, #2093
  jp/components/exporter_excel.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/sorting.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2129 docs(button): add docs for extended FAB
  en/components/button.md
Labels: button

#2113 Update topic with selectedRows input
  en/components/general/update_guide.md
  en/components/grids_templates/row_selection.md
Labels: grid, grid-row-selection, hierarchical-grid, status: verified, tree grid

#2111 Add section for external outlet
  en/components/grids_templates/excel_style_filtering.md
Labels: grid, overlay, status: verified

#2110 Add section for external outlet
  en/components/grids_templates/excel_style_filtering.md
Labels: grid, overlay, status: verified

#2127 Updates code snippets in docs to match w/ sample
  en/components/grids_templates/batch_editing.md
Labels: batch-editing, hierarchical-grid, status: pending-localization, status: verified, transaction, version: 10.1.x

#2138 Add the new cellEditDone & rowEditDone events
  en/components/grids_templates/editing.md
  en/components/grids_templates/row_editing.md
Labels: category-enhancement, grid, status: pending-localization, status: verified

#2142 Update docfx-template version to 2.7.3
  en/components/general/getting_started.md
  package-lock.json
  package.json
Labels: status: verified

#2125 Update topic for complex data
  en/components/grid/grid.md
  jp/components/grid/grid.md
Labels: grid, status: verified

#2140 fix(grid): move row reorder under Application Demo section - vNext
  en/components/grids_templates/row_drag.md
Labels: grid, hierarchical-grid, status: verified, tree grid, version: 10.1.x

#2139 fix(grid): move row reorder under Application Demo section, #2098
  en/components/grids_templates/row_drag.md
Labels: grid, hierarchical-grid, status: verified, tree grid, version: 10.1.x

#2143 Update template to 2.7.3
  en/components/general/getting_started.md
  package-lock.json
  package.json
Labels: status: verified

#2145 Fix igxDateRangeSeparator typo & link
  en/components/date_range_picker.md
Labels: range-date-picker, status: verified

#2144 Default template note, typos and activeNodeChange
  en/components/general/accessibility-compliance.md
  en/components/general/framework-and-features/framework-and-features.md
  en/components/grid/grid.md
  en/components/grids_templates/keyboard_navigation.md
  jp/components/general/accessibility-compliance.md
  jp/components/general/framework-and-features/framework-and-features.md
  jp/components/grids_templates/keyboard_navigation.md
Labels: status: verified

#2147 Default template note, typos and activeNodeChange
  en/components/general/accessibility-compliance.md
  en/components/general/framework-and-features/framework-and-features.md
  en/components/grid/grid.md
  en/components/grids_templates/keyboard_navigation.md
  jp/components/general/framework-and-features/framework-and-features.md
  jp/components/grids_templates/keyboard_navigation.md
Labels: status: verified

#2148 Fix igxDateRangeSeparator typo & link_master
  en/components/date_range_picker.md
Labels: range-date-picker, status: verified

#2134 Add ESF template docs
  en/components/general/update_guide.md
  en/components/grids_templates/excel_style_filtering.md
  en/components/toc.yml
Labels: grid, hierarchical-grid, status: verified, tree grid, version: 10.1.x

#2150 Fix korean topic - localization topic
  en/components/localization.md
  jp/components/localization.md
  kr/components/localization.md
Labels: status: verified, version: 10.1.x

#2121 Adds info about joint use of row editing & transaction
  en/components/grids_templates/batch_editing.md
Labels: batch-editing, status: pending-localization, status: verified, transaction

#2152 docs(export-excel): remove obsolete sentence
  en/components/grids_templates/export_excel.md
Labels: status: verified

#2141 changing column hiding topic to use column actions
  en/components/grids_templates/column_hiding.md
Labels: status: pending-localization

#2153 docs(export-excel): remove obsolete sentence
  en/components/grids_templates/export_excel.md
Labels: status: verified

#2159 Minor addition to the localized content
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/keyboard_navigation.md
Labels: status: localized, status: verified

#2166 Update heights on state sample
  en/components/grids_templates/state_persistence.md
Labels: status: verified

#2165 Update heights on state samples
  en/components/grids_templates/state_persistence.md
Labels: status: verified

#2167 Upgrade to 2.7.4
  package-lock.json
  package.json
Labels: status: verified

#2168 Upgrade to docfx-tempalte 2.7.4
  package-lock.json
  package.json
Labels: status: verified

#2169 [JP] Updating topics to match the latest EN changes. - vNext
  jp/components/date_range_picker.md
  jp/components/general/update_guide.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_selection.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2170 [JP] Updating topics to match the latest EN changes. - master
  jp/components/date_range_picker.md
  jp/components/general/update_guide.md
  jp/components/grids_templates/batch_editing.md
  jp/components/grids_templates/column_hiding.md
  jp/components/grids_templates/excel_style_filtering.md
  jp/components/grids_templates/export_excel.md
  jp/components/grids_templates/keyboard_navigation.md
  jp/components/grids_templates/row_drag.md
  jp/components/grids_templates/row_selection.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2172 refactor(input-group): update the types section
  en/components/input_group.md
Labels: 10.2.x, input-group, status: pending-localization

#2064 chore(*): Update the values for minimum allowed width with the differ…
  en/components/grid/grid.md
  en/components/grids_templates/display_density.md
Labels: status: pending-localization, status: verified

#2065 chore(*): Update the values for minimum allowed width with the differ…
  en/components/grid/grid.md
  en/components/grids_templates/display_density.md
Labels: status: pending-localization, status: verified

#2176 [JP] Localization fixes - vNext
  jp/components/general/framework-and-features/framework-and-features.md
  jp/components/grid/grid.md
  jp/components/grids_templates/paging.md
  jp/components/ripple.md
Labels: status: localized

#2177 [JP] Localization fixes - master
  jp/components/general/framework-and-features/framework-and-features.md
  jp/components/grid/grid.md
  jp/components/grids_templates/paging.md
  jp/components/ripple.md
  jp/components/toc.yml
Labels: status: localized

#2183 docs(filtering): add known limitations section
  en/components/grids_templates/filtering.md
Labels: category-enhancement, grid, status: verified

#2174 docs(filtering): add known limitations section
  en/components/grids_templates/filtering.md
Labels: category-enhancement, grid, status: pending-localization, status: verified

#2188 Hierarchical structure for editing topics -master
  en/components/grids_templates/cell_editing.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/row_editing.md
  en/components/toc.yml
Labels: batch-editing, grid, status: verified

#2190 docs(datepicker): update code block
  en/components/date_picker.md
  jp/components/date_picker.md
Labels: date-picker

#2189 docs(datepicker): update code block
  en/components/date_picker.md
  jp/components/date_picker.md
Labels: date-picker

#2192 Adding changes from #2174
  jp/components/grids_templates/filtering.md
Labels: status: localized, status: verified

#2191 Adding changes from #2183, #2175 and #2173
  jp/components/for_of.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/cell_editing.md
  jp/components/grids_templates/column_pinning.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi_row_layout.md
  jp/components/grids_templates/row_editing.md
  jp/components/grids_templates/row_pinning.md
  jp/components/hierarchicalgrid/hierarchical_grid.md
  jp/components/material_icons_extended.md
  jp/components/toc.yml
  jp/components/treegrid/tree_grid.md
Labels: status: localized, status: verified
