Repository IgniteUI/igniteui-docfx, pull requests merged in 2020-11, with the labels that each got.

#2358 Updating JP - vnext
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/search.md
  jp/components/list.md
Labels: status: localized, status: verified

#2337 Refactoring grids filtering topics
  en/components/general/angular-grid-overview-guide.md
  en/components/grids_templates/filtering-overview.md
  en/components/grids_templates/filtering.md
  en/components/toc.yml
Labels: SEO, status: pending-localization, status: verified

#2365 Seo filtering topics master
  en/components/general/angular-grid-overview-guide.md
  en/components/grids_templates/filtering-overview.md
  en/components/grids_templates/filtering.md
  en/components/toc.yml
Labels: status: verified

#2375 refactor(tree-grid): Update header structure-vnext
  en/components/treegrid/tree-grid.md
Labels: category-topic

#2376 refactor(tree-grid): Update header structure-master
  en/components/treegrid/tree-grid.md
Labels: category-topic

#2383 Update template to 2.8.4-beta.0 (vNext)
  package-lock.json
  package.json
Labels: status: verified

#2385 [JP] Updating topics with the latest changes.
  jp/components/action-strip.md
  jp/components/chip.md
  jp/components/general/angular-grid-overview-guide.md
  jp/components/grids_templates/cell-selection.md
  jp/components/grids_templates/column-selection.md
  jp/components/grids_templates/filtering-overview.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/selection.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2388 Updating JP topics - vnext.
  jp/components/action-strip.md
  jp/components/chip.md
  jp/components/general/angular-grid-overview-guide.md
  jp/components/grids_templates/cell-selection.md
  jp/components/grids_templates/column-selection.md
  jp/components/grids_templates/filtering-overview.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/selection.md
  jp/components/toc.yml
Labels: status: localized

#2373 add example for toast show method -vnext
  en/components/toast.md
Labels: status: verified, toast

#2374 add example for toast show method -master
  en/components/toast.md
Labels: status: verified, toast

#2363 refactor (combo): Content update-vnext
  en/components/combo.md
Labels: SEO, status: verified

#2364 refactor (combo): Content update-master
  en/components/combo.md
Labels: SEO, status: verified

#2369 Add codesandbox for button -vNext
  en/components/button.md
Labels: button, status: verified

#2370 Add codesandbox for button -master
  en/components/button.md
Labels: button, status: verified

#2392 Replace underscores in topic hrefs with hiphens
  en/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/virtualization.md
  jp/components/general/cli/component-templates.md
  jp/components/grid/grid.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/clipboard-interactions.md
  jp/components/grids_templates/collapsible-column-groups.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-moving.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/display-density.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/virtualization.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
Labels: status: verified

#2393 Replace underscores in topics hrefs with hiphens (master)
  en/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/virtualization.md
  jp/components/general/cli/component-templates.md
  jp/components/grid/grid.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/clipboard-interactions.md
  jp/components/grids_templates/collapsible-column-groups.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-moving.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/display-density.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/virtualization.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
Labels: status: verified

#2380 Add keyboard references-vnext
  en/components/grid/grid.md
Labels: category-topic, status: pending-localization, status: verified

#2381 Add keyboard references-master
  en/components/grid/grid.md
Labels: category-topic, status: pending-localization, status: verified

#2356 refactor (group-by): Content update -vnext
  en/components/grid/groupby.md
Labels: SEO, status: verified

#2357 refactor (group-by): Content update -master
  en/components/grid/groupby.md
Labels: SEO, status: pending-localization, status: verified

#2361 refactor (main grid pages): Content update -vnext
  en/components/grid/grid.md
  en/components/grids-and-lists.md
  en/components/grids_templates/search.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/treegrid/tree-grid.md
  kr/components/grids_templates/search.md
Labels: SEO, status: pending-localization, status: verified

#2362 refactor (main grid pages): Content update -master
  en/components/grid/grid.md
  en/components/grids-and-lists.md
  en/components/grids_templates/search.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/treegrid/tree-grid.md
  kr/components/grids_templates/search.md
Labels: SEO, status: pending-localization, status: verified

#2352 Remove redundant paragraph (vNext)
  en/components/grids_templates/remote-data-operations.md
Labels: status: pending-localization

#2353 Remove redundant paragraph (master)
  en/components/grids_templates/remote-data-operations.md
Labels: status: pending-localization

#2397 Updating template to 2.8.4 (vNext)
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/treegrid/tree-grid.md
  package-lock.json
  package.json
Labels: status: verified

#2398 Updating template to 2.8.4 (master)
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/treegrid/tree-grid.md
  package-lock.json
  package.json
Labels: status: verified

#2372 update excel style filtering demo to include header icon template directive
  en/components/grids_templates/excel-style-filtering.md
Labels: grid, status: pending-localization, status: verified

#2255 Added documentation regarding the groupby-row selectors
  en/components/grid/groupby.md
  en/components/grids_templates/keyboard-navigation.md
  en/components/grids_templates/row-selection.md
Labels: category-topic, grid, grid-groupby-row-selection, grid-selection, status: pending-localization

#2406 SEO Updates meta keywords, desc and title
  en/components/combo.md
  en/components/grid/grid.md
  en/components/grid/groupby.md
  en/components/grids-and-lists.md
  en/components/grids_templates/advanced-filtering.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/search.md
  en/components/list.md
  en/components/treegrid/tree-grid.md
  jp/components/combo.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/search.md
  jp/components/list.md
  jp/components/treegrid/tree-grid.md
Labels: status: pending-localization, status: verified

#2407 SEO Updates
  en/components/combo.md
  en/components/grid/grid.md
  en/components/grid/groupby.md
  en/components/grids-and-lists.md
  en/components/grids_templates/advanced-filtering.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/search.md
  en/components/list.md
  en/components/treegrid/tree-grid.md
  jp/components/combo.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/search.md
  jp/components/list.md
  jp/components/treegrid/tree-grid.md
Labels: status: pending-localization, status: verified

#2400 Add sortable property for grid topics-vnext
  en/components/toc.yml
  package-lock.json
  package.json
Labels: status: verified

#2402 Updating JP - vnext
  jp/components/combo.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/toast.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2411 Toolbar topic updates
  en/components/general/update-guide.md
  en/components/grids_templates/toolbar.md
  en/components/toc.yml
Labels: status: verified, toolbar, version: 11.0.x

#2412 Updating JP - vnext
  jp/components/combo-features.md
  jp/components/combo.md
  jp/components/general-licensing.md
  jp/components/general/angular-grid-overview-guide.md
  jp/components/grid/grid.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/list.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2416 Localization - Updating JP - vnext
  jp/components/excel-library-using-cells.md
  jp/components/excel-library-using-tables.md
  jp/components/excel-library-using-workbooks.md
  jp/components/excel-library-using-worksheets.md
  jp/components/excel-library-working-with-charts.md
  jp/components/excel-library-working-with-grids.md
  jp/components/excel-library-working-with-sparklines.md
  jp/components/excel-library.md
  jp/components/general/update-guide.md
  jp/components/grids_templates/toolbar.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2417 Changes from AngularDocFX_JP
  jp/components/general-licensing.md
Labels: status: pending-localization

#2425 update live data topic
  en/components/grids_templates/live-data.md
Labels: status: verified

#2436 Fixes column selection samples not being styled w/ theming widget
  en/components/grids_templates/column-selection.md
  jp/components/grids_templates/column-selection.md
Labels: category-styling, grid-selection, status: verified, version: 11.0.x

#2437 Fixes column selection samples not being styled w/ theming widget
  en/components/grids_templates/column-selection.md
  jp/components/grids_templates/column-selection.md
Labels: category-styling, grid-selection, status: verified, version: 10.2.x

#2438 removing limitation that no longer applies
  en/components/for-of.md
Labels: status: pending-localization

#2439 removing limitation that no longer applies
  en/components/for-of.md
Labels: status: pending-localization

#2449 Updating JP - vnext
  jp/components/for-of.md
  jp/components/grids_templates/live-data.md
Labels: status: localized, status: verified

#2455 [JP] Localization and header fixes. - vNext
  jp/components/general/wpf-to-angular-guide/structural-directives.md
  jp/components/grid/paste-excel.md
  jp/components/grids_templates/column-pinning.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/row-pinning.md
  jp/components/hierarchicalgrid/load-on-demand.md
  jp/components/layout.md
  jp/components/navdrawer.md
  jp/components/treegrid/aggregations.md
Labels: status: localized, status: verified

#2456 [JP] Localization and header fixes - master
  jp/components/general/wpf-to-angular-guide/structural-directives.md
  jp/components/grid/paste-excel.md
  jp/components/grids_templates/column-pinning.md
  jp/components/grids_templates/column-selection.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/row-pinning.md
  jp/components/layout.md
  jp/components/navdrawer.md
  jp/components/treegrid/aggregations.md
Labels: status: localized, status: verified

#2459 Update docfx template version
  package-lock.json
  package.json
Labels: status: verified, version: 10.2.x

#2453 Remove .html from sitemap-vnext
  gulpfile.js
  package-lock.json
  package.json
Labels: SEO, status: verified

#2454 Remove .html from sitemap-master
  gulpfile.js
  package-lock.json
  package.json
Labels: SEO, status: verified

#2462 Fix material icons extended page -vnext
  en/components/material-icons-extended.md
  jp/components/material-icons-extended.md
Labels: status: verified

#2464 fix(toolbar): update the styling section of the topic
  en/components/grids_templates/toolbar.md
Labels: category-styling, status: pending-localization, status: verified, toolbar

#2474 Update topics first iframe -master
  en/components/banner.md
  en/components/card.md
  en/components/date-picker.md
  en/components/divider.md
  en/components/grids_templates/collapsible-column-groups.md
  en/components/grids_templates/live-data.md
  en/components/grids_templates/row-selection.md
  en/components/mask.md
  en/components/navdrawer.md
  en/components/toast.md
  en/components/toggle.md
  jp/components/banner.md
  jp/components/card.md
  jp/components/date-picker.md
  jp/components/divider.md
  jp/components/grids_templates/collapsible-column-groups.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/row-selection.md
  jp/components/mask.md
  jp/components/navdrawer.md
  jp/components/toast.md
  jp/components/toggle.md
Labels: status: verified
