Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-07, with the labels that each got.

#2870 docs(snackbar, toast): update docs according to the latest changes
  en/components/snackbar.md
  en/components/toast.md
Labels: snackbar, status: pending-localization, status: verified, toast, version: 12.1.x

#2872 Add indigo cta banner
  en/images/marketing/indigo-design-app-builder-docfx.jpg
  jp/images/marketing/indigo-design-app-builder-docfx.jpg
  package-lock.json
  package.json
Labels: status: verified

#2873 Add indigo cta banner
  en/images/marketing/indigo-design-app-builder-docfx.jpg
  jp/images/marketing/indigo-design-app-builder-docfx.jpg
  package-lock.json
  package.json
Labels: status: verified

#2874 Update template version with japanese search -vnext
  package-lock.json
  package.json
Labels: status: verified

#2871 [JA] Adding latest changes
  jp/components/date-time-editor.md
  jp/components/snackbar.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/time-picker.md
  jp/components/toast.md
  jp/components/tree.md
  jp/components/treegrid/groupby.md
Labels: status: localized, status: verified

#2864 [JP] Getting Started/Licensing localization - master
  jp/components/general/getting-started.md
  jp/components/general/ignite-ui-licensing.md
Labels: status: localized, status: verified

#2876 Change indigo cta banner -vnext
  en/images/marketing/indigo-design-app-builder-docfx.jpg
  en/images/marketing/indigo-design-app-builder-docfx.png
  jp/images/marketing/indigo-design-app-builder-docfx.jpg
  jp/images/marketing/indigo-design-app-builder-docfx.png
  package-lock.json
  package.json
Labels: status: verified

#2877 Change indigo cta banner -master
  en/images/marketing/indigo-design-app-builder-docfx.jpg
  en/images/marketing/indigo-design-app-builder-docfx.png
  jp/images/marketing/indigo-design-app-builder-docfx.jpg
  jp/images/marketing/indigo-design-app-builder-docfx.png
  package-lock.json
  package.json
Labels: status: verified

#2868 Fix topics links and redirects
  en/components/banner.md
  en/components/grids-and-lists.md
  en/components/grids_templates/cell-editing.md
  en/components/grids_templates/column-moving.md
  en/components/grids_templates/summaries.md
  en/components/slider/slider.md
  en/components/snackbar.md
  en/components/toast.md
  en/web.config
  jp/components/banner.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-moving.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/slider/slider.md
  jp/components/snackbar.md
  jp/components/toast.md
  jp/components/tree.md
  jp/web.config
Labels: status: verified

#2880 Fix topics links and redirects
  en/components/banner.md
  en/components/grids-and-lists.md
  en/components/grids_templates/cell-editing.md
  en/components/grids_templates/column-moving.md
  en/components/grids_templates/summaries.md
  en/components/slider/slider.md
  en/components/snackbar.md
  en/components/toast.md
  en/web.config
  jp/components/banner.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-moving.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/slider/slider.md
  jp/components/snackbar.md
  jp/components/toast.md
  jp/components/tree.md
  jp/web.config
Labels: status: verified

#2875 Topic updates based on new features - staging
  en/components/grid/grid.md
  en/components/grids_templates/column-hiding.md
  en/components/grids_templates/toolbar.md
Labels: status: pending-localization, status: verified

#2881 Topic updates based on new features
  en/components/grid/grid.md
  en/components/grids_templates/column-hiding.md
  en/components/grids_templates/toolbar.md
Labels: status: pending-localization, status: verified

#2879 docs(action-strip): rename color property
  en/components/action-strip.md
  jp/components/action-strip.md
Labels: action-strip, status: awaiting-test, version: 12.1.x

#2866 IgxAccordion documentation topic
  en/components/accordion.md
  en/components/expansion-panel.md
  en/components/toc.yml
Labels: status: verified

#2885 Add explicitEditor for localization code-view -vnext
  en/components/general/localization.md
  package-lock.json
  package.json
Labels: status: verified

#2886 Add explicitEditor for localization code-view -master
  en/components/general/localization.md
  package-lock.json
  package.json
Labels: status: verified

#2893 fix(accordion): broken links
  en/components/accordion.md
Labels: accordion, status: verified

#2894 fix(*): fixing all warnings and broken links #2892
  en/components/accordion.md
  en/components/circular-progress.md
  en/components/combo.md
  en/components/date-range-picker.md
  en/components/dialog.md
  en/components/for-of.md
  en/components/general-breaking-changes-dv.md
  en/components/general-changelog-dv.md
  en/components/general/cli-overview.md
  en/components/general/getting-started.md
  en/components/general/update-guide.md
  en/components/grid/grid.md
  en/components/grid/groupby.md
  en/components/grids-and-lists.md
  en/components/grids.md
  en/components/grids_templates/cell-editing.md
  en/components/grids_templates/conditional-cell-styling.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote-data-operations.md
  en/components/grids_templates/row-adding.md
  en/components/grids_templates/row-editing.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/interactivity/accessibility-compliance.md
  en/components/interactivity/right-to-left-support.md
  en/components/navdrawer.md
  en/components/overlay-styling.md
  en/components/overlay.md
  en/components/select.md
  en/components/themes/sass/css-variables.md
  en/components/themes/sass/elevations.md
  en/components/themes/sass/global-themes.md
  en/components/time-picker.md
  en/components/toc.yml
  en/components/tooltip.md
  en/components/treegrid/tree-grid.md
  jp/components/circular-progress.md
  jp/components/combo.md
  jp/components/date-range-picker.md
  jp/components/dialog.md
  jp/components/general-breaking-changes-dv.md
  jp/components/general-changelog-dv.md
  jp/components/general/cli-overview.md
  jp/components/general/getting-started.md
  jp/components/general/update-guide.md
  jp/components/grid/grid.md
  jp/components/grids.md
  jp/components/themes/sass/css-variables.md
  jp/components/themes/sass/global-themes.md
  package.json
Labels: status: verified

#2862 Add section in excel export topic for multi-column headers export.
  en/components/grids_templates/export-excel.md
Labels: excel-exporter, status: verified

#2888 [JA] Topic updates - vnext
  jp/components/grid/grid.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/toolbar.md
Labels: status: localized, status: verified

#2889 [JA] Topic updates - master
  jp/components/grid/grid.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/toolbar.md
Labels: status: localized, status: verified

#2898 [JP] Add Accordion topic
  jp/components/accordion.md
  jp/components/expansion-panel.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2900 Localization 0907 vnext
  jp/components/circular-progress.md
  jp/components/combo-features.md
  jp/components/combo.md
  jp/components/dialog.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/grids_templates/row-adding.md
  jp/components/grids_templates/row-editing.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/interactivity/accessibility-compliance.md
  jp/components/interactivity/right-to-left-support.md
  jp/components/navdrawer.md
  jp/components/overlay-styling.md
  jp/components/overlay.md
  jp/components/select.md
  jp/components/themes/sass/elevations.md
  jp/components/themes/sass/global-themes.md
  jp/components/time-picker.md
  jp/components/toc.yml
  jp/components/tooltip.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2901 [JP] Fixing links, adding the latest changes - master
  jp/components/circular-progress.md
  jp/components/combo-features.md
  jp/components/combo.md
  jp/components/date-picker.md
  jp/components/date-time-editor.md
  jp/components/dialog.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/grid/groupby.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/grids_templates/row-adding.md
  jp/components/grids_templates/row-editing.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/interactivity/accessibility-compliance.md
  jp/components/interactivity/right-to-left-support.md
  jp/components/navdrawer.md
  jp/components/overlay-styling.md
  jp/components/overlay.md
  jp/components/select.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/themes/sass/elevations.md
  jp/components/themes/sass/global-themes.md
  jp/components/time-picker.md
  jp/components/toc.yml
  jp/components/tooltip.md
  jp/components/tree.md
  jp/components/treegrid/groupby.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2902 feat(tree-grid): updated tree grid group by topic
  en/components/grid/groupby.md
  en/components/treegrid/groupby.md
Labels: status: verified, tree grid

#2903 Fix minor typo, add link for allowCustomValues, remove trailing whitespaces
  en/components/combo.md
Labels: combo, status: verified

#2899 DateTimeEditor IME support section
  en/components/date-picker.md
  en/components/date-range-picker.md
  en/components/date-time-editor.md
  en/components/mask.md
  en/components/time-picker.md
Labels: date-editor, status: verified

#2825 Remove grid with transactions wrapper component
  en/components/general/update-guide.md
  en/components/grids_templates/batch-editing.md
  en/components/toc.yml
Labels: do not merge, severity: medium, status: pending-localization, status: verified, transaction, version: 12.1.x

#2913 Update Accordion topic with SEO improvements
  en/components/accordion.md
Labels: accordion, status: verified

#2908 chore(i18n): Point i18n links to igniteui-angular - vnext
  en/components/general/localization.md
  jp/components/general/localization.md
  kr/components/general/localization.md
Labels: i18n, version: 12.1.x

#2907 chore(i18n): Point i18n links to igniteui-angular - master
  en/components/general/localization.md
  jp/components/general/localization.md
  kr/components/general/localization.md
Labels: i18n, version: 12.0.x

#2915 chore: update changes from 12.1
  en/components/banner.md
  en/components/calendar.md
  en/components/combo-cascading.md
  en/components/combo-remote.md
  en/components/combo.md
  en/components/dialog.md
  en/components/drop-down-virtual.md
  en/components/drop-down.md
  en/components/expansion-panel.md
  en/components/grids_templates/remote-data-operations.md
  en/components/select.md
  en/components/tree.md
  jp/components/banner.md
  jp/components/calendar.md
  jp/components/combo-cascading.md
  jp/components/combo-remote.md
  jp/components/combo.md
  jp/components/dialog.md
  jp/components/drop-down-virtual.md
  jp/components/drop-down.md
  jp/components/expansion-panel.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/select.md
  kr/components/autocomplete.md
  kr/components/banner.md
  kr/components/combo-cascading.md
  kr/components/combo-remote.md
  kr/components/dialog.md
  kr/components/drop-down-virtual.md
  kr/components/drop-down.md
  kr/components/expansion-panel.md
  kr/components/grids_templates/filtering.md
  kr/components/grids_templates/sorting.md
  kr/components/grids_templates/virtualization.md
  kr/components/overlay-position.md
  kr/components/select.md
Labels: status: verified, version: 12.1.x

#2909 [JP] Localization of the the latest topic changes - vNext
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/date-time-editor.md
  jp/components/general/update-guide.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/batch-editing.md
  jp/components/mask.md
  jp/components/time-picker.md
  jp/components/toc.yml
  jp/components/treegrid/groupby.md
Labels: status: localized, status: verified

#2910 [JP] Updating Combo topic - removing trailing whitespaces, adding link - master
  jp/components/combo.md
Labels: status: localized, status: verified

#2917 [JP] Updating Accordion topic - vNext
  jp/components/accordion.md
  jp/components/expansion-panel.md
Labels: status: localized, status: verified

#2916 feat(transactions): update transaction topic w/ details on factories
  en/components/grids_templates/batch-editing.md
  en/components/toc.yml
  en/components/transaction-classes.md
Labels: status: pending-localization, status: verified, transaction, version: 12.1.x

#2918 [JP] Adding latest changes - vnext
  jp/components/expansion-panel.md
  jp/components/general/data-analysis.md
  jp/components/general/update-guide.md
  jp/components/grid/grid.md
  jp/components/grids_templates/batch-editing.md
  jp/components/grids_templates/column-pinning.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/navbar.md
  jp/components/overlay.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2921 Update range picker topic with correct modes
  en/components/date-range-picker.md
Labels: range-date-picker, status: verified

#2924 Upgrade guide and reference updates to IgxGridCell
  en/components/general/update-guide.md
  en/components/grid/grid.md
  en/components/grid/master-detail.md
  en/components/grid/selection-based-aggregates.md
  en/components/grids_templates/cell-editing.md
  en/components/grids_templates/cell-selection.md
  en/components/grids_templates/column-types.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/keyboard-navigation.md
  en/components/grids_templates/live-data.md
  en/components/grids_templates/row-selection.md
  en/components/grids_templates/search.md
  en/components/grids_templates/selection.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/treegrid/tree-grid.md
  jp/components/grid/grid.md
  jp/components/grid/master-detail.md
  jp/components/grid/selection-based-aggregates.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/cell-selection.md
  jp/components/grids_templates/column-types.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/selection.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/treegrid/tree-grid.md
  kr/components/grid/grid.md
  kr/components/grid/selection-based-aggregates.md
  kr/components/grids_templates/editing.md
  kr/components/grids_templates/keyboard-navigation.md
  kr/components/grids_templates/search.md
  kr/components/grids_templates/selection.md
  kr/components/hierarchicalgrid/hierarchical-grid.md
  kr/components/treegrid/tree-grid.md
Labels: grid, hierarchical-grid, status: pending-localization, tree grid, version: 12.1.x

#2914 Updating grid row drag topic
  en/components/grids_templates/row-drag.md
  en/components/toc.yml
Labels: row-drag, status: pending-localization, status: verified

#2926 [JP] Updating transaction topic
  jp/components/grids_templates/batch-editing.md
  jp/components/toc.yml
  jp/components/transaction-classes.md
Labels: status: localized, status: verified

#2919 Update reactive forms topic
  en/components/angular-reactive-form-validation.md
  en/components/combo-cascading.md
  en/components/combo-features.md
  en/components/combo-remote.md
  en/components/combo-templates.md
  en/components/combo.md
  en/components/date-picker.md
  en/components/date-range-picker.md
  en/components/date-time-editor.md
  en/components/input-group-reactive-forms.md
  en/components/input-group.md
  en/components/time-picker.md
  en/components/toc.yml
  en/web.config
  jp/components/combo-cascading.md
  jp/components/combo-features.md
  jp/components/combo-remote.md
  jp/components/combo-templates.md
  jp/components/combo.md
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/date-time-editor.md
  jp/components/input-group.md
  jp/components/time-picker.md
  jp/components/toc.yml
  jp/web.config
  kr/components/autocomplete.md
  kr/components/combo-cascading.md
  kr/components/combo-features.md
  kr/components/combo-remote.md
  kr/components/combo-templates.md
  kr/components/combo.md
  kr/components/input-group.md
  kr/components/toc.yml
  kr/web.config
Labels: reactive-forms, status: verified

#2930 Remove misleading slider paragraph
  en/components/slider/slider.md
Labels: status: pending-localization

#2932 Separate the pagination topic
  en/components/grids_templates/paging.md
  en/components/paginator.md
  en/components/toc.yml
Labels: paging, status: verified

#2923 Separating the topics #2030
  en/components/general/angular-grid-overview-guide.md
  en/components/general/cli-overview.md
  en/components/general/cli/auth-template.md
  en/components/general/cli/getting-started-with-angular-schematics.md
  en/components/general/cli/getting-started-with-cli.md
  en/components/general/cli/step-by-step-guide-using-angular-schematics.md
  en/components/general/cli/step-by-step-guide-using-cli.md
  en/components/general/data-analysis.md
  en/components/general/getting-started.md
  en/components/general/ignite-ui-licensing.md
  en/components/general/ssr-rendering.md
  en/components/toc.yml
  jp/components/general/cli/step-by-step-guide.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/general/ssr-rendering.md
Labels: category-cli, status: verified

#2936 fix(schematics, cli): order topics
  en/components/toc.yml
Labels: category-cli, version: 12.1.x
