Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-03, with the labels that each got.

#2622 Mpopov/button update giude
  en/components/general/update-guide.md
Labels: button, status: pending-localization, version: 12.0.x

#2623 Remove duplicate content - vnext
  en/components/general/update-guide.md
Labels: category-topic, status: verified

#2624 Remove duplicate content - master
  en/components/general/update-guide.md
Labels: category-topic, status: verified

#2628 [JA] Update Guide topic localization - vNext
  jp/components/general/update-guide.md
Labels: status: localized, status: verified

#2635 Fix live-data page code-view -vnext
  en/components/grids-and-lists.md
  en/components/grids_templates/live-data.md
  en/components/treegrid/aggregations.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/live-data.md
  jp/components/treegrid/aggregations.md
  kr/components/grid/grid.md
  kr/components/treegrid/aggregations.md
Labels: status: in-test

#2636 Fix live-data page code-view -master
  en/components/grids-and-lists.md
  en/components/grids_templates/live-data.md
  en/components/treegrid/aggregations.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/live-data.md
  jp/components/treegrid/aggregations.md
  kr/components/grid/grid.md
  kr/components/treegrid/aggregations.md
Labels: status: verified

#2626 docs(*): update toast methods names
  en/components/grids_templates/cell-editing.md
  en/components/list.md
  en/components/time-picker.md
  en/components/toast.md
  jp/components/grids_templates/cell-editing.md
  jp/components/list.md
  jp/components/time-picker.md
  jp/components/toast.md
  kr/components/grids_templates/virtualization.md
  kr/components/list.md
  kr/components/time-picker.md
  kr/components/toast.md
Labels: status: verified, toast, version: 11.1.x

#2634 [JA] Updating Localization topic - master
  jp/components/general/localization.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2633 [JA] Updating Localization topic - vNext
  jp/components/general/localization.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2640 docs(toast): update toast methods names
  en/components/grids_templates/cell-editing.md
  en/components/list.md
  en/components/time-picker.md
  en/components/toast.md
  jp/components/grids_templates/cell-editing.md
  jp/components/list.md
  jp/components/time-picker.md
  jp/components/toast.md
  kr/components/grids_templates/virtualization.md
  kr/components/list.md
  kr/components/time-picker.md
  kr/components/toast.md
Labels: status: verified, toast, version: 12.0.x

#2644 docs(update-guide): list typography refactoring changes
  en/components/general/update-guide.md
Labels: status: pending-localization, status: verified, theming, version: 12.0.x

#2642 [JP] RTL topic localization - vNext
  jp/components/interactivity/right-to-left-support.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2645 docs(themes): add avatar update guide
  en/components/general/update-guide.md
Labels: avatar, status: pending-localization, theme, version: 12.0.x

#2649 refactor(button): update button property names
  en/components/button.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/roundness.md
Labels: button, status: pending-localization, status: verified, theme, version: 12.0.x

#2650 Adding of live-data topic section
  en/components/grids_templates/live-data.md
Labels: status: pending-localization

#2652 Fix data-analysis and ssr-rendering paths -vnext
  en/components/general/data-analysis.md
  en/components/general/ssr-rendering.md
  jp/components/general/data-analysis.md
  jp/components/general/ssr-rendering.md
Labels: status: verified

#2653 Fix data-analysis and ssr-rendering paths -master
  en/components/general/data-analysis.md
  en/components/general/ssr-rendering.md
  jp/components/general/data-analysis.md
  jp/components/general/ssr-rendering.md
Labels: status: verified

#2656 Add Code View for FinJS with Dock Manager - master
  en/components/grids_templates/live-data.md
Labels: status: verified

#2660 Update template version -vnext
  package-lock.json
  package.json
Labels: status: verified

#2659 [JA] Updating topics with the latest changes - vNext
  jp/components/button.md
  jp/components/general/update-guide.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/live-data.md
  jp/components/roundness.md
Labels: status: localized, status: verified

#2661 Add customizing section to row adding topic
  en/components/grids_templates/row-adding.md
Labels: grid, status: pending-localization

#2658 Add Code View for FinJS with Dock Manager - vNext
  en/components/grids_templates/live-data.md
Labels: status: verified

#2664 Revert deleted content
  en/components/avatar.md
  en/components/button.md
  en/components/for-of.md
  en/components/grids_templates/live-data.md
  en/components/grids_templates/multi-row-layout.md
  en/components/icon.md
  en/components/input-group.md
  en/components/radio-button.md
  en/components/ripple.md
  en/components/toast.md
  en/components/treegrid/tree-grid.md
  jp/components/avatar.md
  jp/components/button.md
  jp/components/for-of.md
  jp/components/grids_templates/live-data.md
  jp/components/grids_templates/multi-row-layout.md
  jp/components/icon.md
  jp/components/input-group.md
  jp/components/radio-button.md
  jp/components/ripple.md
  jp/components/toast.md
  kr/components/button.md
  kr/components/carousel.md
  kr/components/grids_templates/multi-row-layout.md
  kr/components/icon.md
  kr/components/input-group.md
  kr/components/radio-button.md
  kr/components/ripple.md
  kr/components/snackbar.md
  kr/components/toast.md
Labels: status: verified

#2669 [JP] Updating to match EN - vnext
  jp/.gitignore
  jp/components/grids_templates/row-adding.md
  jp/components/toc.yml
  jp/components/treegrid/aggregations.md
  jp/components/treegrid/groupby.md
Labels: status: localized, status: verified

#2671 Update contribution file -master
  .github/CONTRIBUTING.md
Labels: status: awaiting-test

#2672 Update topic
  en/components/grids_templates/live-data.md
Labels: status: pending-localization

#2673 Update topic
  en/components/grids_templates/live-data.md
Labels: status: pending-localization

#2677 [JA] Live-data topic localization - vNext
  jp/components/grids_templates/live-data.md
Labels: status: localized, status: verified

#2678 [JA] Live-data topic localization - master
  jp/components/grids_templates/live-data.md
Labels: status: localized, status: verified

#2676 Add SignalR how-to topic
  en/components/general/how-to/signal-r-service-live-data.md
  en/components/toc.yml
  en/images/general/how-to/create-new-project.JPG
  en/images/general/how-to/ws-hub-callers.JPG
  en/images/general/how-to/ws-lets-party.JPG
  en/images/general/how-to/ws-party-1.JPG
Labels: status: pending-localization
