Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-12, with the labels that each got.

#3065 [JA] Latest changes - vnext
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/button.md
  jp/components/general/update-guide.md
  jp/components/icon.md
  jp/components/input-group.md
Labels: status: verified, status: localized

#3058 Add summary template section in Grid Summary topics
  en/components/grids_templates/summaries.md
Labels: grid

#3078 add clarification for providing exporter services - vNext
  en/components/exporter-csv.md
  en/components/exporter-excel.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/toolbar.md
Labels: status: verified

#3083 Add a note about the new animationDuration prop in progress bar
  en/components/linear-progress.md
Labels: status: awaiting-test

#3081 fix(toc): removing the pagination category #3080
  en/components/grids_templates/paging.md
  en/components/toc.yml
  jp/components/grids_templates/paging.md
  jp/components/toc.yml
Labels: status: verified, paging

#3082 add clarification for providing exporter services - master
  en/components/exporter-csv.md
  en/components/exporter-excel.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/toolbar.md
Labels: status: verified

#3095 [JA] Updating with latest changes - vnext
  jp/components/exporter-csv.md
  jp/components/exporter-excel.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/linear-progress.md
Labels: status: verified, status: localized

#3098 chore(navbar): update topic according to the Icon Buttons usage changes in the samples
  en/components/navbar.md
Labels: navbar

#3101 [Localization] Updating JP for #3098
  jp/components/navbar.md
Labels: status: verified, status: localized
