Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-09, with the labels that each got.

#2960 feat(date-range-picker): add custom action buttons sample
  en/components/date-range-picker.md
Labels: status: verified, date-range-picker

#2967 feat(tree-grid): add section for the matching records only filtering strategy to the filtering topic
  en/components/grids_templates/filtering.md
Labels: status: verified

#2970 feat(i18n): add norwegian (nb) language
  en/components/general/localization.md
Labels: status: pending-localization, i18n, version: 12.2.x

#2971 feat(i18n): add norwegian (nb) language
  en/components/general/localization.md
Labels: status: pending-localization, i18n, version: 12.1.x

#2972 fix(drop-down): seo improvements
  en/components/drop-down.md
Labels: status: pending-localization, dropdown, version: 12.2.x

#2973 fix(drop-down): seo improvements
  en/components/drop-down.md
Labels: status: pending-localization, dropdown, version: 12.1.x

#2974 [JA] Adding latest changes - vnext
  jp/components/drop-down.md
  jp/components/general/localization.md
Labels: status: verified, status: localized

#2975 [JA] Adding latest changes - master
  jp/components/drop-down.md
  jp/components/general/localization.md
Labels: status: verified, status: localized

#2968 docs(row-adding): add info about the new beginAddRow methods
  en/components/grids_templates/row-adding.md
Labels: status: pending-localization, status: verified

#2969 docs(row-adding): add info about the new beginAddRow methods - vNext
  en/components/grids_templates/row-adding.md
Labels: status: pending-localization, status: verified

#2977 Add section in excel export topic for freezing header option
  en/components/grids_templates/export-excel.md
Labels: status: awaiting-test, excel-exporter
