Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-10, with the labels that each got.

#2979 Add documentationfor the rowClasses/rowStyles inputs for grid
  en/components/grids_templates/conditional-cell-styling.md
  en/components/toc.yml
Labels: status: pending-localization, status: verified

#2981 [JA] Updating docs - row adding - master
  jp/components/grids_templates/row-adding.md
Labels: status: verified, status: localized

#2984 Merge vnext into master
  en/components/date-range-picker.md
  en/components/grids_templates/conditional-cell-styling.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/state-persistence.md
  en/components/toc.yml
  jp/components/grids_templates/state-persistence.md
Labels: version: 12.2.x

#2985 [JA] Latest updates - vnext
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row-adding.md
  jp/components/toc.yml
Labels: status: verified, status: localized

#2986 [JA] Updating topics to match vNext - master
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/filtering.md
  jp/components/toc.yml
Labels: status: verified, status: localized

#2997 [JP] [vNext] Adding the latest changes - Combo Features, Grid Advanced Filtering
  jp/components/combo-features.md
  jp/components/grids_templates/advanced-filtering.md
Labels: status: verified, status: localized
