Repository IgniteUI/igniteui-docfx, pull requests merged in 2021-02, with the labels that each got.

#2541 [JA] Updating localization for the latest changes. - vNext
  jp/components/animations.md
  jp/components/combo.md
  jp/components/icon.md
  jp/components/input-group.md
  jp/components/material-icons-extended.md
  jp/components/themes/css-variables-theming.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2539 docs(toolbar): remove deprecated properties -vnext
  en/components/grids_templates/advanced-filtering.md
  en/components/grids_templates/batch-editing.md
  en/components/grids_templates/column-hiding.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/row-editing.md
  en/components/treegrid/tree-grid.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/batch-editing.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row-editing.md
  jp/components/treegrid/tree-grid.md
Labels: category-enhancement, status: verified

#2540 docs(toolbar): remove deprecated properties -master
  en/components/grids_templates/advanced-filtering.md
  en/components/grids_templates/batch-editing.md
  en/components/grids_templates/column-hiding.md
  en/components/grids_templates/filtering.md
  en/components/grids_templates/row-editing.md
  en/components/treegrid/tree-grid.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/batch-editing.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row-editing.md
  jp/components/treegrid/tree-grid.md
Labels: category-enhancement, status: verified

#2535 Adding updates related to the new docfx structure
  en/environment.json
  gulpfile.js
  jp/environment.json
  kr/environment.json
  package-lock.json
  package.json
Labels: category-enhancement, status: verified

#2555 Updating JP - vnext
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row-editing.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2556 Updating JP - master
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/row-editing.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, status: verified

#2537 Adding a Grid with Select as editor provider sample - vNext
  en/components/grids_templates/cell-editing.md
  jp/components/grids_templates/cell-editing.md
Labels: grid, select, status: pending-localization, status: verified

#2551 create grouped grid section and edit limitations
  en/components/grids_templates/export-excel.md
Labels: excel-exporter, status: verified

#2557 Adding a note about the focus in templated cells - master #2550
  en/components/grids_templates/cell-editing.md
  jp/components/grids_templates/cell-editing.md
Labels: grid, select, status: awaiting-test

#2558 Adding a note about the focus in the templated cells - vNext #2550
  en/components/grids_templates/cell-editing.md
  jp/components/grids_templates/cell-editing.md
Labels: grid, select

#2563 Updating JP - vnext
  jp/components/grids_templates/cell-editing.md
Labels: status: localized, status: verified

#2326 docs(input-group): add docs for input type file
  en/components/input-group.md
  en/components/label-input.md
Labels: input, input-group, version: 11.1.x

#2569 Updating JP - vnext
  jp/components/carousel.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/selection.md
  jp/components/input-group.md
  jp/components/label-input.md
Labels: status: localized, status: verified

#2568 fix(Events): Updated renamed events (CodeX)
  en/components/carousel.md
  en/components/list.md
  en/components/navbar.md
Labels: list, navbar, status: verified, version: 11.1.x

#2579 nalipiev/grid-select-stackblitz
  en/components/grids_templates/cell-editing.md
Labels: grid, version: 11.1.x

#2575 JP - Adding latest EN changes - vnext
  jp/components/carousel.md
  jp/components/combo.md
  jp/components/grids_templates/cell-editing.md
  jp/components/grids_templates/filtering.md
  jp/components/list.md
  jp/components/navbar.md
Labels: status: localized, status: verified

#2571 Add Formatted Filtering Strategy Section
  en/components/grids_templates/excel-style-filtering.md
Labels: status: verified

#2578 fix(Exporters): Updated renamed events.
  en/components/exporter-csv.md
  en/components/exporter-excel.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/toolbar.md
Labels: excel-exporter, status: pending-localization, status: verified, version: 11.1.x

#2577 Update toc and add column-types topic
  en/components/grid/grid.md
  en/components/grids_templates/column-types.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/summaries.md
  en/components/toc.yml
Labels: status: verified

#2581 Updating JP - master
  jp/components/carousel.md
  jp/components/grids_templates/cell-editing.md
Labels: status: localized, status: verified

#2582 modify selection topics by adding multipleCascade
  en/components/grids_templates/row-selection.md
  en/components/grids_templates/selection.md
Labels: grid-row-selection, status: pending-localization, status: verified, tree grid

#2587 Add live-editing iframe to column-data-types topic
  en/components/grids_templates/column-types.md
Labels: status: verified

#2586 update paging, editing and upgrdade guide topics
  en/components/general/update-guide.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/remote-data-operations.md
Labels: status: verified

#2589 modify cascade selection section
  en/components/grids_templates/row-selection.md
Labels: status: verified

#2595 chore(date-picker): revert date-picker topic
  en/components/date-picker.md
Labels: date-picker, version: 11.1.x

#2593 Updating JP with latest EN changes
  jp/components/drop-down.md
  jp/components/exporter-csv.md
  jp/components/exporter-excel.md
  jp/components/grid/grid.md
  jp/components/grids_templates/column-types.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/selection.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/themes/typography.md
  jp/components/toc.yml
Labels: status: localized, status: verified

#2597 Updating snippets in JA topics - Paging, Remote Data Operations
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/remote-data-operations.md
Labels: status: localized, status: verified

#2413 GroupBy missed api documentation references
  en/components/grid/groupby.md
Labels: category-enhancement, grid-groupby-row-selection, status: pending-localization, status: verified

#2604 fix(Tabs): Removed non-existing links.
  en/components/tabs.md
Labels: status: verified, tabs

#2605 fix(Tabs): Removed non-existing links.
  en/components/tabs.md
Labels: status: verified, tabs

#2608 GroupBy missed api documentation references #2413 master
  en/components/grid/groupby.md
Labels: category-topic, grid, grid-groupby-row-selection, grid-selection, status: verified

#2610 [JP] Adding the latest changes. - vNext
  jp/components/drop-down.md
  jp/components/exporter-csv.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/tabs.md
Labels: status: localized, status: verified

#2611 [JP] Adding the latest changes. - master
  jp/components/drop-down.md
  jp/components/exporter-csv.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/editing.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/shadows.md
  jp/components/tabs.md
Labels: status: localized, status: verified
