Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-08, with the labels that each got.

#3259 feat(docs): add typed forms
  en/components/input-group.md
Labels: status: verified, input-group

#3267 Update complex binding topic - vNext
  en/components/grid/grid.md
Labels: status: pending-localization

#3268 Update complex binding topic - master
  en/components/grid/grid.md
Labels: status: pending-localization

#3270 [JP] Adding the latest topic changes - Cell Editing, Grid topics - vNext
  jp/components/grid/grid.md
  jp/components/grids_templates/cell-editing.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/input-group.md
  jp/components/treegrid/tree-grid.md
Labels: status: verified, status: localized

#3271 [JP] Adding the latest topic changes - Grid, Input Group - master
  jp/components/grid/grid.md
  jp/components/input-group.md
Labels: status: verified, status: localized

#3274 Add short section on column auto-sizing on init.
  en/components/grids_templates/column-resizing.md
Labels: status: verified, grid

#3279 Update code snippets for IgxDateRangePicker
  en/components/date-range-picker.md
  jp/components/date-range-picker.md
Labels: status: resolved, date-range-picker

#3278 docs(rating): adding rating docs.
  en/components/rating.md
  en/components/toc.yml
  jp/components/rating.md
  jp/components/toc.yml
  kr/components/rating.md
  kr/components/toc.yml
Labels: status: pending-localization, status: verified, rating, 14.1.x

#3280 Change height for rowClasses sample container
  en/components/grids_templates/conditional-cell-styling.md
Labels: status: verified, grid

#3285 [JA] Updating column resizing
  jp/components/grids_templates/column-resizing.md
Labels: status: verified, status: localized

#3289 [JA] Adding localization for Rating
  jp/components/rating.md
Labels: status: in-test, status: localized

#3284 added samples to column autosizing
  en/components/grids_templates/column-resizing.md
Labels: status: pending-localization, status: verified, grid, tree grid, hierarchical-grid

#3294 Fix column types meta data vnext
  en/components/grids_templates/column-types.md
Labels: status: verified

#3295 Fix column types meta data - master
  en/components/grids_templates/column-types.md
Labels: status: verified
