Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-05, with the labels that each got.

#3192 [JA] Updating with latest changes
  jp/components/grids_templates/multi-column-headers.md
Labels: status: verified, status: localized

#3191 Update grid sort & group topic
  en/components/grid/groupby.md
  en/components/grids_templates/sorting.md
Labels: group-by, sorting

#3193 [JA] Adding latest changes - master
  jp/components/combo.md
  jp/components/general/update-guide.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/interactivity/accessibility-compliance.md
  jp/components/interactivity/right-to-left-support.md
  jp/components/themes/index.md
  jp/components/themes/sass/configuration.md
  jp/components/themes/sass/global-themes.md
  jp/components/themes/sass/palettes.md
  jp/components/themes/sass/schemas.md
Labels: status: verified, status: localized

#3198 Localization 1205 vnext
  jp/components/grid/groupby.md
  jp/components/grids_templates/sorting.md
Labels: status: verified, status: localized

#3197 feat(slider): updating range slider doc
  en/components/slider/slider.md
Labels: status: pending-localization, slider, version: 13.2.x

#3203 fix(grid): display density links
  en/components/grids_templates/display-density.md
Labels: status: awaiting-test, grid

#3200 docs(expansion-panel): update expansion panel docs
  en/components/expansion-panel.md
Labels: expansion-panel, theme

#3202 [Localization] Updating Slider topic - vNext
  jp/components/slider/slider.md
  jp/components/themes/misc/printing-styles.md
Labels: status: verified, status: localized

#3206 [Localization] Updating Display Density topic - vNext
  jp/components/grids_templates/display-density.md
Labels: status: verified, status: localized

#3210 [Localization] Updating JP to match the latest EN changes - vNext
  jp/components/expansion-panel.md
  jp/components/general-changelog-dv.md
  jp/components/general/update-guide.md
  jp/components/slider/slider.md
Labels: status: verified, status: localized

#3211 [Localization] Updating JP master to match EN, reverting Printing Styles topic.
  jp/components/expansion-panel.md
  jp/components/general-changelog-dv.md
  jp/components/general/update-guide.md
  jp/components/slider/slider.md
  jp/components/themes/misc/printing-styles.md
Labels: status: verified, status: localized

#3201 docs(palettes): update handmade palette docs
  en/components/themes/sass/palettes.md
Labels: status: pending-localization, theme, palettes
