Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-07, with the labels that each got.

#3248 Add yarn snippets
  en/components/general/cli/getting-started-with-angular-schematics.md
  en/components/general/cli/getting-started-with-cli.md
Labels: squash-merge

#3251 Update yarn docs master
  en/components/general/cli/getting-started-with-angular-schematics.md
  en/components/general/cli/getting-started-with-cli.md
Labels: status: pending-localization

#3252 [JA] Updating yarn docs - vnext
  jp/components/general/cli/getting-started-with-angular-schematics.md
  jp/components/general/cli/getting-started-with-cli.md
Labels: status: verified, status: localized

#3253 [JA] Updating yarn docs - master
  jp/components/general/cli/getting-started-with-angular-schematics.md
  jp/components/general/cli/getting-started-with-cli.md
Labels: status: verified, status: localized

#3254 Change import to use inside ignite-ui-licensing.md
  en/components/general/ignite-ui-licensing.md
  jp/components/general/ignite-ui-licensing.md
Labels: status: awaiting-test

#3258 add customizing the toggle and clear icons section to time picker
  en/components/time-picker.md
Labels: time-picker

#3256 docs: remove deprecated properties and change text accordingly
  en/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-hiding.md
  kr/components/grids_templates/column-hiding.md
  kr/components/grids_templates/toolbar.md
Labels: status: pending-localization, status: verified

#3260 [JA] Updating Time Picker - vnext
  jp/components/time-picker.md
Labels: status: verified, status: localized

#3261 [JA] Updating Time Picker - master
  jp/components/time-picker.md
Labels: status: verified, status: localized

#3265 [JP] Adding the latest topic changes - Column Hiding - vNext
  jp/components/grids_templates/column-hiding.md
Labels: status: verified, status: localized

#3266 [JP] Adding the latest topic changes - Column Hiding - master
  jp/components/grids_templates/column-hiding.md
Labels: status: verified, status: localized
