Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-02, with the labels that each got.

#3118 [Localization] Update Guide changes - master
  jp/components/general/update-guide.md
Labels: status: verified, status: localized

#3123 Include the column moving refactoring to the Update Guide
  en/components/general/update-guide.md
Labels: status: verified, grid, column-moving

#3125 docs(toast): add changes to update guide
  en/components/general/update-guide.md
  en/components/toast.md
Labels: status: awaiting-test, toast, update-guide

#3135 [JA] Updating pivot grid topics
  jp/components/general/update-guide.md
  jp/components/pivotgrid/pivot-grid-custom.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/toast.md
  jp/components/toc.yml
Labels: status: verified, status: localized
