Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-11, with the labels that each got.

#3366 update grid crm route
  en/components/general/angular-grid-overview-guide.md
  en/components/grids-and-lists.md
  jp/components/general/angular-grid-overview-guide.md
  jp/components/grids-and-lists.md
Labels: 14.2.x

#3372 Update toc.yml
  en/components/toc.yml
Labels: :eyes: status: in-review

#3375 docs(calendar): update page with new titles and paragraphs - master
  en/components/calendar.md
  jp/components/calendar.md
Labels: status: pending-localization

#3376 docs(calendar): update page with new titles and paragraphs - vnext
  en/components/calendar.md
  jp/components/calendar.md
Labels: status: pending-localization

#3378 docs(qb): modifying SEO for QB topic
  en/components/query-builder.md
Labels: status: pending-localization, SEO, query-builder

#3381 chore(dependencies): update template version - vnext
  package-lock.json
  package.json
Labels: dependencies

#3387 fix(action-strip): apply correct links for pinning and editing actions - vnext
  en/components/action-strip.md
  en/components/general/how-to/how-to-perform-crud.md
  en/components/grids_templates/row-actions.md
  jp/components/action-strip.md
  jp/components/general/how-to/how-to-perform-crud.md
  jp/components/grids_templates/row-actions.md
  kr/components/action-strip.md
Labels: status: awaiting-test

#3386 fix(action-strip): apply correct links for pinning and editing actions - master
  en/components/action-strip.md
  en/components/general/how-to/how-to-perform-crud.md
  en/components/grids_templates/row-actions.md
  jp/components/action-strip.md
  jp/components/general/how-to/how-to-perform-crud.md
  jp/components/grids_templates/row-actions.md
  kr/components/action-strip.md
Labels: status: awaiting-test

#3391 [JA] Updating Calendar and QB
  jp/components/calendar.md
  jp/components/query-builder.md
Labels: status: verified, status: localized

#3367 Add export section to summaries.md
  en/components/grids_templates/summaries.md
Labels: status: pending-localization, status: verified

#3397 Toolbar title and actions update
  en/components/general/update-guide.md
  en/components/grids_templates/column-hiding.md
  en/components/grids_templates/toolbar.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/toolbar.md
  kr/components/grids_templates/column-hiding.md
  kr/components/grids_templates/toolbar.md
Labels: status: pending-localization

#3384 Change code snippets so that they use correct types from the template…
  en/components/general/update-guide.md
  en/components/grid/grid.md
  en/components/grids_templates/batch-editing.md
  en/components/grids_templates/column-pinning.md
  en/components/grids_templates/remote-data-operations.md
  en/components/grids_templates/validation.md
Labels: status: pending-localization, version: 15.0.x

#3320 Add known issue related to validationTrigger blur.
  en/components/grids_templates/validation.md
Labels: status: pending-localization

#3407 chore(*): update card page - vnext
  en/components/card.md
  jp/components/card.md
Labels: status: pending-localization, status: awaiting-test

#3406 chore(*): update carousel page - master
  en/components/carousel.md
  jp/components/carousel.md
Labels: status: pending-localization, status: awaiting-test

#3402 chore(pagination): improve seo of the page - vNext
  en/components/paginator.md
  jp/components/paginator.md
Labels: status: pending-localization, status: awaiting-test

#3401 chore(pagination): improve seo of the page - master
  en/components/paginator.md
  jp/components/paginator.md
Labels: status: pending-localization, status: awaiting-test

#3405 chore(*): update carousel page - vnext
  en/components/carousel.md
  jp/components/carousel.md
Labels: status: pending-localization

#3399 chore(grid): remove duplicated tutorial section - vNext
  en/components/grid/grid.md
  jp/components/grid/grid.md
Labels: status: awaiting-test, grid

#3404 chore(angular-tabs): improve seo of the page - vNext
  en/components/tabs.md
  jp/components/tabs.md
Labels: status: pending-localization, status: awaiting-test, tabs

#3398 chore(grid): remove duplicated tutorial section - master
  en/components/grid/grid.md
  jp/components/grid/grid.md
Labels: status: awaiting-test, grid

#3416 [JP] Adding the latest topic changes, localization fixes - 11/22
  jp/components/accordion.md
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/button-group.md
  jp/components/button.md
  jp/components/carousel.md
  jp/components/charts/features/chart-data-aggregations.md
  jp/components/chip.md
  jp/components/combo-features.md
  jp/components/combo-remote.md
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/expansion-panel.md
  jp/components/exporter-csv.md
  jp/components/general/update-guide.md
  jp/components/grid/grid.md
  jp/components/grids_templates/batch-editing.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/column-pinning.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/remote-data-operations.md
  jp/components/grids_templates/row-editing.md
  jp/components/grids_templates/search.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/validation.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/material-icons-extended.md
  jp/components/navdrawer.md
  jp/components/overlay-position.md
  jp/components/select.md
  jp/components/slider/slider.md
  jp/components/snackbar.md
  jp/components/splitter.md
  jp/components/toc.yml
  jp/components/toggle.md
Labels: status: verified, status: localized

#3414 chore(date-picker): update page with seo improvements - vNext
  en/components/date-picker.md
  jp/components/date-picker.md
Labels: status: pending-localization, date-picker

#3411 chore(date-range-picker): SEO improvements
  en/components/date-range-picker.md
  jp/components/date-range-picker.md
Labels: status: pending-localization, date-range-picker, SEO

#3412 chore(date-picker): update page with seo improvements - master
  en/components/date-picker.md
  jp/components/date-picker.md
Labels: status: pending-localization, status: awaiting-test, date-picker

#3410 chore(month-picker): Month picker SEO improvements
  en/components/month-picker.md
  jp/components/month-picker.md
  kr/components/month-picker.md
Labels: status: pending-localization, month picker, SEO

#3408 chore(*): update card page - master
  en/components/card.md
  jp/components/card.md
Labels: status: pending-localization, status: awaiting-test

#3425 chore(expansion-panel): update page with seo improvements - master
  en/components/expansion-panel.md
  jp/components/expansion-panel.md
Labels: status: pending-localization, expansion-panel

#3424 chore(expansion-panel): update page with seo improvements - vNext
  en/components/expansion-panel.md
  jp/components/expansion-panel.md
Labels: status: pending-localization, expansion-panel

#3383 Simple Combo/Combo: add remote binding section for simple-combo and refactor combo's snippets
  en/components/combo-remote.md
  en/components/simple-combo.md
Labels: status: pending-localization, combo, simple combo

#3427 Add information about newly exposed aggregatorName property
  en/components/pivotGrid/pivot-grid.md
Labels: pivot-grid

#3428 [JP] Updating localization for the latest SEO changes.
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/button-group.md
  jp/components/calendar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/chip.md
  jp/components/combo-features.md
  jp/components/combo-remote.md
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/expansion-panel.md
  jp/components/exporter-csv.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/summaries.md
  jp/components/input-group.md
  jp/components/month-picker.md
  jp/components/navbar.md
  jp/components/overlay-position.md
  jp/components/overlay-styling.md
  jp/components/paginator.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/tabs.md
  jp/components/themes/sass/component-themes.md
  jp/components/time-picker.md
  jp/components/tree.md
Labels: status: verified, status: localized

#3319 Add link to cross-field example in the cancel edit section.
  en/components/grids_templates/validation.md
Labels: status: verified

#3430 feat(image column): updating data types topic
  en/components/grids_templates/column-types.md
  en/components/toc.yml
Labels: status: verified, column-types, version: 15.0.x

#3431 Merging vNext into master
  en/components/combo-remote.md
  en/components/grids_templates/column-types.md
  en/components/grids_templates/validation.md
  en/components/pivotGrid/pivot-grid.md
  en/components/simple-combo.md
  en/components/toc.yml
  jp/components/avatar.md
  jp/components/badge.md
  jp/components/banner.md
  jp/components/button-group.md
  jp/components/calendar.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/chip.md
  jp/components/combo-features.md
  jp/components/combo-remote.md
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/expansion-panel.md
  jp/components/exporter-csv.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/summaries.md
  jp/components/input-group.md
  jp/components/month-picker.md
  jp/components/navbar.md
  jp/components/overlay-position.md
  jp/components/overlay-styling.md
  jp/components/paginator.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/tabs.md
  jp/components/themes/sass/component-themes.md
  jp/components/time-picker.md
  jp/components/tree.md
Labels: status: verified
