Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-03, with the labels that each got.

#3141 docs(bootstrap): update palette colors
  en/components/themes/misc/bootstrap-theming.md
  jp/components/themes/misc/bootstrap-theming.md
Labels: status: verified, theming, version: 13.1.x

#3138 docs(treegrid-esf): add tree filter view section
  en/components/grids_templates/excel-style-filtering.md
Labels: status: verified, tree grid

#3137 chore(tabs): remove the tab component from partially supported RTL
  en/components/interactivity/right-to-left-support.md
  jp/components/interactivity/right-to-left-support.md
Labels: status: verified, tabs

#3144 [JA] Latest updates
  jp/components/general/update-guide.md
  jp/components/grids_templates/excel-style-filtering.md
Labels: status: verified, status: localized

#3154 Remove duplicate topics -vnext
  en/components/row-actions.md
  jp/components/grids_templates/action-strip.md
Labels: status: awaiting-test

#3156 [JA] Updating Pivot Grid
  jp/components/pivotgrid/pivot-grid.md
Labels: status: verified, status: localized

#3155 Remove duplicate topics -master
  en/components/row-actions.md
  jp/components/grids_templates/action-strip.md
Labels: status: verified

#3150 Update existing row styling docs
  en/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/conditional-cell-styling.md
Labels: status: verified, grid, tree grid, hierarchical-grid

#3160 Fix code snippet for Custom Editing Template section
  en/components/grids_templates/column-types.md
  jp/components/grids_templates/column-types.md
Labels: category-topic, status: verified, grid, tree grid, hierarchical-grid

#3161 [JA] Pivot Grid SEO - master
  jp/components/pivotgrid/pivot-grid-custom.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/pivotgrid/pivot-grid.md
Labels: status: verified, status: localized

#3152 Add more information how to use action strip in grids
  en/components/action-strip.md
  en/components/grids_templates/row-actions.md
  jp/components/action-strip.md
  jp/components/grids_templates/row-actions.md
Labels: status: pending-localization, status: verified, grid, action-strip
