Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-01, with the labels that each got.

#3099 Replace column movable prop with the newly exposed moving property in all grid topics
  en/components/grid/grid.md
  en/components/grids_templates/column-moving.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/multi-column-headers.md
  en/components/grids_templates/row-editing.md
  en/components/treegrid/tree-grid.md
  jp/components/grid/grid.md
  jp/components/grids_templates/column-moving.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/multi-column-headers.md
  jp/components/grids_templates/row-editing.md
  jp/components/treegrid/tree-grid.md
  kr/components/grids_templates/column-moving.md
  kr/components/grids_templates/excel-style-filtering.md
  kr/components/grids_templates/multi-column-headers.md
  kr/components/grids_templates/row-editing.md
  kr/components/treegrid/tree-grid.md
Labels: status: awaiting-test, grid, column-moving

#3096 [JA] Updating with latest changes - master
  jp/components/exporter-csv.md
  jp/components/exporter-excel.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/toolbar.md
Labels: status: verified, status: localized

#3108 Update template to 3.1.0-alpha.0
  package-lock.json
  package.json
Labels: status: verified

#3109 Update package lock
  package-lock.json
Labels: status: awaiting-test

#3113 fix: update guide with licensed package
  en/components/general/update-guide.md
Labels: status: pending-localization, version: 13.1.x

#3114 fix: update guide with licensed package
  en/components/general/update-guide.md
Labels: status: pending-localization, version: 13.0.x

#3117 [Localization] Update Guide topic changes - vNext
  jp/components/general/update-guide.md
Labels: status: verified, status: localized

#3116 Fix code snippets in Overlay Styling topic
  en/components/overlay-styling.md
  jp/components/overlay-styling.md
Labels: category-topic, status: verified, status: localized, overlay
