Repository IgniteUI/igniteui-docfx, pull requests merged in 2022-09, with the labels that each got.

#3301 update igniteui-docfx-template version
  package-lock.json
  package.json
Labels: status: verified

#3303 Update template version - vnext
  package-lock.json
  package.json
Labels: status: verified

#3296 Add pivot grid state persistence topic. Add jp version.
  en/.gitignore
  en/components/grids_templates/state-persistence.md
  en/components/pivotGrid/pivot-grid.md
  en/components/toc.yml
  en/web.config
  gulpfile.js
  jp/.gitignore
  jp/components/grids_templates/state-persistence.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/toc.yml
  jp/web.config
  kr/.gitignore
  kr/components/pivotgrid/pivot-grid.md
  kr/web.config
Labels: status: pending-localization, status: verified

#3172 docs: Update printing-styles.md
  en/components/input-group.md
  en/components/themes/misc/printing-styles.md
Labels: status: verified, status: localized, print-styles, version: 13.2.x

#3273 feat(nav-drawer): hierarchical navigation using igx-tree
  en/components/navdrawer.md
Labels: status: pending-localization, status: verified, navdrawer, tree

#3281 docs(validation): grid validation topic
  en/components/grids_templates/validation.md
  en/components/toc.yml
Labels: status: pending-localization, status: verified, grid

#3310 docs(validation): fix heights of the samples for validator
  en/components/grids_templates/validation.md
Labels: status: verified

#3304 feat(list): adding item selection to the topic
  en/components/list.md
  jp/components/list.md
  kr/components/list.md
Labels: status: pending-localization, status: verified, list

#3311 Change some height on containers so that commit buttons show. Remove …
  en/components/grids_templates/validation.md
Labels: status: verified

#3305 Add jp cta banners -vnext
  jp/images/marketing/app-builder-wysiwyg.gif
  jp/images/marketing/ignite-ui-for-angular.gif
  jp/images/marketing/ignite-ui-for-blazor.gif
  jp/images/marketing/ignite-ui-for-react.gif
  package-lock.json
  package.json
Labels: status: verified

#3309 [Localization] [vNext] Adding the latest content changes - State Persistence, Navdrawer, other.
  jp/components/combo.md
  jp/components/general/update-guide.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/state-persistence.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/validation.md
  jp/components/list.md
  jp/components/navdrawer.md
  jp/components/overlay-position.md
  jp/components/overlay-scroll.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/themes/misc/printing-styles.md
  jp/components/themes/sass/component-themes.md
  jp/components/toc.yml
Labels: status: verified, status: localized

#3317 [JP] [master] Adding JP content to master to match EN changes.
  jp/components/combo.md
  jp/components/general/update-guide.md
  jp/components/grids_templates/column-resizing.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/row-actions.md
  jp/components/grids_templates/state-persistence.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/validation.md
  jp/components/list.md
  jp/components/navdrawer.md
  jp/components/overlay-position.md
  jp/components/overlay-scroll.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/themes/misc/printing-styles.md
  jp/components/themes/sass/component-themes.md
  jp/components/toc.yml
Labels: status: verified, status: localized

#3325 Update docfx-template to 3.3.2
  package-lock.json
  package.json
Labels: status: verified

#3326 Update licensing topic and docfx-template to 3.3.2 master
  en/components/general/ignite-ui-licensing.md
  en/components/grids_templates/row-actions.md
  jp/components/general/ignite-ui-licensing.md
  jp/images/marketing/ignite-ui-for-blazor.gif
  jp/images/marketing/ignite-ui-for-react.gif
  package-lock.json
  package.json
Labels: status: verified
