Repository IgniteUI/igniteui-docfx, pull requests merged in 2023-05, with the labels that each got.

#3621 chore(*): update template version
  package-lock.json
  package.json
Labels: status: awaiting-test

#3638 docs(how-to): using the new preview label for stanadalone comps
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: verified, category: how-to

#3643 chore(*): fix indentations
  en/components/autocomplete.md
  en/components/calendar.md
  en/components/expansion-panel.md
  en/components/exporter-csv.md
  en/components/exporter-excel.md
  en/components/grids_templates/column-moving.md
  en/components/grids_templates/editing.md
  en/components/grids_templates/export-excel.md
  en/components/navbar.md
  en/components/query-builder.md
  en/components/select.md
  en/components/tabs.md
  en/components/themes/elevations.md
  en/components/themes/misc/angular-material-theming.md
  en/components/themes/misc/bootstrap-theming.md
  en/components/themes/typography.md
  jp/components/autocomplete.md
  jp/components/calendar.md
  jp/components/expansion-panel.md
  jp/components/exporter-csv.md
  jp/components/exporter-excel.md
  jp/components/grids_templates/export-excel.md
  jp/components/input-group.md
  jp/components/navbar.md
  jp/components/overlay-styling.md
  jp/components/query-builder.md
  jp/components/radio-button.md
  jp/components/select.md
  jp/components/tabs.md
  jp/components/themes/elevations.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/themes/misc/bootstrap-theming.md
  jp/components/themes/typography.md
  kr/components/calendar.md
  kr/components/card.md
  kr/components/carousel.md
  kr/components/combo-features.md
  kr/components/combo-templates.md
  kr/components/drop-down-virtual.md
  kr/components/expansion-panel.md
  kr/components/exporter-csv.md
  kr/components/exporter-excel.md
  kr/components/grids_templates/export-excel.md
  kr/components/navbar.md
  kr/components/query-builder.md
  kr/components/radio-button.md
Labels: status: verified

#3646 feat(standalone): adding directives table
  en/components/general/how-to/how-to-use-standalone-components.md
Labels: status: pending-localization, status: verified

#3644 [JA] Adding localization for standalone components
  jp/components/general/how-to/how-to-use-standalone-components.md
  jp/components/general/update-guide.md
  jp/components/toc.yml
Labels: status: verified, status: localized

#3654 [JA] Localization fixes
  jp/components/general/ignite-ui-licensing.md
  jp/components/general/update-guide.md
Labels: status: localized

#3636 docs(combo): add igxComboHeaderItem section
  en/components/combo-templates.md
Labels: category-topic, status: pending-localization, combo

#3657 [JA] Updating combo-templates
  jp/components/combo-templates.md
Labels: status: verified, status: localized

#3664 fix(grids): update link for api base directive
  en/components/grids_templates/cell-selection.md
  en/components/grids_templates/conditional-cell-styling.md
  en/components/grids_templates/keyboard-navigation.md
  en/components/grids_templates/multi-row-layout.md
  en/components/transaction-classes.md
  jp/components/grids_templates/cell-selection.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/multi-row-layout.md
  jp/components/transaction-classes.md
  kr/components/grids_templates/keyboard-navigation.md
  kr/components/grids_templates/multi-row-layout.md
  kr/components/grids_templates/selection.md
Labels: status: verified

#3671 docs(grids): Fixing broken link in grid sizing
  en/components/grids_templates/sizing.md
Labels: status: verified, grid

#3673 [JA] Updating overlay and overlay-position
  jp/components/overlay-position.md
  jp/components/overlay.md
Labels: status: verified, status: localized
