Repository IgniteUI/igniteui-docfx, pull requests merged in 2023-06, with the labels that each got.

#3670 feat(icon): add section about material symbols
  en/components/icon.md
Labels: status: pending-localization, status: verified, icon

#3691 chore(*): Increase radio button samples height
  en/components/radio-button.md
Labels: status: verified

#3746 fix(theme): typography table was not formatted
  en/components/themes/typography.md
Labels: status: pending-localization, status: verified, theme

#3764 Update toc.yml
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: in-review

#3763 Update toc.yml
  kr/components/toc.yml
Labels: status: in-review

#3725 chore(*): Update readme sections
  README.md
Labels: status: verified

#3742 fix(*): incorrectly displayed button topic section
  en/components/button.md
Labels: status: verified

#3767 Fixing gridCopy link
  en/components/grids_templates/clipboard-interactions.md
  jp/components/grids_templates/clipboard-interactions.md
Labels: status: resolved, grid

#3769 refactor(themes): update roundness topic
  en/components/themes/sass/roundness.md
Labels: status: pending-localization, status: verified, theme, 16.0.x

#3765 Update toc.yml
  en/components/toc.yml
Labels: status: in-review

#3771 Refactor stepper, accordion and autocomplete topics
  en/components/accordion.md
  en/components/autocomplete.md
  en/components/stepper.md
Labels: status: pending-localization

#3782 Topics update
  en/components/card.md
  en/components/carousel.md
  en/components/expansion-panel.md
  en/components/grid/groupby.md
  en/components/grids_templates/advanced-filtering.md
  en/components/grids_templates/excel-style-filtering.md
  en/components/grids_templates/paging.md
  en/components/grids_templates/search.md
  en/components/grids_templates/summaries.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/paginator.md
  en/components/pivotGrid/pivot-grid-custom.md
  en/components/pivotGrid/pivot-grid-features.md
  en/components/pivotGrid/pivot-grid.md
  en/components/stepper.md
  en/components/toc.yml
  en/components/treegrid/groupby.md
  jp/components/accordion.md
  jp/components/autocomplete.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/expansion-panel.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/search.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/paginator.md
  jp/components/pivotgrid/pivot-grid-custom.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/stepper.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/toc.yml
  jp/components/treegrid/groupby.md
  kr/components/grid/selection-based-aggregates.md
  kr/components/grids_templates/column-moving.md
  kr/components/grids_templates/column-pinning.md
  kr/components/grids_templates/export-excel.md
  kr/components/grids_templates/filtering.md
  kr/components/grids_templates/row-pinning.md
  kr/components/grids_templates/search.md
  kr/components/grids_templates/summaries.md
  kr/components/month-picker.md
  kr/components/pivotgrid/pivot-grid-custom.md
  kr/components/pivotgrid/pivot-grid-features.md
  kr/components/pivotgrid/pivot-grid.md
  kr/components/time-picker.md
Labels: status: pending-localization

#3788 mdd-preview-toolbar-toc
  en/components/toc.yml
  jp/components/toc.yml
  kr/components/toc.yml
Labels: status: in-review

#3801 [Localization] Updating topics with the latest changes.
  jp/components/accordion.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/expansion-panel.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/summaries.md
  jp/components/stepper.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/themes/sass/roundness.md
Labels: status: localized

#3802 Updating master with the latest JA changes.
  jp/components/accordion.md
  jp/components/card.md
  jp/components/carousel.md
  jp/components/expansion-panel.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/summaries.md
  jp/components/stepper.md
  jp/components/themes/misc/angular-material-theming.md
  jp/components/themes/sass/roundness.md
Labels: status: localized
