Repository IgniteUI/igniteui-docfx, pull requests merged in 2023-10, with the labels that each got.

#3898 fix(pivot-grid): displaying the note section and the links properly
  en/components/pivotGrid/pivot-grid-custom.md
  en/components/pivotGrid/pivot-grid-features.md
  en/components/pivotGrid/pivot-grid.md
Labels: status: verified, pivot-grid

#3904 [JP] Updating Pivot Grid topics - Note sections, other fixes
  jp/components/pivotgrid/pivot-grid-custom.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/transaction-classes.md
Labels: status: verified, status: localized

#3906 Update button group selection section
  en/components/button-group.md
Labels: status: awaiting-test, button group, 16.1.0

#3912 [JP] Updating Button Group topic with the latest changes
  jp/components/button-group.md
Labels: status: verified, status: localized

#3919 fix(grid): displaying the note sections in the grid topics properly
  en/components/grid/groupby.md
  en/components/grids_templates/cell-selection.md
  en/components/grids_templates/column-types.md
  en/components/grids_templates/keyboard-navigation.md
  en/components/grids_templates/row-actions.md
  en/components/grids_templates/row-selection.md
  en/components/grids_templates/sorting.md
  en/components/grids_templates/state-persistence.md
Labels: status: resolved, grid

#3927 [JA] Fixing note sections
  jp/components/grid/groupby.md
  jp/components/grids_templates/cell-selection.md
  jp/components/grids_templates/column-types.md
  jp/components/grids_templates/keyboard-navigation.md
  jp/components/grids_templates/row-actions.md
  jp/components/grids_templates/row-selection.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/state-persistence.md
Labels: status: localized

#3920 fix(grid): displaying the table properly
  en/components/grids_templates/validation.md
Labels: status: verified, grid

#3961 [JA] Validation topic - table fixes, other changes.
  jp/components/grids_templates/validation.md
Labels: status: verified, status: localized

#3926 docs(drop-down): add multi-level menu section
  en/components/drop-down.md
Labels: category-topic, status: verified, dropdown

#3968 Updating JP for #3926
  jp/components/drop-down.md
Labels: status: localized
