Repository IgniteUI/igniteui-docfx, pull requests merged in 2023-02, with the labels that each got.

#3479 [Localization] Updating Typography docs, Autocomplete topic, spacing fixes.
  jp/components/accordion.md
  jp/components/autocomplete.md
  jp/components/card.md
  jp/components/date-picker.md
  jp/components/drop-down-hierarchical-selection.md
  jp/components/expansion-panel.md
  jp/components/general/getting-started.md
  jp/components/general/ignite-ui-licensing.md
  jp/components/general/ssr-rendering.md
  jp/components/general/update-guide.md
  jp/components/grid/groupby.md
  jp/components/grids_templates/column-pinning.md
  jp/components/grids_templates/column-types.md
  jp/components/grids_templates/excel-style-filtering.md
  jp/components/grids_templates/filtering.md
  jp/components/grids_templates/sorting.md
  jp/components/grids_templates/summaries.md
  jp/components/grids_templates/toolbar.md
  jp/components/input-group.md
  jp/components/mask.md
  jp/components/month-picker.md
  jp/components/overlay-styling.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/slider/slider.md
  jp/components/snackbar.md
  jp/components/tabs.md
  jp/components/themes.md
  jp/components/themes/sass/animations.md
  jp/components/themes/sass/typography.md
  jp/components/tooltip.md
Labels: status: verified, status: localized

#3487 Update jp grids and lists page
  jp/components/grids-and-lists.md
Labels: status: verified

#3481 docs(simple-combo): update keyboard navigation section
  en/components/simple-combo.md
Labels: category-topic, status: awaiting-test, keyboard-navigation, simple combo

#3490 fix: igx for version 14
  en/components/general/update-guide.md
  jp/components/general/update-guide.md
Labels: update-guide, version: 15.0.x

#3492 docs(igx-select): separate code snippets and sections
  en/components/select.md
Labels: category-topic, status: verified, select

#3489 feat(theming): creating a new how-to doc
  en/components/general/how-to/how-to-customize-theme.md
  en/components/themes/index.md
  en/components/toc.yml
  en/images/general/theming-walkthrough/customizing-updated-toolbar.png
  en/images/general/theming-walkthrough/getting-started-appbuilder-theming.png
  en/images/general/theming-walkthrough/getting-started-appbuilder.png
  en/images/general/theming-walkthrough/getting-started-dark-app.png
  en/images/general/theming-walkthrough/getting-started-running-app.png
  en/images/general/theming-walkthrough/optimizing-after-exclude.png
  en/images/general/theming-walkthrough/optimizing-after-module-lazyload.png
  en/images/general/theming-walkthrough/optimizing-initial-build.png
Labels: status: pending-localization, status: verified, theming, category: how-to

#3488 [JP] Updating Simple Combo topic - keyboard navigation
  jp/components/simple-combo.md
Labels: status: verified, status: localized

#3497 [JP] Adding new Customizing Ignite UI Theming topic
  jp/components/general/how-to/how-to-customize-theme.md
  jp/components/select.md
  jp/components/themes/index.md
  jp/components/toc.yml
  jp/images/general/theming-walkthrough/customizing-updated-toolbar.png
  jp/images/general/theming-walkthrough/getting-started-appbuilder-theming.png
  jp/images/general/theming-walkthrough/getting-started-appbuilder.png
  jp/images/general/theming-walkthrough/getting-started-dark-app.png
  jp/images/general/theming-walkthrough/getting-started-running-app.png
  jp/images/general/theming-walkthrough/optimizing-after-exclude.png
  jp/images/general/theming-walkthrough/optimizing-after-module-lazyload.png
  jp/images/general/theming-walkthrough/optimizing-initial-build.png
Labels: status: verified, status: localized

#3499 Add limitation to the Excel Export topic regarding cell styling
  en/components/grids_templates/export-excel.md
Labels: status: verified, excel-exporter

#3504 docs(theming): extending customization doc
  en/components/general/how-to/how-to-customize-theme.md
  en/images/general/theming-walkthrough/customizing-color-schema-dark.png
  en/images/general/theming-walkthrough/customizing-color-schema-light.png
Labels: category-topic, status: pending-localization, status: awaiting-test

#3505 fix(theme): making code snippets consistent
  en/components/themes/sass/component-themes.md
Labels: status: pending-localization, status: verified, theme

#3509 feat(theming): forgot to tag as new
  en/components/toc.yml
Labels: theming

#3512 [JP] Adding the latest topic changes, other fixes - 27 Feb 23
  jp/components/general/how-to/how-to-customize-theme.md
  jp/components/grids_templates/export-excel.md
  jp/components/themes/sass/component-themes.md
  jp/components/toc.yml
  jp/images/general/theming-walkthrough/customizing-color-schema-dark.png
  jp/images/general/theming-walkthrough/customizing-color-schema-light.png
Labels: status: verified, status: localized
