Repository IgniteUI/igniteui-docfx, pull requests merged in 2024-08, with the labels that each got.

#5902 refactor(icon-service): update icon references and usage
  en/components/icon-service.md
Labels: status: pending-localization

#5923 [JA] Update Icon Service topic
  jp/components/badge.md
  jp/components/icon-button.md
  jp/components/icon-service.md
  jp/components/toc.yml
Labels: status: localized

#5922 Updating master with changes from vnext
  en/components/bullet-graph.md
  en/components/charts/features/chart-axis-options.md
  en/components/charts/features/chart-data-selection.md
  en/components/charts/types/data-pie-chart.md
  en/components/charts/types/radial-chart.md
  en/components/general-changelog-dv.md
  en/components/linear-gauge.md
  jp/components/badge.md
  jp/components/bullet-graph.md
  jp/components/charts/chart-overview.md
  jp/components/charts/features/chart-axis-options.md
  jp/components/charts/features/chart-data-filtering.md
  jp/components/charts/features/chart-data-legend.md
  jp/components/charts/features/chart-data-selection.md
  jp/components/charts/features/chart-data-tooltip.md
  jp/components/charts/features/chart-highlight-filter.md
  jp/components/charts/types/bubble-chart.md
  jp/components/charts/types/treemap-chart.md
  jp/components/general-changelog-dv.md
  jp/components/icon-button.md
  jp/components/icon-service.md
  jp/components/radial-gauge.md
  jp/components/toc.yml
  kr/components/charts/chart-overview.md
Labels: do not merge
