Repository IgniteUI/igniteui-docfx, pull requests merged in 2024-02, with the labels that each got.

#5691 fix(slider): Update the Slider docs' guidance on where to import Hamm…
  en/components/slider/slider.md
Labels: bug, status: pending-localization, status: awaiting-test, slider

#5689 Adding a note for the open method in the dropdown component
  en/components/drop-down-hierarchical-selection.md
  en/components/drop-down.md
Labels: status: pending-localization, status: verified, dropdown

#5710 docs(icon-btn): update guide and toc
  en/components/general/update-guide.md
  en/components/toc.yml
  jp/components/toc.yml
Labels: status: pending-localization, update-guide, toc, 17.1.x, icon-button

#5702 docs(*): Updating JA - Dropdown, Standalone, Slider - vnext
  jp/components/drop-down-hierarchical-selection.md
  jp/components/drop-down.md
  jp/components/general/how-to/how-to-use-standalone-components.md
  jp/components/slider/slider.md
Labels: status: localized

#5713 docs(hgrid): update chid grid simpler toolbar setup w/ 17.1
  en/components/grids_templates/toolbar.md
Labels: status: pending-localization, status: verified, hierarchical-grid, toolbar, 17.1.x

#5717 feat(text-highlight): updating docs for 17.1
  en/components/texthighlight.md
  package-lock.json
Labels: status: pending-localization, text-highlight, 17.1.x

#5716 [JA] Update Guide - 17.1.x, Date Picker fixes
  jp/components/date-picker.md
  jp/components/general/update-guide.md
Labels: status: localized

#5718 Add additional information about hammer being optional now.
  en/components/calendar.md
  en/components/carousel.md
  en/components/date-picker.md
  en/components/date-range-picker.md
  en/components/grid/grid.md
  en/components/hierarchicalgrid/hierarchical-grid.md
  en/components/list.md
  en/components/month-picker.md
  en/components/navdrawer.md
  en/components/slider/slider.md
  en/components/time-picker.md
  en/components/treegrid/tree-grid.md
Labels: status: pending-localization

#3986 chore(*): update guide for grid events
  en/components/general/update-guide.md
  jp/components/general/update-guide.md
Labels: status: localized

#5726 [JA] Updating Toolbar and Text Highlight with the latest changes
  jp/components/calendar.md
  jp/components/carousel.md
  jp/components/date-picker.md
  jp/components/date-range-picker.md
  jp/components/grid/grid.md
  jp/components/grids_templates/toolbar.md
  jp/components/hierarchicalgrid/hierarchical-grid.md
  jp/components/list.md
  jp/components/month-picker.md
  jp/components/navdrawer.md
  jp/components/slider/slider.md
  jp/components/spreadsheet_overview.md
  jp/components/texthighlight.md
  jp/components/time-picker.md
  jp/components/treegrid/tree-grid.md
Labels: status: localized, 17.1.x

#5732 fix(update-guide): update icon btn info
  en/components/general/update-guide.md
Labels: status: pending-localization, status: awaiting-test, update-guide

#5738 [JA] Update Guide - Icon Button section
  jp/components/general/update-guide.md
Labels: status: localized, update-guide

#5727 Refactor tree & hierarchical grid conditional styling snippets
  en/components/grids_templates/conditional-cell-styling.md
Labels: status: awaiting-test

#5739 [JA] Updating conditional styling snippets to match EN topic
  jp/components/grids_templates/conditional-cell-styling.md
Labels: status: localized
