Repository IgniteUI/igniteui-docfx, pull requests merged in 2024-06, with the labels that each got.

#5828 docs(pivot-grid): Update docs with the new pivot features
  en/components/general/update-guide.md
  en/components/grids_templates/export-excel.md
  en/components/grids_templates/state-persistence.md
  en/components/pivotGrid/pivot-grid-features.md
  en/components/pivotGrid/pivot-grid.md
Labels: status: pending-localization

#5829 docs(grid): fix outdated section
  en/components/grids_templates/paging.md
Labels: status: awaiting-test, grid, paging, version: 18.0.x

#5824 docs(*): Updating Card, Sizing topics - JA.
  jp/components/button-group.md
  jp/components/button.md
  jp/components/card.md
  jp/components/display-density.md
  jp/components/general/how-to/how-to-customize-theme.md
  jp/components/grids-and-lists.md
  jp/components/grids_templates/conditional-cell-styling.md
  jp/components/grids_templates/sizing.md
  jp/components/grids_templates/summaries.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/toc.yml
Labels: status: localized

#5838 docs(*): Updating JA with the latest changes - Pivot Grid features.
  jp/components/general/update-guide.md
  jp/components/grids_templates/export-excel.md
  jp/components/grids_templates/paging.md
  jp/components/grids_templates/state-persistence.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/stepper.md
Labels: status: localized

#5835 fix(hGrid): display the note sections in row selection topic
  en/components/grids_templates/row-selection.md
Labels: status: verified, hierarchical-grid, grid-row-selection

#5836 feat(overlay, toggle): update documentation with the new setOffset feature
  en/components/overlay-position.md
  en/components/toggle.md
Labels: status: awaiting-test, overlay, toggle

#5837 fix(pivot-grid): correct unique rows
  en/components/pivotGrid/pivot-grid.md
Labels: status: verified, pivot-grid

#5842 docs(*): Updating JA for #5836, other updates.
  jp/components/grids_templates/row-selection.md
  jp/components/overlay-position.md
  jp/components/pivotgrid/pivot-grid.md
  jp/components/toggle.md
Labels: status: localized

#5807 docs(update): Update the update guide for 18.0.x for display density …
  en/components/general/update-guide.md
Labels: grid, tree grid, hierarchical-grid, pivot-grid

#5843 Remove old new/updated labels. Mark pivot grid topics as updated.
  en/components/toc.yml
Labels: status: pending-localization

#5845 Updating Japanese TOC + 18.0.x Update Guide
  jp/components/general/update-guide.md
  jp/components/toc.yml
Labels: status: localized, version: 18.0.x

#5852 docs(sorting): fix initial sorting expressions
  en/components/grids_templates/sorting.md
Labels: status: verified, grid, tree grid, hierarchical-grid, sorting

#5858 Mdd fix changelog link
  en/components/general-changelog-dv.md
Labels: status: in-review

#5859 chore(*): update template with dv samples correct git paths
  package-lock.json
  package.json
Labels: status: awaiting-test
