Repository IgniteUI/igniteui-docfx, pull requests merged in 2024-07, with the labels that each got.

#5869 docs(mask): update code snippets for focus and blur formatting behavior
  en/components/mask.md
Labels: status: verified, mask

#5860 [Localization] Updating JA to match the latest EN changes - DV Changelog, other fixes.
  jp/components/general-changelog-dv.md
  jp/components/grids_templates/advanced-filtering.md
  jp/components/grids_templates/column-hiding.md
  jp/components/grids_templates/sorting.md
  jp/components/mask.md
Labels: status: localized

#5884 feat(*): Add azure pipelines
  azure-pipelines/azure-pipelines-en.yml
  azure-pipelines/azure-pipelines-jp-kr.yml
  azure-pipelines/templates/build-tasks.yml
  gulpfile.js
Labels: CI

#5892 chore(*): use cross-env for setting environment variables
  package-lock.json
  package.json
Labels: status: awaiting-test, CI

#5822 feat(icon-service): add icon service topic
  en/components/icon-service.md
  en/components/icon.md
  en/components/toc.yml
Labels: status: pending-localization, icon, version: 18.1.x, icon-service

#5900 [JA] Icon Service topic, other updates
  jp/components/icon-service.md
  jp/components/icon.md
  jp/components/pivotgrid/pivot-grid-features.md
  jp/components/toc.yml
Labels: status: localized, version: 18.1.x
