Repository IgniteUI/igniteui-docfx, pull requests merged in 2025-02, with the labels that each got.

#6030 [JA] SSR Rendering topic update, other fixes
  jp/components/chip.md
  jp/components/general/data-analysis.md
  jp/components/general/how-to/how-to-use-standalone-components.md
  jp/components/general/ssr-rendering.md
  jp/components/toc.yml
Labels: status: localized

#6038 Mdd update toc chart features
  en/components/toc.yml
Labels: status: in-review

#6046 Update Query Builder topic
  en/components/query-builder.md
  en/components/toc.yml
  en/images/general/query-builder-drag-and-drop.gif
  en/images/general/query-builder-keyboard-drag-and-drop.gif
Labels: status: pending-localization, status: verified, query-builder

#6060 docs(query-builder): update snippets, gifs and code views heights
  en/components/query-builder.md
  en/images/general/query-builder-drag-and-drop.gif
  en/images/general/query-builder-keyboard-drag-and-drop.gif
Labels: status: verified

#6059 [JA] Update Query Builder topic
  jp/components/grids_templates/state-persistence.md
  jp/components/query-builder.md
  jp/components/toc.yml
  jp/images/general/query-builder-drag-and-drop.gif
  jp/images/general/query-builder-keyboard-drag-and-drop.gif
Labels: status: localized
